### PR TITLE
Is #22680: api-exporter-fragment is not up-to-date

### LINKED ISSUE #22680: api-exporter-fragment is not up-to-date
Any package listed in the api-exporter-fragment is automatically visible to deployed Java EE applications via "Common Class Loader." As of bacf743a some packages introduced in EE8, such as javax.json.*, javax.batch.* (and few others) are missing.
Some background wrt this fragment can be found also in #14992

### PR DESCRIPTION
**Pull request by lukasj**
Fixes #22680

### CODE REVIEW

**Comment by lukasj** [comment]
PR #22677 should fix errors seen here

**Review by romain-grecourt — APPROVED** [review]
seems good. Not sure how accurate the package list is, how did you come up with it ?

**Comment by lukasj** [comment]
Took javadoc of EE8 and SE8 and added all missing packages except of java.* ones and one omg related which was not present in original revision.

I

**Review by bshannon — APPROVED** [review]
The Java EE API list is correct.

I don't know how it was decided which Java SE APIs to include so I don't know if that list is correct.

There's a bunch of other com.* and org.* APIs and I don't know why they're included.

**Comment by romain-grecourt** [comment]
@lukasj I merged pr #22677, you can rebase your branch to fix the pipeline failures.

**Comment by lukasj** [comment]
@romain-grecourt done

**Comment by romain-grecourt** [comment]
@lukasj OK, I'll monitor the pipeline and merge it when it passes.

**Pull request merged**
