### PR TITLE
Integrate Parsson 1.1.7

### PR DESCRIPTION
**Pull request by avpinchuk**
Changes: https://github.com/eclipse-ee4j/parsson/compare/1.1.6...1.1.7

### CODE REVIEW

**Comment by avpinchuk** [comment]
Partially fixes #25009. Fixes stack traces in `server.log` related to JSON Processing.

**Comment by avpinchuk** [comment]
Standalone JSON-P and JSON-P Pluggability TCKs passed.

**Review by pzygielo — APPROVED** [review]

**Comment by arjantijms** [comment]
If I'm not mistaken parson updates cause failures in the REST TCK, at least that was the reason to revert last time.

We should look at why that TCK fails after this update.

**Comment by avpinchuk** [comment]
> If I'm not mistaken parson updates cause failures in the REST TCK, at least that was the reason to revert last time.
> 
> We should look at why that TCK fails after this update.

Thank you! I'll take a look.

**Comment by avpinchuk** [comment]
@arjantijms, local REST TCK passed. Did we revert Parsson and not Yasson?

**Review by dmatej — APPROVED** [review]

**Comment by arjantijms** [comment]
> @arjantijms, local REST TCK passed. Did we revert Parsson and not Yasson?
> 
> UPD: [e305bb2](https://github.com/eclipse-ee4j/glassfish/commit/e305bb2648b205d06c4c125377507a7bd284017b)

Indeed, Yasson 3.0.4 seemed problematic.

**Comment by avpinchuk** [comment]
> Indeed, Yasson 3.0.4 seemed problematic.

@arjantijms, REST TCK passed on JDK 17, but failed on JDK 11.

Yasson 3.0.3 was compiled with `target=11`, whereas Yasson 3.0.4 was compiled with `target=17`.

Also Yasson 3.0.4 contains methods than are missing in Java 11 (e.g., `Class.isRecord()`). In Yasson 3.0.3 these methods where located in MR-JAR folder for Java 16, in Yasson 3.0.4 - under default (non-MR) path.

**Comment by pzygielo** [comment]
@m0mus @Verdent - can you re-do yasson 3.0.4 and replace staged version?

**Comment by arjantijms** [comment]
>  In Yasson 3.0.3 these methods where located in MR-JAR folder for Java 16, in Yasson 3.0.4 - under default (non-MR) path.

Thanks for finding the root cause of the failure!

**Pull request merged**
