### PR TITLE
Make ASM API version and bytecode level consistent with used ASM library and minimal requred Java version

### PR DESCRIPTION
**Pull request by avpinchuk**
In this PR

* Raise ASM API version to ASM9 in all places
* Raise bytecode level to Java 11 in all places
* Replace usage of deprecated ASM API

Signed-off-by: Alexander Pinchuk <alexander.v.pinchuk@gmail.com>

### CODE REVIEW

**Review by dmatej — COMMENTED** [review]
Great, thank you! We have some issues with Nexus, which affects Jenkins, so we have to wait a bit for the execution. For sure I will then run the TCK too.

**Comment by dmatej** [comment]
TCK of this PR vs. TCK 10.0.0 (old packages) is running here: https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/10.0.x/49/

**Comment by dmatej** [comment]
Could you create a PR for HK2 too, if you have some time, please?
https://github.com/eclipse-ee4j/glassfish-hk2/issues/779

**Comment by avpinchuk** [comment]
OK, I will try tonight.

**Review by dmatej — APPROVED** [review]

**Pull request merged**
