### PR TITLE
Integrating Glassfish Shoal Dependency

### PR DESCRIPTION
**Pull request by jayasheelankumar**
Updating the maven co-ordinates and version for shoal dependency

quicklook test passed successfully.

Signed-off-by: Jayasheelan Kumar <jayasheelan.kumar@oracle.com>

### CODE REVIEW

**Comment by romain-grecourt** [comment]
@jayasheelankumar please refresh your branch to pickup latest EE4J_8 this should clear the pipeline errors.

**Comment by arindam-bandyopadhyay** [comment]
Run CTS tests

**Comment by arindam-bandyopadhyay** [comment]
Run CTS tests

**Comment by arindam-bandyopadhyay** [comment]
Run CTS tests

**Comment by arindam-bandyopadhyay** [comment]
Run CTS tests

**Comment by arindam-bandyopadhyay** [comment]
Run CTS tests

**Comment by jayasheelankumar** [comment]
@romain-grecourt I merged the EE4J_8 branches and again the tests are failing. Can you please suggest?

**Comment by arindam-bandyopadhyay** [comment]
Run CTS tests

**Comment by arindam-bandyopadhyay** [comment]
Run CTS tests

**Comment by arindam-bandyopadhyay** [comment]
Run CTS tests

**Comment by romain-grecourt** [comment]
@arindam-bandyopadhyay I don't think it makes sense to run the cts on this PR.

**Comment by romain-grecourt** [comment]
@jayasheelankumar the failing tests are in nucleus test suites that are known to be failing intermittently. I'll restart the pipeline to see if they fail again.

**Comment by romain-grecourt** [comment]
@jayasheelankumar the tests do fail consistently, this has to do with your changeset. You should probably debug one of the failing test.

**Review by romain-grecourt — APPROVED** [review]

**Pull request merged**
