### PR TITLE
#22913 Incorporate JSON Binding 2.0.0 into GlassFish 6.0

### LINKED ISSUE #22913: Incorporate JSON Binding 2.0.0 into GlassFish 6.0
Also requires integration of jakarta version of Yasson into GlassFish

### PR DESCRIPTION
**Pull request by arjantijms**
Fixes #22913

**Summary of what was done**

* JSON Binding 2.0.0 and Yasson 2.0 were integrated (incorporated).
* Based on PR https://github.com/eclipse-ee4j/glassfish/pull/22972

**Why are the tests not running**

We decided in the GF project to first integrate everything and thereafter start looking at making the tests work again.

### CODE REVIEW

**Comment by smillidge** [comment]
Most of the changes seem to be bean validation?

**Comment by arjantijms** [comment]
@smillidge 

> Most of the changes seem to be bean validation?

That only looks that way since the PR is based on PR #22972

**Comment by smillidge** [comment]
Now it is showing 0 changes as #22972  is merged

**Comment by arjantijms** [comment]
@smillidge 

Indeed, the commit for this was very small, it was this one:

https://github.com/eclipse-ee4j/glassfish/commit/84abf0f47bf2dabe0eb857793eade787f58979d0

By basing one PR on the other, it ended up at the other PR instead. Could be my mistake or maybe GitHub messed up, hard to see. At any length the right commit is in, so this one can be closed.

**Comment by arjantijms** [comment]
ps The local branch to which I did the commit, and the branch from which the JSON-B PR was done are correct though: https://github.com/arjantijms/glassfish/commits/glassfish-22913

Slightly puzzled how commit https://github.com/eclipse-ee4j/glassfish/commit/84abf0f47bf2dabe0eb857793eade787f58979d0 went up in PR https://github.com/eclipse-ee4j/glassfish/pull/22972 as well.

**Comment by smillidge** [comment]
Possibly branched the second branch off the first rather than master?

**Comment by arjantijms** [comment]
> Possibly branched the second branch off the first rather than master?

Yes indeed

**Pull request closed without merging**
