### PR TITLE
Fix Enterprise Beans deployment error

### LINKED ISSUE #24354: Enterprise Beans deployment error
## Environment Details
* GlassFish Version (and build number): 7.0.3-SNAPSHOT
* JDK version: Liberica JDK 17.0.6
* OS: Windows 10, Ubuntu 22.04
* Database: None

----------

## Problem Description

A next deployment error may occurs under some circumstances when we try to deploy an `ejb-jar`, `ear` or `war` application:

image

The `server log` contains next traces:

image
image

This may happens where next conditions are met:

1. An application contains Session Bean doesn't have the no-arg constructor,
2. This Session Bean have a CDI bean constructor annotated with `@Inject`, and
3. This Session Bean have an one or more "regular" constructors with parameters one or more of them have a primitive type.

## Steps to reproduce

A reproducer can be downloaded here: https://github.com/avpinchuk/reproducer-gf-ejb-deployment-error

## Impact of Issue
Application deployment failed.

### PR DESCRIPTION
**Pull request by avpinchuk**
This is a bug fix.

This PR should close #24354.

Signed-off-by: Alexander Pinčuk <alexander.v.pinchuk@gmail.com>

### CODE REVIEW

**Comment by dmatej** [comment]
The [build 48 runs](https://ci.eclipse.org/glassfish/view/GlassFish/job/glassfish7-all-tests/) this. This configuration of this job is not yet finished, so it will fail, I am doing small steps forward. It should run the TCK tests outside the "old" package, so partially it already should be capable to verify some changes.

**Comment by avpinchuk** [comment]
In this patch I fix only one thing. Currently, in absence of the no-arg ctor GF takes first ctor with parameters. I change this behavior - we try to find annotated ctor. If none of no-arg and annotated constructors found, we throw `DeploymentException`, because this should newer be happens.

**Comment by dmatej** [comment]
CDI TCK failed for some reason - it may be this PR or it may be my configuration, I will try locally tomorrow.

**Comment by dmatej** [comment]
Locally it passed, so I approve it :-)

**Review by dmatej — APPROVED** [review]

**Pull request merged**
