### PR TITLE
Update command-security-maven-plugin to 1.0.11

### PR DESCRIPTION
**Pull request by arjantijms**
command-security-maven-plugin updated from 1.0.10 to 1.0.11

Signed-off-by: arjantijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Review by hs536 — APPROVED** [review]

**Comment by cpaolini** [comment]
Hi,

1.0.11 is not available via https://repo.maven.apache.org/maven2/org/glassfish/build/command-security-maven-plugin/

I receive this build failure:

[INFO] BUILD FAILURE
[INFO] ---------------------------              ---------------------------------------------
[INFO] Total time:  19.062 s
[INFO] Finished           at: 2020-07-12T20:06:09-07:00
[INFO] ------------------------              ------------------------------------------------
[ERROR] Plugin org.glassfish.build:command-security-maven-plugin:1.0.11 or one of its dependencies could
 resolved: Could not find artifact org.glassfish.build:command-security-maven-plugin:jar:1.0.11 in central (https:
maven.apache.org/maven2)

**Comment by pzygielo** [comment]
@cpaolini - do you use staging profile [as described in README](https://github.com/eclipse-ee4j/glassfish#building)? As this version is there https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/build/command-security-maven-plugin.

I agree - [glassfish-security-plugin](https://github.com/eclipse-ee4j/glassfish-security-plugin/) shall be pushed to central.

**Comment by smillidge** [comment]
@arjantijms can you raise a release record on the GlassFish project and then push to central?

**Comment by hs536** [comment]
I previously ran the jenkins job for the release. Is this not running correctly?
* https://ci.eclipse.org/glassfish/view/All%20Projects/job/all-projects_3_staging-to-release/66/

**Pull request merged**
