### PR TITLE
Add missing jpa 3.2 features

### PR DESCRIPTION
**Pull request by starksm64**
This is related to the #25198 issue for JPA 3.2.

This is as far as I have been able to get. It is currently failing in the `Archivist.postStandardDDsRead` method because the descriptor classloader is null. 

```
[2024-11-08T11:27:50.419766-06:00] [GF 8.0.0-JDK17-M7] [SEVERE] [NCLS-CORE-00026] [jakarta.enterprise.system.core] [tid: _ThreadID=53 _ThreadName=admin-listener(2)] [levelValue: 1000] [[
  Exception during lifecycle processing
java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.loadClass(String)" because the return value of "com.sun.enterprise.deployment.BundleDescriptor.getClassLoader()" is null
	at com.sun.enterprise.deployment.archivist.Archivist.postStandardDDsRead(Archivist.java:367)
	at org.glassfish.web.deployment.archivist.WebArchivist.postStandardDDsRead(WebArchivist.java:179)
	at org.glassfish.web.deployment.archivist.WebArchivist.postStandardDDsRead(WebArchivist.java:72)
	at com.sun.enterprise.deployment.archivist.Archivist.readRestDeploymentDescriptors(Archivist.java:451)
	at com.sun.enterprise.deployment.archivist.Archivist.readDeploymentDescriptors(Archivist.java:426)
	at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:279)
	at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:288)
	at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:247)
	at com.sun.enterprise.deployment.archivist.ApplicationFactory.openArchive(ApplicationFactory.java:131)
	at org.glassfish.javaee.core.deployment.DolProvider.processDOL(DolProvider.java:187)
	at org.glassfish.javaee.core.deployment.DolProvider.load(DolProvider.java:210)
	at org.glassfish.javaee.core.deployment.DolProvider.load(DolProvider.java:80)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.loadDeployer(ApplicationLifecycle.java:942)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainerInfos(ApplicationLifecycle.java:881)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:411)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:257)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:471)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:574)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:570)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:376)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:569)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:600)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:592)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:376)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:591)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1484)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1862)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1738)
	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:223)
	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:203)
	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:243)
	at org.glassfish.admin.rest.resources.TemplateListOfResource.createResource(TemplateListOfResource.java:305)
	at org.glassfish.admin.rest.resources.TemplateListOfResource.post(TemplateListOfResource.java:142)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:263)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:266)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:242)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:704)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:372)
	at org.glassfish.admin.rest.adapter.RestAdapter$2.service(RestAdapter.java:289)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:157)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:429)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:143)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:833)
]]
```

### CODE REVIEW

**Comment by starksm64** [comment]
@arjantijms suggest what changes are needed to this

**Comment by arjantijms** [comment]
Thanks for the initial PR :) I was just starting to look into this, but due to travelling and conferences only took a quick look.

What I guess we could try is:

1. Add the new elements for scope and qualifiers to the config bean, so that the existing parser will add it (as you've been doing)
2. Let the existing code do what it does, and make the entity manager available for `@PersistenceContext` injection
3. In a CDI extension, obtain the entity manager configuration previously created, and add `jakarta.enterprise.inject.spi.Bean<T>` (synthetic bean) instances for the `{EntityManager.class, [Qualifier]}` with scope `[Scope]`, with `[Qualifier]` and `[Scope]` obtained for each configured persistence context.
4. For the `create` method of each `jakarta.enterprise.inject.spi.Bean<T>`, set a lambda that obtains the corresponding entity manager and returns it.

Assumptions here is that the parsing is done and the configuration is made available before CDI extensions are called. We need to make sure that we can obtain the configuration and later the entity manager from the context of the CDI extension.

**Comment by arjantijms** [comment]
p.s. do note that the PR needs to go into the 8.0 branch. Master is for the 7.x (EE 10) series.

**Comment by starksm64** [comment]
Right, I had done the work on that branch in the main repo clone, but forgot to switch in my fork. There are a few CDI extensions, which one is the correct one?

**Comment by starksm64** [comment]
This is what does not seem to work:
> 2. Let the existing code do what it does, and make the entity manager available for `@PersistenceContext` injection

Instead of there being a `@PersistenceContext(unitName = "CTS-EM")` indicating the injection site, there is a custom qualifier annotation and `@Inject`:

```java
@RequestScoped
public class TestBeanEM {
    Logger logger = Logger.getLogger(TestBeanEM.class.getName());

    //@PersistenceContext(unitName = "CTS-EM")
    @CtsEmQualifier
    //@Inject
    private EntityManager em1;
    //@PersistenceContext(unitName = "CTS-EM2")
    @CtsEmQualifier
    @Inject
    private EntityManager em2;
...
```

I'm trying to reuse the existing entitymanager related processing, but I cannot load the custom annotation that is in the war deployment.

**Comment by pzygielo** [comment]
- Replaced with #25209

**Pull request closed without merging**
