### PR TITLE
Fix for 5.1.0-run-with-JDK11 branch

### PR DESCRIPTION
**Pull request by hs536**
( FOR 5.1.0-run-with-JDK11 BRANCH )

Partial changes to update some components and make sure jenkins-ci works with new docker image correctly.

### CODE REVIEW

**Comment by hs536** [comment]
Eclipse Jenkins seems to be busy, so I'll keep it in Draft until the test runs.

**Comment by hs536** [comment]
This merge request is ready to merge.
* Reflected modifications from several other projects.
* Some fail, but testing is now running with JDK 11 on Eclipse Jenkins CI.

**Comment by smillidge** [comment]
Hi @hs536 some of the test are failing do you want me to still approve the merge?

**Comment by hs536** [comment]
@smillidge 
Yes. Some test failures remain, but if this MR is merged, anyone can try starting GF5 with JDK 11 without additional steps.
// the latest orb-gmbal-pfl (4.1.2-RC1) need to obtain from the Eclipse staging repository, not to MavenCentral, though.

**Comment by smillidge** [comment]
Shall I cut a final release of gmbal-pfl 4.1.2?

**Comment by smillidge** [comment]
I've staged a 4.1.2 of GMBAL PFL

**Comment by smillidge** [comment]
@hs536 can you switch to the staged GMBAL PFL 4.1.2 and see if everything is still good?

**Comment by hs536** [comment]
@smillidge 
OK, test results were almost the same as last time.
( Compared to the last time, for some reason one more test item was passed. )

**Comment by lukasj** [comment]
upcoming metro 2.4.5 can help you a bit here. If you don't mind trying out snapshot, see https://github.com/lukasj/glassfish-1/commit/a3dc5c6652d8a9338a0a61f75f1d928e4a9036e4 for what is needed to be updated (it's basically the same as current metro-master but within `javax` namespace) - sorry for the small incompatibility there but it was required to be able to run at least one specific configuration on JPMS.

**Comment by hs536** [comment]
I'll temporarily drop this PR

**Pull request closed without merging**
