### PR TITLE
fix for exported package name

### PR DESCRIPTION
**Pull request by AngryGami**
https://github.com/eclipse-ee4j/glassfish/issues/22712

### CODE REVIEW

**Comment by Cousjava** [comment]
@AngryGami  you need to sign the ECA (https://www.eclipse.org/legal/ECA.php) and sign off your commit (`git commit -s`)

**Review by Cousjava — APPROVED** [review]

**Comment by AngryGami** [comment]
Do I absolutely have to? I hoped that someone with authority could just apply this change to repo and be done with it. Problem is trivial.

**Comment by bshannon** [comment]
> Do I absolutely have to? I hoped that someone with authority could just apply this change to repo and be done with it. Problem is trivial.

Sadly, yes, those are the Eclipse rules.  Otherwise you wait until someone else creates the fix based on your bug report.

**Comment by AngryGami** [comment]
I really tried, but I can't understand what I need to do with all that ECA stuff. I've signed ECA at the url you have provided and then just stuck.. Should I install some certificate somewhere? How to apply this signature to this pull request/commit or should I create new one from scratch?

**Pull request closed without merging**
