### PR TITLE
Integrate Jersey 3.1.0-M3

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: Arjan Tijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Review by hs536 — APPROVED** [review]

**Comment by hs536** [comment]
a little bit concerned about Jersey still depends on JAXB3:  
https://github.com/eclipse-ee4j/jersey/blob/3.1.0-M3/pom.xml#L2196-L2197

**Comment by arjantijms** [comment]
> https://github.com/eclipse-ee4j/jersey/blob/3.1.0-M3/pom.xml#L2196-L2197

Good catch, @jansupol any idea why that is?

**Comment by dmatej** [comment]
Just FYI: https://github.com/eclipse-ee4j/jersey/issues/5006
So if you would be able to work on jackson, we could probably meet on some stable point of compatibility of 4 modules: jersey, grizzly, metro-wsit and jackson ... and finally GlassFish, which is waiting for that here https://github.com/eclipse-ee4j/glassfish/pull/23843 - tests detected incompatibility :-)

**Comment by jansupol** [comment]
[JAX-B version update](https://github.com/eclipse-ee4j/jersey/pull/5008) is merged. For Jackson, we need to have both JAX-B/3 and JAX-B/4 on [classpath](https://github.com/eclipse-ee4j/jersey/blob/3.1/tests/osgi/functional/src/test/java/org/glassfish/jersey/osgi/test/basic/JsonJacksonTest.java#L45). Looks like OSGi is ok with that.

**Pull request merged**
