### PR TITLE
Update Derby to latest for JDK 11

### PR DESCRIPTION
**Pull request by smillidge**
Signed-off-by: Steve Millidge <steve.millidge@payara.fish>

Draft until I work out how to get org.glassfish.external derby version into staging and out to central!

### CODE REVIEW

**Comment by hussainnm** [comment]
Needs to be updated in glassfish-repackaged repo. I created a PR https://github.com/eclipse-ee4j/glassfish-repackaged/pull/16 to update derby.

**Comment by smillidge** [comment]
Thanks for the PR I've approved. It's getting it into staging which is the next problem.

**Comment by hussainnm** [comment]
From the job history of [repackaged](https://ci.eclipse.org/glassfish/job/repackaged/), it does not look like the Jenkins pipeline has worked. Can you try staging it with https://ci.eclipse.org/glassfish/view/all/job/all-projects_1_build-and-stage/

**Comment by arjantijms** [comment]
@smillidge @hussainnm I staged Derby here: https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/external/derby/10.15.2.0/

It took a little bit of fiddling with the script and some coordination with Joel from Sonatype, but it's there now.

**Review by arjantijms — APPROVED** [review]

**Comment by arjantijms** [comment]
As this passes now, and Derby has been published, I'm going to merge this one in.

**Comment by arjantijms** [comment]
p.s. do we want to push Derby out to central now, or wait a little to do that?

**Comment by smillidge** [comment]
May as well it's not really going to change

**Comment by pzygielo** [comment]
> p.s. do we want to push Derby out to central now, or wait a little to do that?

https://github.com/eclipse-ee4j/glassfish-repackaged/issues/19

**Pull request merged**
