### PR TITLE
Merge 6.x to master

### PR DESCRIPTION
**Pull request by dmatej**

### CODE REVIEW

**Comment by dmatej** [comment]
Blocked by this: https://github.com/eclipse-ee4j/metro-wsit/pull/161

**Comment by arjantijms** [comment]
@dmatej
> Blocked by this: https://github.com/eclipse-ee4j/metro-wsit/pull/161

Since that one has now been unblocked (thanks to you and @lukasj), can we now proceed with this PR?

**Comment by dmatej** [comment]
Goood!

**Comment by arjantijms** [comment]
@lukasj I can stage a 4.0.0-M4 too for Metro (WSIT, or WebServices) if needed.

**Comment by arjantijms** [comment]
> My hope is that grizzly (which I've already asked for back in Jan) 

If I'm not mistaken @dmatej is working on that as we speak ;) Not every part of it appeared to be trivial, but process is being made.

> I'd like to keep this pattern.

It's sometimes difficult to keep patterns when you're part of a larger project. If everyone would stick to a monthly pattern, then it would take more than 2 years (27 months), give or take, until we could release GF 7.

**Comment by lukasj** [comment]
Where does the "larger project" have its rough schedule, so those being included there can plan their work as needed? Is the whole work supposed to be "one-man show" or collaborative effort?

**Comment by dmatej** [comment]
> My hope is that grizzly (which I've already asked for back in Jan) will be ready by then

I am working on that today, I was without electricity yesterday.

> Is the whole work supposed to be "one-man show" or collaborative effort?

I would see it as some event-driven automat with multiple actors, where every actor works (or asks for help) on anything he requires for an actual project. Schedules are rather orientation points then.

**Comment by arjantijms** [comment]
> Where does the "larger project" have its rough schedule

The rough schedule is the Jakarta EE 10 release plan (https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee10/JakartaEE10ReleasePlan) and specifically for GlassFish there's the tracking board here:  https://github.com/eclipse-ee4j/glassfish/projects/3

With so many projects it is indeed mostly event driven. We have about 10 contributors for the 7 release  https://github.com/eclipse-ee4j/glassfish/graphs/contributors?from=2021-11-03&to=2022-03-15&type=c  although some are helping by preparing dependencies in their own repos (like Scott for Hibernate Validate) and don't show up directly in that graph.

**Comment by lukasj** [comment]
that project board show no dates as does the release plan. It says nothing about estimated target dates for GF RCs/final builds, it also says nothing about GF weekly(?)/milestone builds. It really does not help to align releases of component CIs with GF release - at least those I'm somehow responsible for and I can help with (~11 top-level projects from > 30repos).

Events as such are fine and should definitely be responded to, yet some time-buffer should be expected.

btw: I did not say you can't do some metro-4.0.0-gf1 (or whatever keeps treating current M3 as the latest) build if you really need it a week ago ;-)

**Comment by dmatej** [comment]
So, current status + dependency tree:

* grizzly 4.0.0-SNAPSHOT, depends on servlet6; I need the 4.0.0-M1 to be able to release with jersey. (https://github.com/eclipse-ee4j/grizzly/pull/2156)
* metro-wsit 4.0.0-SNAPSHOT, depends on authentication-api 3.0.0-RC2 (https://github.com/eclipse-ee4j/metro-wsit/pull/162 and I didn't test latest changes in wsit from @lukasj yet: https://github.com/eclipse-ee4j/metro-wsit/pulls?q=is%3Apr+is%3Aclosed)
* jersey 3.1.0-SNAPSHOT, depends on grizzly 4.0.0-SNAPSHOT and servlet6 (https://github.com/eclipse-ee4j/jersey/pull/5009)
* this branch depends on them all, passed locally cdi_all and webservice_all

**Review by arjantijms — APPROVED** [review]

**Pull request merged**
