### PR TITLE
Update test dependencies (junit/testng/easymock)

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: arjantijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Review by smillidge — CHANGES_REQUESTED** [review]
Would it be easier to pull the version number into a parent pom property or parent pom dependency rather than update 75 files :-)

**Comment by arjantijms** [comment]
> Would it be easier to pull the version number into a parent pom property or parent pom dependency rather than update 75 files :-)

Normally, sure, but many (all?) of those files don't have a parent to begin with.

**Comment by smillidge** [comment]
Could we add one?

**Comment by arjantijms** [comment]
> Could we add one?

I guess we could, but may be some work ;)

**Comment by dmatej** [comment]
You can add junit.version to aggregator and add junit to dependeny management. And also set default scope to test scope. Then you don't need to declare version and scope in each child.

**Comment by smillidge** [comment]
Your call. I will approve

**Review by smillidge — APPROVED** [review]

**Comment by arjantijms** [comment]
Okay, I'll merge this now as-is, as it updated just the previous version. For a new PR we can then introduce a parent and move the version there. Thanks!

**Pull request merged**
