### PR TITLE
Integrate Angus Mail 1.1.0

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: Arjan Tijms <arjan.tijms@omnifish.ee>

### CODE REVIEW

**Comment by pzygielo** [comment]
Not sure what's the status, but 2yrs ago https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/485#note_413570

> The requirement is the email that you have on file with your Eclipse Foundation Account is the email address that you need to use as your author and signed-off-by credentials.
So the two workarounds that you have are to either change your email address on your EF account, or rewrite these commits to use your current email address.

(With the change, that no sign-off is required now - the author has to match I guess.)

Persona project is still open: https://gitlab.eclipse.org/groups/eclipsefdn/-/epics/16

**Review by pzygielo — APPROVED** [review]

**Comment by pzygielo** [comment]
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1316#note_827021:

> unfortunately we cannot provide this functionality ( i.e. associate an EF account with two email addresses / enable an alias) in the near future.

**Comment by arjantijms** [comment]
@pzygielo I changed my email address a while back and it's the same as the commit. When I manually validate the email address it validates correctly.

**Comment by arjantijms** [comment]
And now it works. Oh well...

**Comment by pzygielo** [comment]
I've seen that this e-mail sync takes noticeable amount of time somewhere else too.

**Pull request merged**
