### PR TITLE
Display debug port

### LINKED ISSUE #24956: `start-domain --debug=true` does not display port number
## Environment Details
* GlassFish Version (and build number): 7.0.14
* JDK version: openjdk version "21.0.3" 2024-04-16 LTS
* OS: GNU/Linux
* Database: n/a

----------

## Problem Description
Currently:
```
$ ./glassfish7/glassfish/bin/asadmin start-domain --debug=true
Waiting for domain1 to start .........
Waiting finished after 8,630 ms.
Successfully started the domain : domain1
domain  Location: .../glassfish7/glassfish/domains/domain1
Log File: .../glassfish7/glassfish/domains/domain1/logs/server.log
Admin Port: 4,848
Command start-domain executed successfully.
```
and no port used for debugging is displayed.

Expected - per man page:
```
$ ./glassfish7/glassfish/bin/asadmin start-domain --help
...
       --debug, -d
...
           true
               The instance is started with JPDA debugging enabled and the
               port number for JPDA debugging is displayed.
```
to have port displayed.

### PR DESCRIPTION
**Pull request by pzygielo**
Test:
1. get https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/job/PR-24955/1/artifact/bundles/glassfish.zip and unpack
2. execute and inspect output:
```
$ ./glassfish7/glassfish/bin/asadmin start-domain --debug=true
Waiting for domain1 to start ...........
Waiting finished after 10,150 ms.
Successfully started the domain : domain1
domain  Location: .../glassfish7/glassfish/domains/domain1
Log File: .../glassfish7/glassfish/domains/domain1/logs/server.log
Admin Port: 4,848
Debugging is enabled.  The debugging port is: 9,009
Command start-domain executed successfully.
```

### CODE REVIEW

**Review by arjantijms — APPROVED** [review]

**Comment by pzygielo** [comment]
> Tiny comment, but it's already in the other values too; "9,009" vs "9009"

I don't understand that comment.

Logged message formatting step is locale-dependent, and one can get dot instead of comma as grouping character easily (observe for _Waiting finished_ or _Admin port_ as well):
```
$ LC_ALL=nl_NL.utf8 ./glassfish7/glassfish/bin/asadmin start-domain --debug=true
Waiting for domain1 to start .......
Waiting finished after 6.666 ms.
Successfully started the domain : domain1
domain  Location: .../glassfish7/glassfish/domains/domain1
Log File: .../glassfish7/glassfish/domains/domain1/logs/server.log
Admin Port: 4.848
Debugging is enabled.  The debugging port is: 9.009
Command start-domain executed successfully.
```
or
```
$ LC_ALL=lv_LV.utf8 ./glassfish7/glassfish/bin/asadmin start-domain --debug=true
Waiting for domain1 to start ......
Waiting finished after 5 974 ms.
Successfully started the domain : domain1
domain  Location: .../glassfish7/glassfish/domains/domain1
Log File: .../glassfish7/glassfish/domains/domain1/logs/server.log
Admin Port: 4 848
Debugging is enabled.  The debugging port is: 9 009
Command start-domain executed successfully.
```
or
```
$ LC_ALL=sd_IN ./glassfish7/glassfish/bin/asadmin start-domain --debug=true
Waiting for domain1 to start .......
Waiting finished after ٦٬٥٤٦ ms.
Successfully started the domain : domain1
domain  Location: .../glassfish7/glassfish/domains/domain1
Log File: .../glassfish7/glassfish/domains/domain1/logs/server.log
Admin Port: ٤٬٨٤٨
Debugging is enabled.  The debugging port is: ٩٬٠٠٩
Command start-domain executed successfully.
```

**Review by dmatej — APPROVED** [review]
Wow, good catch, however we should make it yet more robust (address is not just a port) ... on the other hand I don't expect anyone would debug on production, so it is ok.

**Comment by arjantijms** [comment]
> > Tiny comment, but it's already in the other values too; "9,009" vs "9009"
> 
> I don't understand that comment.
> 
> Logged message formatting step is locale-dependent, and one can get dot instead of comma as grouping character easily (observe for _Waiting finished_ or _Admin port_ as well):
> 
> ```
> $ LC_ALL=nl_NL.utf8 ./glassfish7/glassfish/bin/asadmin start-domain --debug=true
> Waiting for domain1 to start .......
> Waiting finished after 6.666 ms.
> Successfully started the domain : domain1
> domain  Location: .../glassfish7/glassfish/domains/domain1
> Log File: .../glassfish7/glassfish/domains/domain1/logs/server.log
> Admin Port: 4.848
> Debugging is enabled.  The debugging port is: 9.009
> Command start-domain executed successfully.
> ```
> 
> or
> 
> ```
> $ LC_ALL=lv_LV.utf8 ./glassfish7/glassfish/bin/asadmin start-domain --debug=true
> Waiting for domain1 to start ......
> Waiting finished after 5 974 ms.
> Successfully started the domain : domain1
> domain  Location: .../glassfish7/glassfish/domains/domain1
> Log File: .../glassfish7/glassfish/domains/domain1/logs/server.log
> Admin Port: 4 848
> Debugging is enabled.  The debugging port is: 9 009
> Command start-domain executed successfully.
> ```
> 
> or
> 
> ```
> $ LC_ALL=sd_IN ./glassfish7/glassfish/bin/asadmin start-domain --debug=true
> Waiting for domain1 to start .......
> Waiting finished after ٦٬٥٤٦ ms.
> Successfully started the domain : domain1
> domain  Location: .../glassfish7/glassfish/domains/domain1
> Log File: .../glassfish7/glassfish/domains/domain1/logs/server.log
> Admin Port: ٤٬٨٤٨
> Debugging is enabled.  The debugging port is: ٩٬٠٠٩
> Command start-domain executed successfully.
> ```

I think it should perhaps not be formatted as a number at all, just as a string. So it should be just "9009", imho. Of course it doesn't matter too much.

**Comment by pzygielo** [comment]
> I think it should perhaps not be formatted as a number at all, just as a string. So it should be just "9009", imho.

- Going from (unformatted) `String` to `int` (to be handled by Formatter): https://github.com/eclipse-ee4j/glassfish/pull/24200.

**Comment by pzygielo** [comment]
> we should make it yet more robust (address is not just a port) 

Can you elaborate? The term `address` is only used as agent's parameter (not under GF control), the help page is only about port and the message is only about port. Not clear what change you'd like to see.

**Comment by dmatej** [comment]
> > we should make it yet more robust (address is not just a port)
> 
> Can you elaborate? The term `address` is only used as agent's parameter (not under GF control), the help page is only about port and the message is only about port. Not clear what change you'd like to see.

Just forget it, it was just a short idea related to the address - user can enable the debug port just on specific IP, generally, but we don't need it and it would make user's life harder than just using the `--debug` parameter.

**Comment by pzygielo** [comment]
> user can enable the debug port just on specific IP

True. I only considered the case (`*:`) present in template `domain.xml`, indeed.
This however, fortunately, does not block the debug itself. It is just that message is not displayed then (for the NFEx).

**Pull request merged**
