### PR TITLE
Integration of Eclipse Grizzly 2.4.4 and Eclipse Grizzly NPN 1.9

### PR DESCRIPTION
**Pull request by anajosep**
Signed-off-by: anajosep <anand.francis.joseph.augustin@oracle.com>

### CODE REVIEW

**Comment by romain-grecourt** [comment]
@anajosep please refresh your PR with the latest EE4J_8 branch, PR #22644 has been reverted to fix the test failures.

**Comment by anajosep** [comment]
@romain-grecourt . I have merged the latest from EE4J_8. Can you please review it.
Thanks 
Anand.

**Comment by anajosep** [comment]
@romain-grecourt  The tests for this merge might require JDK8u191+ as the Grizzly NPN version 1.9 requires that JDK version.

**Review by arjantijms — APPROVED** [review]

**Comment by arjantijms** [comment]
LGTM

**Comment by romain-grecourt** [comment]
@anajosep the pipeline uses jdk8u181, should we expect test failures ? Are there other changes in this JDK version that we should be aware of (other than the stuff that grizzly npn depends on) ?

**Comment by anajosep** [comment]
@romain-grecourt I don't expect test failures due to JDK8u191 upgrade or Grizzly NPN 1.9 integration. For Oracle GF 5.0.1, we integrated Grizzly NPN 1.8.1 (having the same code base as 1.9) and we did not find any issues in the test runs. To be on a safer side, I would try to run a subset of CTS tests with JDK8u191 and the bundle built from this PR and confirm if its safe to merge this PR and also to upgrade the pipeline jobs to JDK8u191.

**Comment by anajosep** [comment]
The CTS subset runs were clean in my local run. I see that the PR is also merged. Thanks @romain-grecourt

**Comment by pzygielo** [comment]
With npn updated to 1.9, I suppose #22601 could be closed, right?

**Pull request merged**
