### PR TITLE
Embed EE4J parent pom until 1.0.8 is released.

### PR DESCRIPTION
**Pull request by arjantijms**
This is needed to be able to deploy using JDK 17.

Signed-off-by: Arjan Tijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Comment by pzygielo** [comment]
Will this result in release of ee4j/project (parent) under its original coordinates with new (-M1) version from [this] glassfish repository?

**Comment by pzygielo** [comment]
I think much safer would be to manage required plugin(s) (I guess nexus-staging only) instead.

**Comment by dmatej** [comment]
This is a wrong idea - as @pzygielo  wrote, you will have to release them parent too as M1, or it cannot pass the Maven Central rules again.

**Comment by arjantijms** [comment]
Essentially these are just some (increasingly) desperate attempts to get GF to be deployed to staging.

**Comment by arjantijms** [comment]
But indeed, managing the nexus plug-in instead is probably much safer.

**Comment by pzygielo** [comment]
I think, JDK17 can be used to build GF, and then JDK11 to stage with old sonatype plugin.

----

This is all unnecessary work due to unreleased change
- https://github.com/eclipse-ee4j/ee4j/pull/79#issuecomment-1287658387
- https://github.com/eclipse-ee4j/ee4j/issues/83

**Pull request merged**
