### PR TITLE
Upgrade to Jakarta Transaction API 1.3.1

### PR DESCRIPTION
**Pull request by tomjenkinson**
Signed-off-by: Tom Jenkinson <tom.jenkinson@redhat.com>

### CODE REVIEW

**Review by smillidge — APPROVED** [review]

**Comment by smillidge** [comment]
Glassfish doesn't build now 
` Could not resolve dependencies for project org.glassfish.main.deployment:dol:glassfish-jar:5.0.1-SNAPSHOT: Could not find artifact jakarta.transaction:jakarta.transaction-api:jar:1.3.1 in central (https://repo.maven.apache.org/maven2)`

**Comment by bshannon** [comment]
You're definitely going to need to use the staging profile to build.
Can we just activate that profile by default during development?
(Of course, no one will remember to deactivate it for the final release.)

**Comment by romain-grecourt** [comment]
Yes, IMO we should activate it during dev cycles *only*.

Not having it enabled by default would mean that the workspace is not build-able with just a "mvn install :(

The other way would be to use -Pstaging in the CI jobs.
This would actually be worse: it could potentially allow pushing GlassFish release artifacts to Maven Central with unresolvable dependencies that are still in staging and not released to Maven Central.

Activating/Deactivating the staging repository in the pom should be a part of the release process.
Before a release we deactivate the repository to enforce that all dependencies are available strictly from Maven Central.

That will require coordinating with all projects to ensure they release before we deactivate the staging repository.

**Comment by smillidge** [comment]
Perhaps just update the readme? I can raise a PR.

**Comment by romain-grecourt** [comment]
OK, let's update the readme for now.

**Pull request merged**
