### PR TITLE
Enable GF Embedded test suite - part 2 (also fixes a NullPointerException in VirtualServer.java) 

### PR DESCRIPTION
**Pull request by OndroMih**
Fixes a NullPointerException in `VirtualServer.java` which caused some tests to fail. This was because`DeploymentContextImpl initialContext` was created without an archive handler, and this cause a null pointer exception when `archiveHandler.getDefaultApplicationName(archive, initialContext)` was called later in the same `addContext` method.

Enables the `web` module in the `embedded` tests:

* introduce `buildDir` system property set to the `target` directory, which is used in some of the tests
* add the `utils` module to the build which is required to build the other modules
* removed the binary test WAR, it's now generated from sources during the build, before the tests are executed

### CODE REVIEW

**Review by dmatej — APPROVED** [review]
Next level: JUnit 5 :-)

**Comment by OndroMih** [comment]
> Next level: JUnit 5 :-)

Oh, yes, I forgot to upgrade these tests to JUnit5. I’ll do it later in another PR.

**Review by avpinchuk — APPROVED** [review]
Great!

**Comment by OndroMih** [comment]
> Next level: JUnit 5 :-)

OK, so I did the lifting now and also migrated the tests to JUnit 5 in this PR :)

**Review by arjantijms — APPROVED** [review]

**Pull request merged**
