### PR TITLE
Integrate Mojarra 4.0.3

### PR DESCRIPTION
**Pull request by arjantijms**
Changes: https://github.com/eclipse-ee4j/mojarra/releases/tag/4.0.3-RELEASE

### CODE REVIEW

**Comment by pzygielo** [comment]
BTW - could the release at https://github.com/eclipse-ee4j/mojarra/releases/tag/4.0.3-RELEASE be renamed from 
image
to 4.0.3?

**Review by pzygielo — APPROVED** [review]

**Comment by scottmarlow** [comment]
@arjantijms are you running the TCK via https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-faces-tck-glassfish?  The job shows green even though there are failures.

https://gist.github.com/scottmarlow/4c7c121470398cafcbf697195ed119fe contains some of the output from the last run for which there are some failures including `com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperAddGetMessagesTest` which we are hitting with WildFly as well via https://issues.redhat.com/browse/WFLY-18397.

**Comment by scottmarlow** [comment]
If ${FAILED_COUNT} or ${ERROR_COUNT} are not zero, should https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-faces-tck-glassfish exit with an error so that Jenkins shows red instead of green for the test run?

**Comment by arjantijms** [comment]
Indeed, you are right 😵

https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-faces-tck-glassfish/137/artifact/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/facesreport/faces/text/summary.txt

There are clearly errors there, but the TCK report `success`. We have two issues to fix here:

1. The error reporting of the TCK
2. The actual failure caused by Mojarra 4.0.3

**Comment by scottmarlow** [comment]
I started https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-faces-tck-glassfish/138/ with a change to force Jenkins to exit 1 in case of error/failures.

**Pull request merged**
