### PR TITLE
Fixes data race during Admin Console initialization

### PR DESCRIPTION
**Pull request by avpinchuk**
Synchronize access to fields accessed from many threads.

### CODE REVIEW

**Comment by hs536** [comment]
What kind of problems can the current code cause?
( Is there a possibility of conflict in the loading process of the RestModule...?

**Review by dmatej — APPROVED** [review]
I believe I can see it. The init method can be called by different thread than service method, but they use the same attribute, which can sometimes lead to a situation when the service method would use an old value.

**Comment by avpinchuk** [comment]
> The init method can be called by different thread than service method, but they use the same attribute, which can sometimes lead to a situation when the service method would use an old value.

Yes, this is also one of the possible problems

**Review by hs536 — APPROVED** [review]

**Comment by avpinchuk** [comment]
I will make several builds of the master branch at different time. I hope this fix help stabilize `application-tests`.

**Pull request merged**
