### PR TITLE
Integrate Weld 5.0.0.SP1

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: Arjan Tijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Review by dmatej — CHANGES_REQUESTED** [review]
Communicating with the Weld team, seems we detected some error ...

**Comment by dmatej** [comment]
The error was fixed, now we have two options:
- wait for Weld 5.0.1
- build it and use snapshot.

**Comment by arjantijms** [comment]
> build it and use snapshot.

Let's try the snapshot first then. It will be a quick replace when 5.0.1 is released.

**Comment by manovotn** [comment]
The release is in Central already - it is 5.0.0.SP1 (just the core artifact, API stays the same).
If you find any more issues, let me know. But hopefully, this should do the trick :-)

**Review by dmatej — APPROVED** [review]

**Review by scottmarlow — APPROVED** [review]

**Pull request merged**
