### PR TITLE
Finalise Grizzly 3.0.0 Dependency

### PR DESCRIPTION
**Pull request by MattGill98**
Needs finalising before GF 6 release.

Waiting on staging artifact: https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/grizzly/grizzly-core/3.0.0

### CODE REVIEW

**Comment by pzygielo** [comment]
Just checking - as https://ci.eclipse.org/grizzly/job/1_grizzly-build-and-stage/30/ was ran to build and stage version 2.0.0, and 2.0.0 is there https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/grizzly/grizzly-core/.

**Comment by MattGill98** [comment]
NPN dependency was 2.0, but was released as 2.0.0 (intentionally). I've updated the PR to fix that

**Comment by pzygielo** [comment]
I see grizzly was rebuilt in https://ci.eclipse.org/grizzly/job/1_grizzly-build-and-stage/32 in ver. 3.0.0.

**Comment by arjantijms** [comment]
> I see grizzly was rebuilt in

Yes, I rebuilt it. My mistake, I mixed-up Grizzly-NPN and Grizzly main version numbers. It's fixed now.

**Review by arjantijms — APPROVED** [review]

**Pull request merged**
