### PR TITLE
Comment out MVC temporarily to have CDI TCK passing again

### LINKED ISSUE #23961: CDI Test failures with GlassFish 7
Running the CDI TCK (using the runner in GlassFish) there are 11 failures as of today:

[ERROR] Failures: 

- [x]   EjbInjectionTest>Arquillian.run:138->testPassivationOfEjbs:70 » EJB java.rmi.RemoteException: CORBA BAD_OPERATION 0 No; nested exception is: 
	org.omg.CORBA.BAD_OPERATION: The delegate has not been set!  vmcid: 0x0  minor code: 0  completed: No
- [x]    AmbiguousInjectionIntoNonContextualComponentTest>Arquillian.arquillianBeforeClass:99 » Runtime Expected exception of type jakarta.enterprise.inject.spi.DeploymentException during deployment of _DEFAULT_, but no exception was thrown.
- [x]   UnsatisfiedInjectionIntoNonContextualComponentTest>Arquillian.arquillianBeforeClass:99 » Runtime Expected exception of type jakarta.enterprise.inject.spi.DeploymentException during deployment of _DEFAULT_, but no exception was thrown.
- [x]    InjectionPointTest>Arquillian.arquillianBeforeClass:99 » Runtime Expected exception of type jakarta.enterprise.inject.spi.DefinitionException during deployment of _DEFAULT_, but no exception was thrown.
- [x]    CDIProviderInitTest>Arquillian.run:138->testAccessingBeanManager:103 expected [0] but found [1]
- [x]    CDIProviderRuntimeTest>Arquillian.run:138->testGetBeanManager:76 expected [1] but found [0]
- [x]    CDIProviderRuntimeTest>Arquillian.run:138->testLookup:90 » UnsatisfiedResolution WELD-001334: Unsatisfied dependencies for type Bravo with qualifiers  

Fixed by Weld update:

- [x]   ContainerLifeCycleEventRuntimeInvocationTest>Arquillian.run:138->testAfterBeanDiscoveryEventFails:224 » NullPointer
- [x]   ContainerLifeCycleEventRuntimeInvocationTest>Arquillian.run:138->testAfterBeanDiscoveryEventFails:224 » NullPointer

See https://github.com/jakartaee/cdi/issues/624#issuecomment-1149357201

Fixed by CDI TCK update:

- [x]   PersistenceContextInjectionTest>Arquillian.run:138->testBeanTypesAndBindingTypesOfPersistenceContext:105
- [x]   PersistenceContextInjectionTest>Arquillian.run:138->testBeanTypesOfPersistenceUnit:116

See https://github.com/jakartaee/cdi-tck/issues/380

```
[ERROR] Tests run: 1837, Failures: 11, Errors: 0, Skipped: 6
```

Tests can be run from `[glassfish]/appserver/tests/tck/cdi` using:

`mvn clean install`

Individual tests can be run via

`mvn clean install -Dit.test=ExcludeFiltersTest#testExcludeSystemPropertyActivator`

Tests can be debugged via:

`mvn clean install -Dit.test=ExcludeFiltersTest#testExcludeSystemPropertyActivator -Dglassfish.suspend`

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: Arjan Tijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Review by dmatej — CHANGES_REQUESTED** [review]
No, not again! :D

**Comment by dmatej** [comment]
So ... here we go to investigation ... **I will edit this yet with more tests ...**
| 210f6f298a7cbaaf85e | 1831 | 0 | OK | PR with last MVC integration | 
| 3cde7383658d6b307 | 1831 | 0 | OK | After merge with last MVC integration | 
| a24af3b55107c70eec | 1831 | 0 | OK | Merge pull request #24016 from arjantijms/tck_concurrency_sigtest |

**Comment by dmatej** [comment]
`mvn clean install -Pfastest -Djakarta.mvc-api.version=2.1.0.M1 -T4C && mvn clean install -Pstaging,tck -pl :glassfish-external-tck-cdi -Dit.test=ProcessBeanAttributesNotFiredForBuiltinBean`

vs. 

`mvn clean install -Pfastest -Djakarta.mvc-api.version=2.0.1 -T4C && mvn clean install -Pstaging,tck -pl :glassfish-external-tck-cdi -Dit.test=ProcessBeanAttributesNotFiredForBuiltinBean`

+ compare server.log

**Comment by dmatej** [comment]
Hmmm, 2.1.0.M1 simply disables Krazo:
```
[2022-06-26T22:57:40.333862+02:00] [glassfish 7.0] [SEVERE] [] [jakarta.enterprise.web.core] [tid: _ThreadID=66 _ThreadName=admin-listener(3)] [timeMillis: 1656277060333] [levelValue: 1000] [[
  java.util.ServiceConfigurationError: jakarta.servlet.ServletContainerInitializer: Provider org.eclipse.krazo.servlet.KrazoContainerInitializer not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at org.apache.catalina.core.StandardContext.callServletContainerInitializers(StandardContext.java:5289)
	at com.sun.enterprise.web.WebModule.callServletContainerInitializers(WebModule.java:627)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5227)
	at com.sun.enterprise.web.WebModule.start(WebModule.java:549)
```

**Comment by dmatej** [comment]
This PR is not acceptable, maybe passes TCK, but still ends with the stacktrace in the server.log. Maybe we can exclude krazo too then ... but ... why the hell is 2.0.1 is breaking CDI TCK tests???!
image

**Comment by dmatej** [comment]
This is the difference in the server.log:
left fails the TCK, right passed.
image

**Comment by arjantijms** [comment]
> Maybe we can exclude krazo too then 

It should already have been excluded. Hmmm.

**Comment by dmatej** [comment]
> > Maybe we can exclude krazo too then
> 
> It should already have been excluded. Hmmm.

Aha, sorry, I excluded just mvc-api, you're right.

**Review by dmatej — APPROVED** [review]
I'm approving that, seems there is some issue with empty beans.xml and perhaps we can fix that tomorrow ... today ... no steps back .. except for few days :)

**Pull request merged**
