### PR TITLE
Install git

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Comment by alwin-joseph** [comment]
Just to understand, is git-core required for any specific purpose when run in the CI ? 

I presume the changes in this file would require docker build & push to the right docker hub repo and use the same image at https://github.com/eclipse-ee4j/glassfish/blob/c9119bfc20de889e032905510e54ff092a91545e/Jenkinsfile#L150.

@RohitKumarJain Can you confirm this and provide the details.

**Comment by pzygielo** [comment]
> Just to understand, is git-core required for any specific purpose when run in the CI ?

Yes.

> I presume the changes in this file would require docker build & push to the right docker hub repo

Yes, that would be necessary.

> and use the same image at
> https://github.com/eclipse-ee4j/glassfish/blob/c9119bfc20de889e032905510e54ff092a91545e/Jenkinsfile#L150

I don't know. git does not seem to be needed here. But for synchronization sake it could be updated there as well. Assuming the tag change.

**Comment by RohitKumarJain** [comment]
> Just to understand, is git-core required for any specific purpose when run in the CI ?
> 
> I presume the changes in this file would require docker build & push to the right docker hub repo(by someone who has the rights) and use the same image at
> 
> https://github.com/eclipse-ee4j/glassfish/blob/c9119bfc20de889e032905510e54ff092a91545e/Jenkinsfile#L150
> 
> .
> @RohitKumarJain Can you confirm this and provide the details.
> 
> cc @gurunrao

Yes, in order to take these changes into effect, we need to build & push to the appropriate docker hub repo.

**Comment by alwin-joseph** [comment]
> 
> > I presume the changes in this file would require docker build & push to the right docker hub repo
> 
> Yes, that would be necessary.

Are you planning to do it yourself or do you need help from someone to do that(I think not everyone can push to the docker hub repo https://hub.docker.com/r/ee4jglassfish/ci).

> 
> > and use the same image at
> > https://github.com/eclipse-ee4j/glassfish/blob/c9119bfc20de889e032905510e54ff092a91545e/Jenkinsfile#L150
> 
> I don't know. git does not seem to be needed here.

From what I understand this Dockerfile was used to build the image ee4jglassfish/ci:tini-jdk-8.181 which seems to be the only image:tag  pulled from the Jenkinsfile. 
If you are creating new image:tag with this change, are you planning to pull the same from some other place? The Jenkinsfile is the only place where the image is pulled to run from the CI, right?

> But for synchronization sake it could be updated there as well. Assuming the tag change.

**Comment by pzygielo** [comment]
> > > I presume the changes in this file would require docker build & push to the right docker hub repo
> > Yes, that would be necessary.
> 
> Are you planning to do it yourself or do you need help from someone to do that(I think not everyone can push to the docker hub repo https://hub.docker.com/r/ee4jglassfish/ci).

I have no privilege to do this.

> > > and use the same image at
> > > https://github.com/eclipse-ee4j/glassfish/blob/c9119bfc20de889e032905510e54ff092a91545e/Jenkinsfile#L150
> > I don't know. git does not seem to be needed here.
> 
> From what I understand this Dockerfile was used to build the image ee4jglassfish/ci:tini-jdk-8.181 which seems to be the only image:tag pulled from the Jenkinsfile.
> If you are creating new image:tag with this change, are you planning to pull the same from some other place?
> The Jenkinsfile is the only place where the image is pulled to run from the CI, right?

It's is already used in [glassfish-build-maven-plugin](https://github.com/eclipse-ee4j/glassfish-build-maven-plugin) too.
Missing `git` causes (I suppose as I can't prove it<sup>*</sup>) [glassfishbuild-maven-plugin:master](https://ci.eclipse.org/glassfish/job/glassfishbuild-maven-plugin/job/master/) to fail there, as it is needed by `glassfish-copyright-maven-plugin`:
```
14:36:12  [ERROR] Failed to execute goal org.glassfish.copyright:glassfish-copyright-maven-plugin:2.3:copyright (default) on project glassfishbuild-maven-plugin: IOException while checking copyrights: Cannot run program "git": error=2, No such file or directory -> [Help 1]
```

----- 
<sup>*</sup> I tried to verify my guess with https://github.com/eclipse-ee4j/glassfish-build-maven-plugin/pull/17. Unfortunately - due to `‘Jenkinsfile’ has been modified in an untrusted revision` I'm not able to complete that there.

**Comment by pzygielo** [comment]
Converted to draft with the hope that https://github.com/eclipse-ee4j/glassfish-build-maven-plugin/pull/19 could help in plugin project.

**Comment by hs536** [comment]
I can push to the `ee4jglassfish/ci`, so I think I can help.
We have several options:
* Update tini-jdk -8.181 wit git (according to this PR)
* Create a new tini tag with git
* Use non-tini tags for projects that require git

**Comment by pzygielo** [comment]
As eclipse-ee4j/glassfish-build-maven-plugin#20 works for plugin project, I no longer think this change is needed.
Thank you for your time.

**Pull request closed without merging**
