### PR TITLE
Resolve `build.id` with git.* properties

### LINKED ISSUE #23489: GlassFish Console - About info incorrect version qualifier
## Environment Details
* GlassFish Version (and build number): 6.2.0
* JDK version: Oracle JDK "11.0.11" 2021-04-20 LTS
* OS: Linux Debian 10
* Database: MySQL 5.7
* WebBrowser: Firefox 89.0

----------

## Problem Description
About window in console doesn't display version qualifier correctly.
Server was downloaded from https://repo1.maven.org/maven2/org/glassfish/main/distributions/glassfish/6.2.0/glassfish-6.2.0.zip

## Steps to reproduce
- Start GlassFish
- Open Console (e.g. http://localhost:4848) in the web browser
- Click to "About..." button in top of the page
- New version info window is displayed
- It prints instead of complete version with qualifier following `Eclipse GlassFish 6.2.0 (build ${git.branch}-b${git.closest.tag.commit.count}-g${git.commit.id.abbrev} ${git.build.time})`
_It seems, that substitution variables are not correctly loaded._

## Impact of Issue
There is minimal impact to me. I want just point You to this GUI error.

### PR DESCRIPTION
**Pull request by pzygielo**
Before
```
$ ./glassfish6/glassfish/bin/asadmin version
Version string could not be obtained from Server [localhost:4848].
(Turn debugging on e.g. by setting AS_DEBUG=true in your environment, to see the details.)
Using locally retrieved version string from version class.
Version = Eclipse GlassFish  6.2.0  (build ${git.branch}-b${git.closest.tag.commit.count}-g${git.commit.id.abbrev} ${git.build.time})
Command version executed successfully.
```
After
```
 ./glassfish6/glassfish/bin/asadmin version
Version string could not be obtained from Server [localhost:4848].
(Turn debugging on e.g. by setting AS_DEBUG=true in your environment, to see the details.)
Using locally retrieved version string from version class.
Version = Eclipse GlassFish  6.2.1  (build revid-b463-gd891f35 2021-07-11T22:14:56+0200)
Command version executed successfully.
```
and for web console: 
revid-console

Fixes #23489.

### CODE REVIEW

**Comment by dmatej** [comment]
FYI, maybe we should upgrade to 5.0.0 (perhaps in another PR)
https://github.com/git-commit-id/git-commit-id-maven-plugin/releases

**Comment by pzygielo** [comment]
Checked with [zip produced on Jenkins](https://ci.eclipse.org/glassfish/view/GlassFish/job/glassfish_build-and-test-using-jenkinsfile/view/change-requests/job/PR-23519/lastSuccessfulBuild/artifact/bundles/glassfish.zip):
```
$ ./glassfish6/glassfish/bin/asadmin version
Version string could not be obtained from Server [localhost:4848].
(Turn debugging on e.g. by setting AS_DEBUG=true in your environment, to see the details.)
Using locally retrieved version string from version class.
Version = Eclipse GlassFish  6.2.1  (build ${git.branch}-b${git.closest.tag.commit.count}-g${git.commit.id.abbrev} ${git.build.time})
Command version executed successfully.
```
and it **doesn't** work there.

**Comment by pzygielo** [comment]
Checked with [zip produced on Jenkins](https://ci.eclipse.org/glassfish/view/GlassFish/job/glassfish_build-and-test-using-jenkinsfile/job/PR-23519/6/artifact/bundles/glassfish.zip):
```
Version string could not be obtained from Server [localhost:4848].
(Turn debugging on e.g. by setting AS_DEBUG=true in your environment, to see the details.)
Using locally retrieved version string from version class.
Version = Eclipse GlassFish  6.2.1  (build PR-23519-b-g6eead71 2021-07-11T22:13:20+0000)
Command version executed successfully.
```
Seems to work now.

**Comment by dmatej** [comment]
It still doesn't work for partial builds. Probably the invocation should move to the place where is the result used, because ie this doesn't work:
`mvn clean install -Pstaging -Pfastest -pl :glassfish-common,org.glassfish.main.distributions:glassfish`
It results in
`build_id=${git.branch}-b${git.closest.tag.commit.count}-g${git.commit.id.abbrev} ${git.build.time}`

The build_id is used also for these two properties, which are not used at all now and could be deleted. Then we can simply move the git commit id plugin usage to the glassfish-common and it is reliable in all ways of usage.

```
        <javaee.version_qualifier>-b${build.id}</javaee.version_qualifier>
        <javaee.version>${javaee.major_version}.${minor_version}${javaee.version_qualifier}</javaee.version>

```

**Comment by pzygielo** [comment]
> mvn clean install -Pstaging -Pfastest -pl :glassfish-common,org.glassfish.main.distributions:glassfish

So you are using here nucleus/parent - already installed in your local repository. Include nucleus-parent project above and please re-check.

**Comment by dmatej** [comment]
That will not resolve the issue, because installed pom is same as the pom from the workspace -> those properties would not be resolved. I would have to add it to the reactor.
I'm creating PR to your PR, wait few minutes ...

**Comment by pzygielo** [comment]
> That will not resolve the issue, because installed pom is same as the pom from the workspace -> those properties would not be resolved. I would have to add it to the reactor.

That's what I meant:
>> Include nucleus-parent project above and please re-check.

**Comment by pzygielo** [comment]
```
$ mvn clean install -Pstaging -Pfastest -pl nucleus/parent,:glassfish-common,org.glassfish.main.distributions:glassfish help:evaluate -Dexpression=build.id -DskipTests
...
[INFO] --- maven-help-plugin:3.2.0:evaluate (default-cli) @ nucleus-parent ---
[INFO] No artifact parameter specified, using 'org.glassfish.main:nucleus-parent:pom:6.2.1-SNAPSHOT' as project.
[INFO] 
6eead711ed84a66b4a874c346be984c8df120fbf-b465-g6eead71 2021-07-12T10:38:19+0200
```

**Comment by pzygielo** [comment]
If one has to know that `:glassfish-common` shall be included in partial build - `nucleus-parent` could be considered of the same class.

**Comment by pzygielo** [comment]
> I'm creating PR to your PR, wait few minutes ...

You can add commits directly to my branch for this PR. _Allow edits by maintainers_ is checked. I won't mind.

I'm all for the idea to move the execution of this plugin to the place it is really needed in.

**Comment by dmatej** [comment]
The PR is here: https://github.com/pzygielo/glassfish/pull/3

**Comment by pzygielo** [comment]
Moving to draft - I'm going to merge commits from pzygielo#3 - but then to revert my unneeded change to `skipPoms`.

**Review by dmatej — APPROVED** [review]

**Pull request merged**
