### PR TITLE
Is #22676: quickLook: adminconsole_tests fails

### LINKED ISSUE #22676: quickLook: adminconsole_tests fails
## Environment Details
* GlassFish Version (and build number): EE4J_8 branch, bacf743af

## Problem Description
server log says:
```
[2018-12-18T21:42:29.717+0100] [glassfish 5.0] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=210 _ThreadName=Thread-66] [timeMillis: 1545165749717] [levelValue: 1000] [[
  Exception during lifecycle processing
com.sun.enterprise.module.ResolveError: Not able to locate a unique module by name javax.servlet-api
    at com.sun.enterprise.v3.server.ClassLoaderHierarchyImpl.createApplicationParentCL(ClassLoaderHierarchyImpl.java:148)
    at org.glassfish.deployment.common.DeploymentContextImpl.createClassLoader(DeploymentContextImpl.java:222)
    at org.glassfish.deployment.common.DeploymentContextImpl.createDeploymentClassLoader(DeploymentContextImpl.java:205)
    at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:341)
    at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:382)
    at com.sun.enterprise.v3.admin.adapter.InstallerThread.load(InstallerThread.java:187)
    at com.sun.enterprise.v3.admin.adapter.InstallerThread.run(InstallerThread.java:76)
]]

[2018-12-18T21:42:29.719+0100] [glassfish 5.0] [SEVERE] [NCLS-CORE-00041] [javax.enterprise.system.core] [tid: _ThreadID=210 _ThreadName=Thread-66] [timeMillis: 1545165749719] [levelValue: 1000] [[
  Application deployment failed: Exception while deploying the app [__admingui]]] 
```

## Steps to reproduce
mvn -f appserver/tests/quicklook/pom.xml test -Dglassfish.home=appserver/distributions/glassfish/target/stage/glassfish5/glassfish

## Impact of Issue
admingui is broken

### PR DESCRIPTION
**Pull request by lukasj**
Fixes #22676

### CODE REVIEW

**Review by edbratt — APPROVED** [review]
LGTM

**Comment by romain-grecourt** [comment]
the pipeline is likely to fail without purging the old jakarta-servlet-api from the cache.

**Comment by romain-grecourt** [comment]
Then the build would be broken every Sunday lol :)
Re-release should be forbidden and only allowed on a case by case basis.

**Comment by lukasj** [comment]
And people would have something "real" to do on Mondays :-D

**Pull request merged**
