### PR TITLE
Merge 5.1.0 branch into master

### PR DESCRIPTION
**Pull request by romain-grecourt**

### CODE REVIEW

**Review by bshannon — APPROVED** [review]

**Comment by smillidge** [comment]
Looks like glassfish-bot is failing the ECA check. Anybody know whether this can just be merged?

**Comment by bshannon** [comment]
Yes, it's a bug that the bot doesn't pass the ECA check.
@romain-grecourt, are you going to look into the CI failures?

**Comment by romain-grecourt** [comment]
I'll take a look.

**Comment by smillidge** [comment]
@romain-grecourt  I assume this needs closing?

**Comment by smillidge** [comment]
Closing as master has now moved to 6.0.0-SNAPSHOT

**Pull request closed without merging**
