### PR TITLE
Adding the firstcup project needed to follow the jakarta ee firstcup tutorial

### PR DESCRIPTION
**Pull request by gabrielbussolo**
Hey guys, 
I am reading Jakarta and First Cup and taking the opportunity to make some contributions.
There is a reference to the "Java EE SDK" which is nothing more than glassfish 5 with this project that I am adding.
So I am adding the project so that we can correct the Jakarta and Firstcup documentation with a link to glassfish already with the example of "firstcup".
Besides, I opened a pull request with the correction in the jakartaee firstcup eclipse-ee4j/jakartaee-firstcup/pull/15

### CODE REVIEW

**Comment by gabrielbussolo** [comment]
Just justifiyng my force push,
I had added the oracle example project, then I realized that we already had the project eclipse-ee4j/jakartaee-firstcup-examples
So I changed to this files.

**Comment by smillidge** [comment]
Hi @gabrielbussolo thanks for the contribution. I'm not sure what you are trying to do. Aren't the files you are adding already in the first cup project? Sorry for my confusion.

**Comment by gabrielbussolo** [comment]
@smillidge sorry, I do not detail the pull request as it should.

The old Java First Cup tutorial instructed us to [download the "Java EE SDK"] (https://javaee.github.io/firstcup/intro002.html#get-the-java-ee-8-sdk) to follow the tutorial, however I noticed that this project is basically a glassfish with the first-cup-examples project inside the doc folder.

Content of docs folder at "Java EE SDK"
Java SDK

Content of docs folder of our glassfish (downloaded from Eclipse website)
Eclipse Glassfish

We can add the docs from the firstcup project to our glassfish project to keep it as it was or we can change the java first cup tutorial to do it differently (by cloning the examples repository for example).

I'm working to improve jakartaee-firstcup, so I'm opened to feedback!

Thanks!

**Comment by gabrielbussolo** [comment]
So, rethinking this pull request, I think we can separate the two things, glassfish and jakarta-firstcup-examples, I will submit a pull request with new instructions to the firstucup :)

**Pull request closed without merging**
