### PR TITLE
Issue #24284 Fixed git.build.time

### PR DESCRIPTION
**Pull request by dmatej**
- Fixes comment in #24284
- was overriden by a value from eclipse project 1.0.8

### CODE REVIEW

**Comment by pzygielo** [comment]
I'd rather have ever-changing `git.build.time` removed from `build.id` than move away from reproducible builds goal (I understand it's centuries of work to do to have it here, and such goal is not even established yet...).

IMO - the timestamp in signature file is enough.

- https://github.com/eclipse-ee4j/ee4j/pull/71 - @hboutemy - what do you think?

**Comment by dmatej** [comment]
> I'd rather have ever-changing `git.build.time` removed from `build.id` than move away from reproducible builds goal (I understand it's centuries of work to do to have it here, and such goal is not even established yet...).
> 
> IMO - the timestamp in signature file is enough.
> 
> * [prepare Reproducible Builds ee4j#71](https://github.com/eclipse-ee4j/ee4j/pull/71) - @hboutemy - what do you think?

I have yet another changes prepared, but I wanted to push this first before somebody starts screaming that I did too many changes again :D (revisited branding.properties, related documentation and implementation)

Also - the commit is useful when you start arguing what was the source commit of the build. That's what I did in my next PR (yet after one with plugin updates).

I don't understand the reason for https://github.com/eclipse-ee4j/ee4j/pull/71 - it doesn't make builds reproducible at all. I think it should work exactly opposite - to be able to run the build with -Dproject.build.outputTimestamp with one concrete time stamp for several executions, but this change made it mandatory.

**Comment by dmatej** [comment]
But maybe we could even abandon the build id and rather replace it with more readable information instead of generating "magical" id: 
* the source commit
* the timestamp

Then in the log output instead of this:
`Running GlassFish Version: Eclipse GlassFish  7.0.2  (build updates-b43-g6276a24 2020-12-19T18:24:00+0100)]]`
would be this:
`Running GlassFish Version: Eclipse GlassFish  7.0.2-SNAPSHOT  (commit ec1ce24934f0bb174333a9886b58a0d2f9e52b44, timestamp 2023-02-25T18:24:00+0100)]]`

(My usual issue - do I work with snapshot or with a released version? How old is it?)

**Comment by pzygielo** [comment]
> I'd rather have ever-changing `git.build.time` removed from `build.id`.

This would leave other `build.id`' components like branch, commits since last tag and commit to give: `updates-b43-g6276a24`. Which by the way - `b{xx}` is questionable.

I'm all for only-commit (full hash) (and no timestamp).

**Comment by pzygielo** [comment]
> I have yet another changes prepared, but I wanted to push this first
:+1:

**Review by pzygielo — APPROVED** [review]

**Pull request merged**
