### PR TITLE
[master] JSON-P updated to 1.1.5

### PR DESCRIPTION
**Pull request by Tomas-Kraus**

### CODE REVIEW

**Comment by romain-grecourt** [comment]
@Tomas-Kraus the staging profile is used, see this file: https://github.com/eclipse-ee4j/glassfish/blob/391cf42697608d8a7a98dae5eb4cdcd905eb259d/gfbuild.sh#L66

**Comment by Tomas-Kraus** [comment]
We should put this into both master abnd EE4J_8.
@romain-grecourt please restart buld job again. I added jsonp artifacts into staging.

**Comment by romain-grecourt** [comment]
> We should put this into both master abnd EE4J_8.
> @romain-grecourt please restart buld job again. I added jsonp artifacts into staging.

This file is the same in both branches, what are you talking about ?

**Comment by Tomas-Kraus** [comment]
> This file is the same in both branches, what are you talking about ?
About this changeset.

**Comment by romain-grecourt** [comment]
I don't understand what you are saying. Even in your fork the script does use -U -Pstaging.
Can you be more explicit ?

**Comment by romain-grecourt** [comment]
The initial pipeline error is gone, now it's failing with the same issue as #22624. I've seen this error with maven.java.net many times but I never really figured out the reason for it.

The issue is related to https://maven.java.net/content/repositories/releases but I can't reproduce the error ; tried using the docker image of the pipeline with no luck. I'll be trying a few things, in the last resort we can remove the repository definition from the parent pom (nucleus/parent/pom.xml)

**Comment by romain-grecourt** [comment]
@Tomas-Kraus please refresh your PR with the latest master

**Comment by romain-grecourt** [comment]
@Tomas-Kraus You will need to push a separate PR against EE4J_8.
Question: why changing javax.json-api.jar for javax.json.jar in the manifest-jar ?

**Comment by Tomas-Kraus** [comment]
@romain-grecourt javax.json.jar was a typo. But this change has some reasons. JSOPN-P packaging was reverted to old API+IMPL bundle so in glassfish/modules there is now jakarta.json.jar which contains both javax.json (API) and org.glassfish.json (IMPL) packages.
Manifest ClassPath must be changed to point to this jar instead of javax.json-api.jar
Typo was fixed in current PR diff.

**Comment by Tomas-Kraus** [comment]
It's failing with
```
[ERROR] Failed to execute goal on project glassfish-embedded-static-shell: Could not resolve dependencies for project org.glassfish.main.extras:glassfish-embedded-static-shell:jar:5.0.1-SNAPSHOT: Failed to collect dependencies at org.glassfish.jersey.media:jersey-media-json-processing:jar:2.27 -> org.glassfish:jsonp-jaxrs:jar:1.1.5: Failed to read artifact descriptor for org.glassfish:jsonp-jaxrs:jar:1.1.5: Could not transfer artifact org.glassfish:jsonp-jaxrs:pom:1.1.5 from/to sonatype-nexus-staging (https://oss.sonatype.org/content/repositories/staging): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty -> [Help 1]
```
now - please can you restart the job?

**Comment by Tomas-Kraus** [comment]
Removed Mimepull updated. I'll put it as separate PR. Let's resolve JSONP in this one.

**Comment by romain-grecourt** [comment]
@Tomas-Kraus Why the move back to standalone bundle ? I remember explicitly asking Jitu to split this into API + IMPL as this was a new API at the time: there was no historical reason force it to be standalone bundle.
@bshannon FYI

**Comment by bshannon** [comment]
The historical reason for standalone bundles was for the convenience of people who
were downloading jars manually and adding them to their classpath.  Maybe enough
people are using Maven and other tools now so that's no longer an important
consideration.

**Comment by romain-grecourt** [comment]
My point is why the sudden change ? Given the recent discussions, I think there should be a valid reason for making jsonp a standalone bundle when the current version is not.

**Comment by bshannon** [comment]
I thought the change was just to how it was bundled in GlassFish.
If the change was to JSON-P itself, I don't know why that was done.

**Comment by romain-grecourt** [comment]
Quoting @Tomas-Kraus 
> But this change has some reasons. JSOPN-P packaging was reverted to old API+IMPL bundle so in glassfish/modules there is now jakarta.json.jar which contains both javax.json (API) and org.glassfish.json (IMPL) packages.

**Comment by romain-grecourt** [comment]
I think the impl is now standalone, the API seems untouched. It was likely done with this change by @lukasj https://github.com/eclipse-ee4j/jsonp/commit/01ee02ac803cbf5c78bbb39959b6b4c48f69a1a5

**Comment by lukasj** [comment]
The final EE8 release contained standalone bundle, split was done later (in 1.1.2) but due to osgi related issues (couldn't get serviceloader working in generic osgi env within the time I could allocate to it), we decided to go back to the proven working way (in 1.1.4), see also https://github.com/eclipse-ee4j/jsonp/blob/master/bundles/ri/src/main/resources/README.txt

**Comment by romain-grecourt** [comment]
Thanks for correcting me. The jsonp impl was done as a standalone jar from the start. (the change I referred to was actually about references to org.glassfish.json from some javax.json concrete classes)

This means it's all good and we should be able to merge as soon as the pipeline gets better.

**Comment by Tomas-Kraus** [comment]
@romain-grecourt Unfortunately current error in pipeline is something that I can't reproduce. According to https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty it has something to do with keystore of JDK on your image.

**Comment by Tomas-Kraus** [comment]
Merged/rebased master into this PR to see whether it helps.

**Comment by romain-grecourt** [comment]
GF_HOME/lib/embedded/glassfish-embedded-static-shell.jar has the old javax.json.jar in its MANIFEST class-path entry

**Comment by romain-grecourt** [comment]
This should do it:

```diff
diff --git a/appserver/extras/embedded/shell/glassfish-embedded-static-shell/pom.xml b/appserver/extras/embedded/shell/glassfish-embedded-static-shell/pom.xml
index fa48a4cd..46b55243 100755
--- a/appserver/extras/embedded/shell/glassfish-embedded-static-shell/pom.xml
+++ b/appserver/extras/embedded/shell/glassfish-embedded-static-shell/pom.xml
@@ -64,7 +64,7 @@
                           <fileSeparator>/</fileSeparator>
                           <prefix>../../modules</prefix>
                           <stripVersion>true</stripVersion>
-                          <excludeArtifactIds>jsftemplating</excludeArtifactIds>
+                          <excludeArtifactIds>jsftemplating, javax.json, jakarta.json-api</excludeArtifactIds>
                       </configuration>
                   </execution>
               </executions>
@@ -1233,6 +1233,11 @@
             <artifactId>javax.security.enterprise-api</artifactId>
             <optional>true</optional>
         </dependency>
+        <dependency>
+            <groupId>org.glassfish</groupId>
+            <artifactId>jakarta.json</artifactId>
+            <optional>true</optional>
+        </dependency>
         <!-- glassfish-jersey -->
         <dependency>
             <groupId>org.glassfish.jersey.media</groupId>
```

Looking at this stuff reminded me how ugly the embedded packaging is, this needs to be cleaned-out in the future.

**Comment by Tomas-Kraus** [comment]
Looks like this PR has problem with source repository reference. Will create a new one.

**Pull request closed without merging**
