### PR TITLE
Issue 24900 part 1: document and refactor, part 2: add first step in PoolManagerImpl unit test

### PR DESCRIPTION
**Pull request by escay**
Draft for now, I would like to add more unit tests and I would like to remove a number of TODO statements I added in ConnectionPool and PoolManagerImpl classes.

Part 1 for issue #24900 Document and rename some ResourceHandle fields. Document and rename some ConnectionPool fields. Remove some unused methods and constructor parameters. Functional / possible incompatibility changes in DataStructureFactory and in ResourceHandle due to constructor changes.
(Maybe part 1 is a bit too much, I altered a few interfaces and removed unused parameters)

Part 2 for issue #24900 Start with a new PoolManagertImpl unit test to understand enlisted versus busy states of Resource handles and the wiring inside a transaction to keep track of all used resources.

### CODE REVIEW

**Comment by escay** [comment]
Part 3 for issue #24900 adds some more documentation. Main item of this commit is: 
- Changed unit test to show 2 points where I would expect different behaviour. In case of resourceAbortOccurred and resourceErrorOccurred the connectionErrorOccurred flag of the resource is not set, while it is set in badConnectionClosed logic.
- Changed unit test to show removing resources from a transaction seems to behave as expected for basic scenarios.

**Comment by dmatej** [comment]
I am bit confused why there's so many changes and some look like they already are in the master branch. Is it some GitHub issue? Seems so ... I tried locally:
* PoolManagerImplTest contains windows eolns, You can configure it in Eclipse IDE and other editors. Weird that Jenkins did not complain.... Aha, I did not add this rule to checkstyle.xml yet ...
* Otherwise it looks well

**Comment by escay** [comment]
@dmatej Not sure what happened. I had a few tasks from May I wanted to rebase to the most recent master (maybe I used an incorrect approach into getting all master tasks into this branch), then I made a few mistakes in merging the import changes. I will try to clean it up and make a correct pull request. This should have been draft so far.

**Comment by dmatej** [comment]
Just replace those crlf with lf (linux) and I believe it will be alright. I tried to fetch and compare your brach with master and it seems ok, just github is somehow confused and shows diff to some old commit.

**Comment by escay** [comment]
Not sure why the last build failed and the build before the 'crlf' fix did not fail. Perhaps a rebuild is needed, but I cannot start it I think.
The commits together:

[Part 1 for issue](https://github.com/eclipse-ee4j/glassfish/pull/24901/commits/b1d3069851a0aeb2057cd727752b943c3349dbfe) https://github.com/eclipse-ee4j/glassfish/issues/24900 [Document and rename some Resource…](https://github.com/eclipse-ee4j/glassfish/pull/24901/commits/b1d3069851a0aeb2057cd727752b943c3349dbfe)
[b1d3069](https://github.com/eclipse-ee4j/glassfish/pull/24901/commits/b1d3069851a0aeb2057cd727752b943c3349dbfe)

[Part 2 for issue](https://github.com/eclipse-ee4j/glassfish/pull/24901/commits/6ec33909897c115650e02af93217c351399b9de1) https://github.com/eclipse-ee4j/glassfish/issues/24900 [Start with a new PoolManagertImpl…](https://github.com/eclipse-ee4j/glassfish/pull/24901/commits/6ec33909897c115650e02af93217c351399b9de1)
[6ec3390](https://github.com/eclipse-ee4j/glassfish/pull/24901/commits/6ec33909897c115650e02af93217c351399b9de1)

[Part 3 for issue](https://github.com/eclipse-ee4j/glassfish/pull/24901/commits/bb41ac52986efd22d0135e8469ab8acd0b06c416) https://github.com/eclipse-ee4j/glassfish/issues/24900 [More documentation and more unit …](https://github.com/eclipse-ee4j/glassfish/pull/24901/commits/bb41ac52986efd22d0135e8469ab8acd0b06c416)
[bb41ac5](https://github.com/eclipse-ee4j/glassfish/pull/24901/commits/bb41ac52986efd22d0135e8469ab8acd0b06c416)

[Part 4 for issue](https://github.com/eclipse-ee4j/glassfish/pull/24901/commits/027b7d20502ec6e0af1f2c68960f4b843a6e487e) https://github.com/eclipse-ee4j/glassfish/issues/24900 [Add more detailed logging to impr…](https://github.com/eclipse-ee4j/glassfish/pull/24901/commits/027b7d20502ec6e0af1f2c68960f4b843a6e487e)
[027b7d2](https://github.com/eclipse-ee4j/glassfish/pull/24901/commits/027b7d20502ec6e0af1f2c68960f4b843a6e487e)

[Merge branch 'issue_24900' of](https://github.com/eclipse-ee4j/glassfish/pull/24901/commits/f000acdf92a34f1238d4ac50d55dd0a2e42344f3) https://github.com/escay/glassfish [into…](https://github.com/eclipse-ee4j/glassfish/pull/24901/commits/f000acdf92a34f1238d4ac50d55dd0a2e42344f3)
[f000acd](https://github.com/eclipse-ee4j/glassfish/pull/24901/commits/f000acdf92a34f1238d4ac50d55dd0a2e42344f3)

[Fix checkstyle for issue](https://github.com/eclipse-ee4j/glassfish/pull/24901/commits/d9d1f6297bac9590c93bffd414646e00a0178f37) https://github.com/eclipse-ee4j/glassfish/issues/24900 [merge.](https://github.com/eclipse-ee4j/glassfish/pull/24901/commits/d9d1f6297bac9590c93bffd414646e00a0178f37)
[d9d1f62](https://github.com/eclipse-ee4j/glassfish/pull/24901/commits/d9d1f6297bac9590c93bffd414646e00a0178f37)

[Change 'git ls-files --eol' value i/-text to i/lf](https://github.com/eclipse-ee4j/glassfish/pull/24901/commits/e902173713b757a6bea7efaa85758379c85f70d2)
[e902173](https://github.com/eclipse-ee4j/glassfish/pull/24901/commits/e902173713b757a6bea7efaa85758379c85f70d2)

Solve issue #24900 
The TODOs (PoolManagerImpl) I added in the code I plan to investigate later on to see if I can improve/solve them.

**Comment by pzygielo** [comment]
472 commits, 4006 files - seriously?

**Comment by pzygielo** [comment]
> > 472 commits, 4006 files - seriously?
> 
> I did a rebase last week to get my changes from May in this branch to work, it is only the last 7 commits. Maybe I rebased wrong as mentioned above.

> I will try to clean it up and make a correct pull request. 

I was waiting for that.

**Comment by pzygielo** [comment]
Why changes from 8.0 are merged-in? I'm against pulling them in with this PR.

**Comment by pzygielo** [comment]
> I didn't because @dmatej told me to just commit the lf change.

But it didn't work, did it? And yet you marked as ready to review. So I comment on what I see.

**Comment by escay** [comment]
I think the crlf / lf linefeed change in 1 unit test file succeeded. I do not know why the build failed in the ejb_group_2 set, and I cannot start a new build to see if it was an environment change. It was not the linefeed change in the unit test file.
I only rebased to master as far as I know, I do not know the 8.0 branch names.

If needed I can create a new branch a do everything fresh, so you more easily review 4 cleaner commits.

**Comment by pzygielo** [comment]
> I cannot start a new build to see if it was an environment issue. 

Started build no. 11.

**Comment by pzygielo** [comment]
@escay Does this https://github.com/eclipse-ee4j/glassfish/compare/master...pzygielo:glassfish:pr24901?expand=1 look like the changes intended?

**Comment by escay** [comment]
@pzygielo It looks like the changes indeed. But I do not see a few new files like InjectionUtil and PoolManagerImplTest.

**Comment by pzygielo** [comment]
> I do not see a few new files like InjectionUtil and PoolManagerImplTest.

True, I see I've missed untracked on commit.
Updated my branch for consistency.

**Comment by dmatej** [comment]
I reviewed using this command without --stat. GitHub's UI failed in this case.
```
git diff -w -M eclipse/master..escay/issue_24900 --stat
```

**Comment by OndroMih** [comment]
Is it maybe better to close this PR and create it again, so that it contains only the real changes?

**Comment by escay** [comment]
(No problem for me, just let me know)

**Comment by pzygielo** [comment]
> just let me know

@escay - please do

**Comment by dmatej** [comment]
GOTO replacement of this PR: https://github.com/eclipse-ee4j/glassfish/pull/25155

**Pull request closed without merging**
