### PR TITLE
PR for #23615 Professional Services Section to README.md, Update Download Page for 6.2.1

### PR DESCRIPTION
**Pull request by gerdogdu**
PR for the issue #23615 .
Can you please review?

### CODE REVIEW

**Comment by gerdogdu** [comment]
Can you please look and review this PR?

**Comment by gerdogdu** [comment]
I have also updated https://glassfish.org/ to reflect 6.2.1 News and Download info.
Can you please review this PR?

**Comment by gerdogdu** [comment]
This is a simple PR. Do you see any problem to not approve this PR? If so, could you please explain what it is? Most of the open source projects include commercial support companies to their website or documentation as I included example of Jetty, https://github.com/eclipse/jetty.project

**Comment by waynebeaton** [comment]
I figure that somebody is going to ask me eventually, so...

The addition in the README.md is completely consistent with the Eclipse Foundation Development Process. 

The rule that applies here is that vendor-neutrality must be observed. Care needs to be taken to make sure that there is no confusion that the project itself is an Eclipse open source project, not a Vendor X open source project. In that context, including links to vendors who provide services for an open source project is fine, so long as other organizations can participate via the same set of rules (e.g., if you have an active committer on the project then we can link to your company's services related to the project). The links should be a statement of fact without qualification or anything that looks like an advertisement or endorsement (i.e., "Vendor X provides services related to this project", not "Vendor X is the preferred services provided for this project"), and it needs to be very obvious that the links lead to pages that have a distinct appearance (i.e., don't fool the user into thinking that the services provider page is part of the open source project's website).

HTH

**Comment by TanjaObradovic** [comment]
thanks @waynebeaton

**Comment by dmatej** [comment]
Thank you, that was my question, I wasn't sure if it is acceptable to have it mentioned here :-)

**Review by dmatej — APPROVED** [review]

**Comment by waynebeaton** [comment]
> Thank you, that was my question, I wasn't sure if it is acceptable to have it mentioned here :-)

FWIW, I've used this as an opportunity to add some content on the topic to the handbook that will be included in the next roll out.

**Pull request merged**
