### PR TITLE
Feature: allow using @Inject instead of @Context for simple injection

### LINKED ISSUE #24049: Include org.glassfish.jersey.ext.cdi:jersey-cdi-rs-inject to support @Inject in Jakarta REST
## Environment Details
* GlassFish Version (and build number): Glassfish
* JDK version: 17
* OS: Windows
* Database: built-in Derby

----------

## Problem Description
I have tried to use `@Inject` to replace `@Context` in Jaxrs beans, all failed to works.
see: https://github.com/eclipse-ee4j/jersey/issues/5100

```java
@Path("todos")
@RequestScoped
public class TodoResources {

    //@Inject
    @Context
    ResourceContext resourceContext;

    //@Inject
    @Context
    UriInfo uriInfo;

````

And I follow the new features in Rest 3.1 article to taste Jaxrs 3.1. https://dev.to/andymc12/what-s-coming-in-jakarta-rest-3-1-ole

## Steps to reproduce
1. Checkout my sample project,  https://github.com/hantsy/jakartaee10-sandbox/tree/master/rest 
2. build and deploy to Glassfish
3. If changing `@Context` to `@Inject` in the `TodoResources.java`, all failed.

### PR DESCRIPTION
**Pull request by arjantijms**
Fixes #24049

### CODE REVIEW

**Review by dmatej — APPROVED** [review]
Test would be nice ;-)

**Review by senivam — APPROVED** [review]
yes, agree, that tests would be nice, at least the reproducer from the mentioned issue.

**Review by avpinchuk — APPROVED** [review]

**Review by gurunrao — APPROVED** [review]

**Comment by OndroMih** [comment]
In Github, it looks like you changed 4 depencies. But in fact, you only added `jersey-cdi-rs-inject` and excluded dependencies from `jersey-media-json-processing`? Why is that? Can you change the code so that the diff only shows what was really changed?

**Comment by arjantijms** [comment]
This feature has triggered a very interesting, but also very obscure failure in GlassFish Embedded (and only Embedded).

The core failure is that when CDI validates the `Bean<T>` instance `org.glassfish.jersey.ext.cdi1x.inject.internal.InjectExtension$ServletReferenceProducerBean` it fails to resolve the injected `org.glassfish.jersey.internal.inject.InjectionManager`.

A Bean that provides an instance `org.glassfish.jersey.internal.inject.InjectionManager` is really added though, but eventually in `org.jboss.weld.bootstrap.events.AfterBeanDiscoveryImpl.processBeanRegistration(BeanRegistration, GlobalEnablementBuilder)` a different bean archive and subsequently bean manager is retrieved for it every time:

**GF Embedded**

Run 1)
_Bean:_
org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider$Hk2Bean
  t = interface org.glassfish.jersey.internal.inject.InjectionManager

_Bean Archive:_
|ID: org.glassfish.enterprise.concurrent.cdi.ConcurrentCDIExtension, bdaType= UNKNOWN, accessibleBDAs #:1, [,], Bean Classes #: 1,[org.glassfish.enterprise.concurrent.cdi.ConcurrentCDIExtension], ejbs=[]
|---->ID: org.omnifaces.jwt.cdi.CdiExtension, bdaType= UNKNOWN, accessibleBDAs #:0, [], Bean Classes #: 1,[org.omnifaces.jwt.cdi.CdiExtension], ejbs=[]

_Bean Manager:_
Weld BeanManager for org.glassfish.enterprise.concurrent.cdi.ConcurrentCDIExtension [bean count=102]


Run 2)
_Bean:_
org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider$Hk2Bean
  t = interface org.glassfish.jersey.internal.inject.InjectionManager

_Bean Archive:_
|ID: com.sun.faces.flow.FlowDiscoveryCDIExtension, bdaType= UNKNOWN, accessibleBDAs #:1, [,], Bean Classes #: 1,[com.sun.faces.flow.FlowDiscoveryCDIExtension], ejbs=[]
|---->ID: org.eclipse.krazo.cdi.KrazoCdiExtension, bdaType= UNKNOWN, accessibleBDAs #:0, [], Bean Classes #: 1,[org.eclipse.krazo.cdi.KrazoCdiExtension], ejbs=[]

_Bean Manager:_
Weld BeanManager for com.sun.faces.flow.FlowDiscoveryCDIExtension [bean count=96]



Run 3)
_Bean:_
org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider$Hk2Bean
  t = interface org.glassfish.jersey.internal.inject.InjectionManager

_Bean Archive:_
|ID: org.glassfish.jms.injection.JMSCDIExtension, bdaType= UNKNOWN, accessibleBDAs #:1, [,], Bean Classes #: 1,[org.glassfish.jms.injection.JMSCDIExtension], ejbs=[]
|---->ID: org.eclipse.krazo.cdi.KrazoCdiExtension, bdaType= UNKNOWN, accessibleBDAs #:0, [], Bean Classes #: 1,[org.eclipse.krazo.cdi.KrazoCdiExtension], ejbs=[]

_Bean Manager:_
Weld BeanManager for org.glassfish.jms.injection.JMSCDIExtension [bean count=122]

**Comment by arjantijms** [comment]
> In Github, it looks like you changed 4 depencies. But in fact, you only added `jersey-cdi-rs-inject` and excluded dependencies from `jersey-media-json-processing`? Why is that? Can you change the code so that the diff only shows what was really changed?

It only looked like that because of the order or elements and GitHub diff not seems to get that. Eclipse diff showed it better. But I changed the order somewhat so now it only shows a single element added in GitHub diff.

**Comment by OndroMih** [comment]
It looks like you managed to fix the issue in GF embedded, good job!

I would still revert the changes in imports in `DeploymentImpl.java` it looks like your IDE just reordered the imports but they didn't change. As long as we don't have a decision about the ordering of the imports, I would rather keep them unchanged, so that the PR only touches the lines that were really changed.

**Review by dmatej — APPROVED** [review]

**Review by avpinchuk — APPROVED** [review]

**Pull request merged**
