### PR TITLE
increase java version and reference jaxb explicitly

### PR DESCRIPTION
**Pull request by rlfnb**
Signed-off-by: rlfnb <github@rlfnb.de>

My change wont compile, as the referenced version of the command-security-plugin might be not available. As the needed change to ompile with java11 is already done there, @arjantijms @Cousjava might do a release (https://github.com/eclipse-ee4j/glassfish-security-plugin/issues/9) and I can change the version accordingly.

### CODE REVIEW

**Comment by rlfnb** [comment]
I changed the version of command-security-plugin back to 1.10. Nevertheless, the old command-security-plugin hides other build errors. Simply want to make the PRs small to make it easy to see what happens.

**Comment by bshannon** [comment]
It's taken quite a few attempts to get the CI tests to mostly pass, but now I'm seeing this failure:


Caused by: org.osgi.framework.BundleException: Unable to resolve org.glassfish.main.core.kernel [41](R 41.0): missing requirement [org.glassfish.main.core.kernel [41](R 41.0)] osgi.wiring.package; (&(osgi.wiring.package=com.sun.enterprise.admin.progress)(version>=5.1.0)(!(version>=6.0.0))) [caused by: Unable to resolve org.glassfish.main.admin.util [16](R 16.0): missing requirement [org.glassfish.main.admin.util [16](R 16.0)] osgi.wiring.package; (&(osgi.wiring.package=com.sun.enterprise.config.serverbeans)(version>=5.1.0)(!(version>=6.0.0))) [caused by: Unable to resolve org.glassfish.main.admin.config-api [9](R 9.0): missing requirement [org.glassfish.main.admin.config-api [9](R 9.0)] osgi.wiring.package; (&(osgi.wiring.package=com.sun.appserv.server.util)(version>=5.1.0)(!(version>=6.0.0))) [caused by: Unable to resolve org.glassfish.main.common.util [180](R 180.0): missing requirement [org.glassfish.main.common.util [180](R 180.0)] osgi.wiring.package; (&(osgi.wiring.package=org.glassfish.api)(version>=5.1.0)(!(version>=6.0.0))) [caused by: Unable to resolve org.glassfish.main.common.glassfish-api [131](R 131.0): missing requirement [org.glassfish.main.common.glassfish-api [131](R 131.0)] osgi.wiring.package; (&(osgi.wiring.package=javax.xml.bind.annotation)(version>=2.3.0)(!(version>=3.0.0)))]]]] Unresolved requirements: [[org.glassfish.main.core.kernel [41](R 41.0)] osgi.wiring.package; (&(osgi.wiring.package=com.sun.enterprise.admin.progress)(version>=5.1.0)(!(version>=6.0.0)))]


This could possibly be due to the change in the jakarta.xml.bind-api dependency in nucleus/hk2/config-types/pom.xml.

**Comment by rlfnb** [comment]
I removed the newly introduced dependency to pass the tests. Will take care of the dependency later.

**Comment by rlfnb** [comment]
Maybe another related question: Is it possible to address this #22754 as well? ATM, the issue hides most of the progress we made already for bein compilable with java11.

**Comment by bshannon** [comment]
@lukasj can you help with this JAXB-related issue?

**Comment by lukasj** [comment]
@bshannon jaxb integ is being taken care of in #22971

**Comment by arjantijms** [comment]
The branch from which the PR is done should be rebased on current master; it currently fails in the changed HK2 Module type.

**Pull request closed without merging**
