### PR TITLE
[EE4J_8] Mimepull updated to 1.9.11, JSON-P updated to 1.1.5

### PR DESCRIPTION
**Pull request by Tomas-Kraus**
Backport from master branch.

### CODE REVIEW

**Comment by romain-grecourt** [comment]
@Tomas-Kraus a PR was merged (#22644) with test failures this is why you are seeing these now.
Need to revert that commit and you'll have to pick-up the latest EE4J_8 again.
@arjantijms FYI

**Comment by romain-grecourt** [comment]
@Tomas-Kraus looking at the test failures I see some `java.lang.ClassNotFoundException: javax.json.JsonValue` ; this must be some kind of classpath configuration issue.

**Comment by lukasj** [comment]
@romain-grecourt shouldn't  https://github.com/eclipse-ee4j/glassfish/blob/EE4J_8/appserver/core/api-exporter-fragment/pom.xml#L64 be updated to include all EE8 APIs instead? Ie jsonp/b, batch seems to be missing there

**Comment by romain-grecourt** [comment]
Good question, I don't recall the purpose of this module.

**Review by romain-grecourt — APPROVED** [review]

**Pull request merged**
