### PR TITLE
Debugging support 2.0, preliminary TCK result summary

### PR DESCRIPTION
**Pull request by edbratt**
Preliminary TCK Summary results for Eclipse GlassFish 6, for Debugging Support for Other Languages

### CODE REVIEW

**Review by m0mus — APPROVED** [review]
LGTM

**Comment by m0mus** [comment]
Shall it go to `gh-pages` branch?

**Review by m0mus — CHANGES_REQUESTED** [review]
Shall it go to `gh-pages` branch?

**Comment by edbratt** [comment]
@m0mus Doc changes go to Master. There is a Jenkins job that will kick-off and builds all the material and promotes it to gh-pages. So, no, this should not go to the gh-pages branch. See the readme https://github.com/eclipse-ee4j/glassfish/blob/master/docs/README.md

**Review by m0mus — APPROVED** [review]
LGTM

**Comment by edbratt** [comment]
TY @m0mus

**Pull request merged**
