### PR TITLE
Add smoke test for appclient consuming resource from server

### PR DESCRIPTION
**Pull request by arjantijms**
Currently crashes with:

```
java.lang.ClassNotFoundException: com.sun.gjc.spi.ResourceAdapterImpl
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:440)
	at org.glassfish.appclient.client.acc.ACCClassLoader.findClass(ACCClassLoader.java:208)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.sun.enterprise.connectors.ActiveRAFactory.createActiveResourceAdapter(ActiveRAFactory.java:79)
        at com.sun.enterprise.connectors.ActiveRAFactory.createActiveResourceAdapter(ActiveRAFactory.java:87)
	at com.sun.enterprise.connectors.service.ResourceAdapterAdminServiceImpl.createActiveResourceAdapter(ResourceAdapterAdminServiceImpl.java:188)
	at com.sun.enterprise.connectors.ConnectorRuntime.createActiveResourceAdapter(ConnectorRuntime.java:404)
	at com.sun.enterprise.resource.naming.ConnectorObjectFactory.getObjectInstance(ConnectorObjectFactory.java:82)
javax.naming.NamingException: Failed to look up ConnectorDescriptor from JNDI [Root exception is com.sun.appserv.connectors.internal.api.ConnectorRuntimeException: Error in creating active RAR]
	at com.sun.enterprise.resource.naming.ConnectorObjectFactory.getObjectInstance(ConnectorObjectFactory.java:89)
	at java.naming/javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:342)
	at com.sun.enterprise.naming.impl.SerialContext.getObjectInstance(SerialContext.java:503)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:463)
javax.naming.NamingException: Lookup failed for 'jdbc/DB1' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, com.sun.enterprise.naming.logicalName=java:comp/env/com.sun.ts.tests.concurrency.spec.ContextService.tx.Client/dataSource}
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:467)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:414)
	at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
	at com.sun.enterprise.naming.util.JndiNamingObjectFactory.create(JndiNamingObjectFactory.java:66)
	at com.sun.enterprise.naming.util.JndiInitializationNamingObjectFactory.create(JndiInitializationNamingObjectFactory.java:86)
	at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:721)
	at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:691)
	at com.sun.enterprise.naming.impl.JavaURLContext.lookup(JavaURLContext.java:135)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:447)
```

Signed-off-by: arjantijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Comment by arjantijms** [comment]
@dmatej 

After a quick investigation, it looks like the jar names have changed:

6.2.2
`glassfish/lib/install/applications/__ds_jdbc_ra/__ds_jdbc_ra.jar`

6.2.3-SNAPSHOT
`glassfish/lib/install/applications/__ds_jdbc_ra/jdbc-ra-ds.jar`

**Comment by dmatej** [comment]
These dependencies have org.glassfish.main.tests.tck groupId now
`[ERROR] Failed to execute goal on project concurrency_appclient: Could not resolve dependencies for project org.glassfish.main.tests.tck:concurrency_appclient:jar:6.2.3-SNAPSHOT: The following artifacts could not be resolved: com.sun:javatest:jar:5.0, com.sun:tsharness:jar:1.4: Could not find artifact com.sun:javatest:jar:5.0 in staging (https://jakarta.oss.sonatype.org/content/repositories/staging) -> [Help 1]`

**Comment by pzygielo** [comment]
Where one can find
```xml
        <dependency>
            <groupId>org.glassfish.main.tests</groupId>
            <artifactId>glassfish-javatest-install</artifactId>
            <version>${project.version}</version>
        </dependency>
```
? It doesn't seem to be produced in this project/repository.

**Comment by arjantijms** [comment]
> Where one can find [...]

That's a good question, at some point it really existed at some location. I'll see if I can find out where it went.

**Comment by pzygielo** [comment]
> ```xml
> <artifactId>glassfish-javatest-install</artifactId>
> ```
I've found reference in
- #23692

It (g-j-i) exists in https://github.com/eclipse-ee4j/glassfish/commit/204d3af3dcd720cca188d82bf26dd719773d41fd and disappears in #23696.

**Pull request closed without merging**
