### PR TITLE
Remove export of org.glassfish.flashlight from monitoring-core

### PR DESCRIPTION
**Pull request by Cousjava**
Possible fix for #23191. This is an alternative to #23262.

### CODE REVIEW

**Comment by scottmarlow** [comment]
I don't know the internals but should org.glassfish.flashlight.impl also be included?  Was the `org.glassfish.flashlight` reference expected to include the `flashlight.impl` classes or are those classes not needed here?

```
jar tf modules/monitoring-core.jar | grep org.glassfish.flashlight
org/glassfish/flashlight/
org/glassfish/flashlight/statistics/
org/glassfish/flashlight/statistics/impl/
org/glassfish/flashlight/statistics/factory/
org/glassfish/flashlight/datatree/
org/glassfish/flashlight/datatree/impl/
org/glassfish/flashlight/datatree/factory/
org/glassfish/flashlight/annotations/
org/glassfish/flashlight/impl/
org/glassfish/flashlight/statistics/impl/AverageImpl.class
org/glassfish/flashlight/statistics/impl/TimeStatsNanosImpl.class
org/glassfish/flashlight/statistics/impl/TimeStatsAbstractImpl$ThreadLocalTimeStatData.class
org/glassfish/flashlight/statistics/impl/TimeStatsAbstractImpl$TimeStatData.class
org/glassfish/flashlight/statistics/impl/TimeStatsAbstractImpl$1.class
org/glassfish/flashlight/statistics/impl/TimeStatsAbstractImpl.class
org/glassfish/flashlight/statistics/impl/TimeStatsMillisImpl.class
org/glassfish/flashlight/statistics/impl/CounterImpl.class
org/glassfish/flashlight/statistics/Average.class
org/glassfish/flashlight/statistics/TimeStats.class
org/glassfish/flashlight/statistics/TimeStatsNanos.class
org/glassfish/flashlight/statistics/factory/AverageFactory.class
org/glassfish/flashlight/statistics/factory/CounterFactory.class
org/glassfish/flashlight/statistics/factory/TimeStatsFactory.class
org/glassfish/flashlight/statistics/Counter.class
org/glassfish/flashlight/statistics/TimeStatsMillis.class
org/glassfish/flashlight/datatree/impl/AbstractTreeNode.class
org/glassfish/flashlight/datatree/impl/TreeNodeImpl.class
org/glassfish/flashlight/datatree/impl/MethodInvokerImpl.class
org/glassfish/flashlight/datatree/factory/MonitoringRuntimeDataRegistryFactory.class
org/glassfish/flashlight/datatree/factory/TreeNodeFactory.class
org/glassfish/flashlight/annotations/Monitorable.class
org/glassfish/flashlight/impl/MonitoringRuntimeDataRegistryImpl.class
```

**Comment by scottmarlow** [comment]
@smillidge Do you know if the org.glassfish.flashlight.impl.MonitoringRuntimeDataRegistryImpl class needs to be included in monitoring-core?  

Or does including org.glassfish.flashlight.impl.MonitoringRuntimeDataRegistryImpl cause the failure?  Perhaps that was causing the failure before when it was included via the (removed by this pull request) `org.glassfish.flashlight` import.

**Comment by scottmarlow** [comment]
FYI, test run https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-scottmarlow/job/darranl-unauthorized_status_code/2/testReport/ is still running but looking good so far.  This test run is using the GlassFish built with this change.

**Review by scottmarlow — APPROVED** [review]
If https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-scottmarlow/job/darranl-unauthorized_status_code/2/testReport/ completes with zero failures, I would definitely merge this change.

In general, this change looks good to me.

**Review by scottmarlow — APPROVED** [review]

**Review by smillidge — APPROVED** [review]

**Pull request merged**
