### PR TITLE
Remove explicit osgi.bundle for monitoring-core

### PR DESCRIPTION
**Pull request by Cousjava**
Possible fix for #23191
As a result OSGi manifest will be autogenerated using the felix plugin.

### CODE REVIEW

**Comment by scottmarlow** [comment]
@Cousjava I am sorry to say that I get the same failure when starting GlassFish (locally) with this change (after building your branch):
`glassfish/bin/asadmin start-domain  --verbose 2>&1 | tee /tmp/glassfish.txt` produces the `java.lang.NoClassDefFoundError: Lorg/glassfish/flashlight/MonitoringRuntimeDataRegistry;` still :(

[glassfish.txt](https://github.com/eclipse-ee4j/glassfish/files/5447200/glassfish.txt)

**Comment by pzygielo** [comment]
I've built locally, always with clean workspace (`git clean -fdx`), and:
  - current master 1b78bbeba 
    - I DO get `NoClassDefFoundError: Lorg/glassfish/flashlight/MonitoringRuntimeDataRegistry;` with zip produced in this build on `start-domain`
    - `stop-domain` reports `CLI306: Warning - The server located at /tmp/glassfish6/glassfish/domains/domain1 is not running. Command stop-domain executed successfully.` (as ~expected)
  - proposed 9761fd7c2
    - I DO NOT get any exception/error, esp. `NoClassDefFoundError`
    - domain is started and `stop-domain` stops it.

So this fix seems to work for me, :confused: 

[gf.log](https://github.com/eclipse-ee4j/glassfish/files/5447598/gf.log)

**Comment by scottmarlow** [comment]
I haven't tried `git clean -fdx` before building GlassFish, trying that now.

**Comment by scottmarlow** [comment]
The tip about `git clean -fdx` worked for me (also added alias `"gfbuild=git clean -fdx;mvn -Pstaging install"` to ~/.bashrc).

Thanks @pzygielo 

Also thanks @Cousjava for this change!  I will have to test more I think.

**Comment by pzygielo** [comment]
Just a reminder - `git clean` deletes much more files than `mvn clean` - so please remember that it will delete all non-versioned files (for example IDEA project or similar) - thus use your alias with care.
Safer would be `mvn clean install....` perhaps.

**Comment by scottmarlow** [comment]
Where does the monitoring-core osgi.bundle get generated?  I would like to compare the generate osgi.bundle to the deleted osgi.bundle.

**Comment by pzygielo** [comment]
I do not understand why it didn't break for 5.1, but (generated) manifests of `monitoring-core.jar`s (current master <-> this PR) differ about such:

```diff
--- nucleus/admin/monitor/target/classes/META-INF/MANIFEST.MF	2020-10-28 09:50:07.660425866 +0100
+++ nucleus/admin/monitor/target/classes/META-INF/MANIFEST.MF	2020-10-28 10:46:04.750994974 +0100
@@ -9,9 +9,9 @@
 Archiver-Version: Plexus Archiver
 
 Bundle-ManifestVersion: 2
 
 Bundle-DocURL: https://www.eclipse.org
@@ -68,18 +68,18 @@
  pfl-tf-tools.jar
  logging-annotation-processor.jar
 
 Import-Package:
- com.sun.enterprise.admin.monitor.jndi;version="[6.0,7)",
+ com.sun.enterprise.admin.monitor.jndi,
  com.sun.enterprise.config.serverbeans;version="[6.0,7)",
  com.sun.enterprise.module;version="[3.0,4)",
  com.sun.enterprise.util;version="[6.0,7)",
  com.sun.enterprise.util.i18n;version="[6.0,7)",
  jakarta.inject;version="[2.0,3)",
  javax.management,
  javax.naming,
- org.glassfish.admin.monitor;version="[6.0,7)",
- org.glassfish.admin.monitor.cli;version="[6.0,7)",
+ org.glassfish.admin.monitor,
+ org.glassfish.admin.monitor.cli,
  org.glassfish.api;version="[6.0,7)",
  org.glassfish.api.admin;version="[6.0,7)",
  org.glassfish.api.event;version="[6.0,7)",
  org.glassfish.api.monitoring;version="[6.0,7)",
@@ -93,9 +93,9 @@
  org.glassfish.flashlight.client;version="[6.0,7)",
  org.glassfish.flashlight.datatree;version="[6.0,7)",
  org.glassfish.flashlight.impl.client;version="[6.0,7)",
  org.glassfish.flashlight.provider;version="[6.0,7)",
- org.glassfish.flashlight.statistics;version="[6.0,7)",
+ org.glassfish.flashlight.statistics,
  org.glassfish.gmbal;version="[4.0,5)",
  org.glassfish.hk2.api;version="[3.0,4)",
  org.glassfish.hk2.runlevel;version="[3.0,4)",
  org.glassfish.internal.api;version="[6.0,7)",
@@ -125,15 +125,19 @@
   uses:="org.glassfish.flashlight.statistics",
  org.glassfish.admin.monitor;
   version="6.0.0";
   uses:="com.sun.enterprise.module,com.sun.enterprise.util,jakarta.inject,javax.management,org.glassfish.api.event,org.glassfish.external.amx,org.glassfish.external.probe.provider,org.glassfish.flashlight,org.glassfish.flashlight.client,org.glassfish.flashlight.provider,org.glassfish.hk2.api,org.glassfish.hk2.runlevel,org.jvnet.hk2.annotations,org.jvnet.hk2.config",
+
  org.glassfish.admin.monitor.cli;
   version="6.0.0";
   uses:="com.sun.enterprise.config.serverbeans,org.glassfish.api,org.glassfish.api.admin,org.glassfish.config.support,org.glassfish.hk2.api,org.jvnet.hk2.annotations",
- com.sun.enterprise.admin.monitor.util;
-  version="6.0.0",
- org.glassfish.flashlight;
-  version="6.0.0"
+
+ org.glassfish.admin.monitor.jvm;
+  version="6.0.0";
+  uses:="org.glassfish.external.statistics,org.glassfish.gmbal,org.glassfish.hk2.api,org.glassfish.hk2.runlevel,org.jvnet.hk2.annotations",
+ org.glassfish.admin.monitor.jvm.statistics;
+  version="6.0.0";
+  uses:="org.glassfish.admin.monitor.cli,org.glassfish.api,org.glassfish.external.statistics,org.glassfish.hk2.api,org.jvnet.hk2.annotations"
 
 Bundle-Name: admin-monitoring
 
 Bundle-Version: 6.0.0.SNAPSHOT
```

**Comment by Cousjava** [comment]
The maven-bundle-plugin creates the `import-package` and `export-package` sections in the jar's manifest. If an osgi.bundle file is present it will use that, which overrides the defaults which the plugin will generate for the manifest which are based off looking in the source to see what packages are used and and are available to export.

**Comment by Cousjava** [comment]
I have also created an alternative fix at #23264 which just removes a single line from the osgi.bundle file.

**Comment by Cousjava** [comment]
#23264 merged instead

**Pull request closed without merging**
