### PR TITLE
Fixes issue 24868 Clean code: fix unlikely argument and remove some unused variables.

### PR DESCRIPTION
**Pull request by escay**
ManagedBeanManagerImpl and JdbcConnPoolAppStatsProvider need specific review.
I did not add a nullcheck for SimpleJndiName in JdbcConnPoolAppStatsProvider, since the constructor already validates it.

```
Unlikely argument type SimpleJndiName for remove(Object) on a Map<String,NamingObjectProxy>	ManagedBeanManagerImpl.java	/container-common/src/main/java/com/sun/enterprise/container/common/impl/managedbean	line 338	Java Problem
## Unlikely argument type for equals(): SimpleJndiName seems to be unrelated to String	JdbcConnPoolAppStatsProvider.java	/jdbc-runtime/src/main/java/org/glassfish/jdbc/pool/monitor	line 90	Java Problem
## Unlikely argument type for equals(): SimpleJndiName seems to be unrelated to String	JdbcConnPoolAppStatsProvider.java	/jdbc-runtime/src/main/java/org/glassfish/jdbc/pool/monitor	line 109	Java Problem
## Unlikely argument type for equals(): SimpleJndiName seems to be unrelated to String	JdbcConnPoolAppStatsProvider.java	/jdbc-runtime/src/main/java/org/glassfish/jdbc/pool/monitor	line 124	Java Problem
## Unlikely argument type for equals(): SimpleJndiName seems to be unrelated to String	JdbcConnPoolAppStatsProvider.java	/jdbc-runtime/src/main/java/org/glassfish/jdbc/pool/monitor	line 136	Java Problem
```

Full list of items is listed in issue #24868

### CODE REVIEW

**Comment by arjantijms** [comment]
Cool! There's 1 check style violation though:

```
11:51:54  [INFO] --- checkstyle:3.3.0:check (org.glassfish.main.admin-config-api-checkstyle) @ config-api ---
11:51:58  [INFO] There is 1 error reported by Checkstyle 10.12.4 with org/glassfish/qa/config/checkstyle/checkstyle.xml ruleset.
11:51:58  [ERROR] src/main/java/org/glassfish/config/support/DomainXml.java:[24,8] (imports) UnusedImports: Unused import - com.sun.enterprise.universal.i18n.LocalStringsImpl.
```

**Comment by escay** [comment]
Please discard this pull request. Used wrong author / comitter. Not sure how to fix this without creating a new branch on github.
I will have a look at the unused import as well.

**Comment by arjantijms** [comment]
Thanks!

Btw, before long we may consider doing (larger) refactoring in the 8.0 branch instead. Not sure when the turnover point should be though.

**Comment by dmatej** [comment]
> Thanks!
> 
> Btw, before long we may consider doing (larger) refactoring in the 8.0 branch instead. Not sure when the turnover point should be though.

I prefer refactoring on master, usually it is not so huge problem to merge it to 8. Once you start with these changes on 8 and also doing "temporary compromises", there would be no way back and very hard to find those "temporary" things.

**Pull request closed without merging**
