### PR TITLE
Add profiles to Faces TCK to run subsets

### PR DESCRIPTION
**Pull request by arjantijms**
This defines 2 main subsets:

* only old tests
* only new tests

Old can be divided into two further sets:

* old1
* old2

### CODE REVIEW

**Comment by dmatej** [comment]
Bit confusing what means old1 and what means old2 ... and new ... bad names? :-)

**Comment by dmatej** [comment]
I would have to go through tests, but I see they are separated by some `component/html` part. So perhaps `old-html-component` and `old-...`?

**Comment by arjantijms** [comment]
> but I see they are separated by some component/html part. So perhaps old-html-component and old-...?

That's the split for now, but maybe we can find better splits? The parts are still rather big.

**Comment by dmatej** [comment]
> > but I see they are separated by some component/html part. So perhaps old-html-component and old-...?
> 
> That's the split for now, but maybe we can find better splits? The parts are still rather big.

Those should have good names too, but now I will never know if I want `old1` or `old2` or `new`.

**Comment by arjantijms** [comment]
>  but now I will never know if I want old1 or old2 or new.

It's a bit like the other tests where we have "...group1", "...group2":

groups

**Comment by dmatej** [comment]
Yeah, but I call these an army of zombies, its 23 years old set of tests, btw I group will be "cured" before the end of the year! ;-)

**Pull request merged**
