### PR TITLE
Generate new default certificates

### PR DESCRIPTION
**Pull request by hussainnm**
The following commands were executed to generate the new keystore and truststore

```
keytool -keystore keystore.jks -storepass changeit -keypass changeit -genkeypair -alias s1as -keyalg RSA -keysize 4096 -startdate "2020/12/08 16:30:00" -validity 3650 -dname "CN=localhost,OU=GlassFish,O=Eclipse.org Foundation Inc,L=Ottawa,ST=Ontario,C=CA"
keytool -keystore keystore.jks -storepass changeit -keypass changeit -genkeypair -alias glassfish-instance -keyalg RSA -startdate "2020/12/08 16:30:00" -validity 3650 -dname "CN=localhost-instance,OU=GlassFish,O=Eclipse.org Foundation Inc,L=Ottawa,ST=Ontario,C=CA"
keytool -keystore keystore.jks -storepass changeit -keypass changeit -exportcert -alias s1as -file s1as.cer
keytool -keystore keystore.jks -storepass changeit -keypass changeit -exportcert -alias glassfish-instance -file glassfish-instance.cer
keytool -keystore cacerts.jks -storepass changeit -keypass changeit -importcert -noprompt -trustcacerts -file s1as.cer -alias s1as
keytool -keystore cacerts.jks -storepass changeit -keypass changeit -importcert -noprompt -trustcacerts -file glassfish-instance.cer -alias glassfish-instance
```

### CODE REVIEW

**Comment by hussainnm** [comment]
**Existing cert details:**
- sa1s has expired on Fri Jul 05 13:57:35 IST 2019
- glassfish-instance will expire on  Fri Dec 09 20:25:28 IST 2022

> Keystore type: jks
> Keystore provider: SUN
> 
> Your keystore contains 2 entries
> 
> Alias name: glassfish-instance
> Creation date: May 14, 2018
> Entry type: trustedCertEntry
> 
> Owner: CN=localhost-instance, OU=GlassFish, O=Oracle Corporation, L=Santa Clara, ST=California, C=US
> Issuer: CN=localhost-instance, OU=GlassFish, O=Oracle Corporation, L=Santa Clara, ST=California, C=US
> Serial number: 1c7ba1b4
> Valid from: Tue Dec 11 20:25:28 IST 2012 until: Fri Dec 09 20:25:28 IST 2022
> Certificate fingerprints:
>          MD5:  BE:5B:27:26:1E:98:7A:A8:49:9A:6D:CA:39:69:21:94
>          SHA1: EA:BB:0D:1C:08:A7:26:6B:CF:24:B5:9F:6C:D9:C7:69:BC:C0:C1:7D
>          SHA256: 90:8B:18:AE:E7:F9:63:9A:5E:EA:A6:98:69:6C:A8:DE:35:DC:54:C1:C9:E3:27:AA:63:ED:53:27:64:0C:DF:B4
> Signature algorithm name: SHA256withRSA
> Subject Public Key Algorithm: 2048-bit RSA key
> Version: 3
> 
> Extensions:
> 
> #1: ObjectId: 2.5.29.14 Criticality=false
> SubjectKeyIdentifier [
> KeyIdentifier [
> 0000: 60 DE 83 56 83 DF F2 D2   76 C5 5A A1 87 44 83 47  `..V....v.Z..D.G
> 0010: C7 5A 89 E7                                        .Z..
> ]
> ]
> 
> 
> 
> *******************************************
> *******************************************
> 
> 
> Alias name: s1as
> Creation date: May 14, 2018
> Entry type: trustedCertEntry
> 
> Owner: CN=localhost, OU=GlassFish, O=Sun Microsystems, L=Santa Clara, ST=California, C=US
> Issuer: CN=localhost, OU=GlassFish, O=Sun Microsystems, L=Santa Clara, ST=California, C=US
> Serial number: 4a5306f7
> Valid from: Tue Jul 07 13:57:35 IST 2009 until: Fri Jul 05 13:57:35 IST 2019
> Certificate fingerprints:
>          MD5:  44:3D:1D:1A:33:97:42:D0:05:C5:84:4D:AC:4B:C0:D4
>          SHA1: 3A:C7:17:C1:95:EA:80:EE:22:D5:89:4E:99:8C:9C:D3:E4:D1:AB:BD
>          SHA256: E4:1E:67:03:38:48:8D:13:64:E4:89:63:4E:EB:46:8E:A2:BE:E5:41:D3:5B:B0:69:FE:6E:C2:AF:A2:26:E2:77
> Signature algorithm name: SHA1withRSA
> Subject Public Key Algorithm: 1024-bit RSA key
> Version: 3
> 
> Extensions:
> 
> #1: ObjectId: 2.5.29.14 Criticality=false
> SubjectKeyIdentifier [
> KeyIdentifier [
> 0000: 8F FB 7A 0A BF 38 54 A6   0D 9D CC 28 F8 7A B2 25  ..z..8T....(.z.%
> 0010: F2 F8 A1 99                                        ....
> ]
> ]
> 
> 
> 
> *******************************************
> *******************************************
> 
>

**Comment by hussainnm** [comment]
**New cert details**
- s1as will expire on Fri Dec 06 16:16:16 IST 2030
- glassfish-instance will expire on Fri Dec 06 16:16:16 IST 2030

> Keystore type: jks
> Keystore provider: SUN
> 
> Your keystore contains 2 entries
> 
> Alias name: glassfish-instance
> Creation date: Dec 30, 2020
> Entry type: trustedCertEntry
> 
> Owner: CN=localhost-instance, OU=GlassFish, O=Eclipse.org Foundation Inc, L=Ottawa, ST=Ontario, C=CA
> Issuer: CN=localhost-instance, OU=GlassFish, O=Eclipse.org Foundation Inc, L=Ottawa, ST=Ontario, C=CA
> Serial number: 68ff7ca9
> Valid from: Tue Dec 08 16:16:16 IST 2020 until: Fri Dec 06 16:16:16 IST 2030
> Certificate fingerprints:
>          MD5:  98:A4:AB:1E:A6:45:72:1D:5E:94:B4:62:DF:2A:0E:4A
>          SHA1: 9E:84:F5:AB:99:2E:71:D2:EA:DF:DA:87:1F:E3:6D:05:93:7E:78:C5
>          SHA256: BE:FB:FA:60:D5:F4:A0:3F:4A:76:76:5C:7B:D7:DC:22:1E:D3:BB:97:2C:A4:FC:F4:B0:E6:22:B9:67:50:D8:2F
> Signature algorithm name: SHA256withRSA
> Subject Public Key Algorithm: 2048-bit RSA key
> Version: 3
> 
> Extensions:
> 
> #1: ObjectId: 2.5.29.14 Criticality=false
> SubjectKeyIdentifier [
> KeyIdentifier [
> 0000: CB B3 75 73 F4 3B FA 29   33 9C A5 89 D5 C4 23 F8  ..us.;.)3.....#.
> 0010: 6E A7 7F 6C                                        n..l
> ]
> ]
> 
> 
> 
> *******************************************
> *******************************************
> 
> 
> Alias name: s1as
> Creation date: Dec 30, 2020
> Entry type: trustedCertEntry
> 
> Owner: CN=localhost, OU=GlassFish, O=Eclipse.org Foundation Inc, L=Ottawa, ST=Ontario, C=CA
> Issuer: CN=localhost, OU=GlassFish, O=Eclipse.org Foundation Inc, L=Ottawa, ST=Ontario, C=CA
> Serial number: 196dc464
> Valid from: Tue Dec 08 16:16:16 IST 2020 until: Fri Dec 06 16:16:16 IST 2030
> Certificate fingerprints:
>          MD5:  E6:B5:91:4D:DF:C8:61:B1:C1:80:FD:73:7B:73:AE:7A
>          SHA1: C4:8C:1B:32:4E:C2:CC:61:DF:C4:E1:40:6B:C2:A0:96:7F:42:F0:7D
>          SHA256: DA:98:0E:4E:01:21:BF:0C:20:17:37:B6:77:95:B9:08:59:32:11:4F:E6:E7:B6:1F:E1:F5:9C:C9:09:1E:25:FD
> Signature algorithm name: SHA256withRSA
> Subject Public Key Algorithm: 4096-bit RSA key
> Version: 3
> 
> Extensions:
> 
> #1: ObjectId: 2.5.29.14 Criticality=false
> SubjectKeyIdentifier [
> KeyIdentifier [
> 0000: 99 AA 19 F2 89 83 F3 F3   CB 92 FD B4 C9 09 B1 40  ...............@
> 0010: B1 1A 4F 77                                        ..Ow
> ]
> ]
> 
> 
> 
> *******************************************
> *******************************************
> 
> 
>

**Comment by smillidge** [comment]
I thought the certs were generated during the build?

**Comment by hussainnm** [comment]
When the domain is created during the build process, it generates a new certificate. These are static certificates that are used in glassfish-embedded server.

**Review by smillidge — APPROVED** [review]

**Pull request merged**
