### PR TITLE
Fixes #22927 removed Jakarta Management API from GlassFish 6.0.0

### LINKED ISSUE #22927: Remove Pruned API Jakarta Management

### PR DESCRIPTION
**Pull request by smillidge**
Passes Quick Look Tests
Signed-off-by: smillidge <steve.millidge@payara.fish>

### CODE REVIEW

**Review by hs536 — APPROVED** [review]
In the near future we will need to modify the following devtests, part of which use mejb:
- ejb_group_3
- cdi_all

**Review by hs536 — CHANGES_REQUESTED** [review]
3 more files need to be modified for the build to succeed.
```
# git branch
* 22927
# find . -name "pom.xml" |xargs grep "mejb"
./appserver/extras/embedded/all/pom.xml:            <artifactId>mejb-frag</artifactId>
./appserver/extras/embedded/shell/glassfish-embedded-static-shell/pom.xml:            <artifactId>mejb-frag</artifactId>
./appserver/featuresets/glassfish/pom.xml:            <artifactId>mejb</artifactId>
```

**Comment by smillidge** [comment]
@hs536 I've corrected the build. I hate it when my local maven repo has the snapshot artifact so I don't catch build errors.

**Review by hs536 — APPROVED** [review]
I don't know why the build failed in Eclipse Jenkins, but it did build correctly in my local environment, so I aprove it. :)

**Comment by arjantijms** [comment]
Resolved merge conflict, will merge this in now.

**Pull request merged**
