### PR TITLE
New infra - Volume for jenkins home

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: arjantijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Comment by arjantijms** [comment]
@romain-grecourt This will still not pass the tests, but it's again one step closer.

**Comment by romain-grecourt** [comment]
Can you help me understand why would we need an empty-dir volume for /home/jenkins ?

**Comment by arjantijms** [comment]
@romain-grecourt It's supposedly due to "recent changes in the Jenkins Kubernetes plugin"

See https://wiki.eclipse.org/Jenkins#In_a_custom_container_the_build_can.27t_write_to_.2Fhome.2Fjenkins.2C_what_do_I_need_to_do.3F

**Comment by romain-grecourt** [comment]
OK, thanks for the pointer.

**Review by romain-grecourt — APPROVED** [review]

**Pull request merged**
