### PR TITLE
Integrate ha-api 3.1.12

### PR DESCRIPTION
**Pull request by vinayvishal**

### CODE REVIEW

**Comment by vinayvishal** [comment]
I am seeing quite a few quicklook test failures as soon as I integrate this particular version. All these failures are due to `NoClassDefFoundError` for  class `javax/validation/Payload`. This class is present in my maven repository in following two jars. 

Snippet from the error log:

```java
   [testng] Caused by: java.lang.NoClassDefFoundError: javax/validation/Payload
   [testng]     at java.lang.ClassLoader.defineClass1(Native Method)
   [testng]     at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
   [testng]     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
   [testng]     at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
   [testng]     at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
   [testng]     at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
   [testng]     at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
   [testng]     at org.glassfish.hk2.utilities.reflection.internal.ClassReflectionHelperUtilities$3.run(ClassReflectionHelperUtilities.java:85)
   [testng]     at org.glassfish.hk2.utilities.reflection.internal.ClassReflectionHelperUtilities$3.run(ClassReflectionHelperUtilities.java:81)
   [testng]     at java.security.AccessController.doPrivileged(Native Method)
   [testng]     at org.glassfish.hk2.utilities.reflection.internal.ClassReflectionHelperUtilities.secureGetDeclaredMethods(ClassReflectionHelperUtilities.java:81)
   [testng]     at org.glassfish.hk2.utilities.reflection.internal.ClassReflectionHelperUtilities.getDeclaredMethodWrappers(ClassReflectionHelperUtilities.java:110)
   [testng]     at org.glassfish.hk2.utilities.reflection.internal.ClassReflectionHelperUtilities.getAllMethodWrappers(ClassReflectionHelperUtilities.java:169)
   [testng]     at org.glassfish.hk2.utilities.reflection.internal.ClassReflectionHelperImpl$3.compute(ClassReflectionHelperImpl.java:61)
   [testng]     at org.glassfish.hk2.utilities.reflection.internal.ClassReflectionHelperImpl$3.compute(ClassReflectionHelperImpl.java:57)
   [testng]     at org.glassfish.hk2.utilities.cache.LRUHybridCache$OriginThreadAwareFuture$1.call(LRUHybridCache.java:92)
   [testng]     at org.glassfish.hk2.utilities.cache.LRUHybridCache$OriginThreadAwareFuture$1.call(LRUHybridCache.java:88)
   [testng]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   [testng]     at org.glassfish.hk2.utilities.cache.LRUHybridCache$OriginThreadAwareFuture.run(LRUHybridCache.java:150)
   [testng]     at org.glassfish.hk2.utilities.cache.LRUHybridCache.compute(LRUHybridCache.java:269)
   [testng]     ... 69 more
   [testng] Caused by: java.lang.ClassNotFoundException: javax.validation.Payload
   [testng]     at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
   [testng]     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
   [testng]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
   [testng]     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
   [testng]     ... 97 more
```

```java
   [testng] Caused by: java.lang.ClassNotFoundException: javax.validation.Payload
   [testng]     at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
   [testng]     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
   [testng]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
   [testng]     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
   [testng]     ... 97 more
   [testng] MultiException stack 4 of 4
   [testng] java.lang.IllegalArgumentException: Errors were discovered while reifying SystemDescriptor(
   [testng]     implementation=com.sun.enterprise.v3.server.ServerContextImpl
   [testng]     contracts={com.sun.enterprise.v3.server.ServerContextImpl,org.glassfish.internal.api.ServerContext}
   [testng]     scope=javax.inject.Singleton
   [testng]     qualifiers={}
   [testng]     descriptorType=CLASS
   [testng]     descriptorVisibility=NORMAL
   [testng]     metadata=
   [testng]     rank=0
   [testng]     loader=org.glassfish.hk2.bootstrap.impl.Hk2LoaderPopulatorPostProcessor$1@7ceb3185
   [testng]     proxiable=null
   [testng]     proxyForSameScope=null
   [testng]     analysisName=null
   [testng]     id=280
   [testng]     locatorId=0
   [testng]     identityHashCode=1131184547
   [testng]     reified=false)
   [testng]     at org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:681)
   [testng]     at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:441)
   [testng]     at org.jvnet.hk2.internal.ServiceLocatorImpl.narrow(ServiceLocatorImpl.java:2287)
   [testng]     at org.jvnet.hk2.internal.ServiceLocatorImpl.igdCacheCompute(ServiceLocatorImpl.java:1163)
   [testng]     at org.jvnet.hk2.internal.ServiceLocatorImpl.access$400(ServiceLocatorImpl.java:105)
   [testng]     at org.jvnet.hk2.internal.ServiceLocatorImpl$8.compute(ServiceLocatorImpl.java:1157)
   [testng]     at org.jvnet.hk2.internal.ServiceLocatorImpl$8.compute(ServiceLocatorImpl.java:1154)
   [testng]     at org.glassfish.hk2.utilities.cache.internal.WeakCARCacheImpl.compute(WeakCARCacheImpl.java:105)
   [testng]     at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetDescriptor(ServiceLocatorImpl.java:1237)
   [testng]     at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:750)
   [testng]     at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.jav
```
Between version 3.1.11 and 3.1.12, there is hardly any change. I do see that following dependency has been removed from hk2-maven-plugin. Not sure if it has got to do anything with it.

```bash
<dependency>
     <groupId>com.sun</groupId>
     <artifactId>tools</artifactId>
     <version>${hk2.version}</version>
     <scope>system</scope>
     <systemPath>${java.home}/../lib/tools.jar</systemPath>
</dependency>
```

I will have to try out few things so that I get a clean Quicklook run. We need to keep this PR on hold till then. Meanwhile any pointers would help.

**Comment by m0mus** [comment]
Make sure that you have BeanValidation on class path.

**Comment by romain-grecourt** [comment]
@m0mus This is OSGi, making sure something is on class-path is dark science lol :)

**Review by m0mus — APPROVED** [review]
LGTM

**Pull request merged**
