### PR TITLE
Fix link to CTS

### PR DESCRIPTION
**Pull request by OndroMih**

### CODE REVIEW

**Review by smillidge — APPROVED** [review]

**Comment by bshannon** [comment]
Would everyone please read [this](https://github.com/eclipse-ee4j/glassfish/blob/master/docs/README.md) and then try again?  Thanks.

**Comment by smillidge** [comment]
OK will revert see https://github.com/eclipse-ee4j/glassfish/pull/22949 needs review.

Can these instructions be added somewhere more visible

**Comment by bshannon** [comment]
> Can these instructions be added somewhere more visible

Sure.  Where did you look for them before making this change?

**Comment by kazumura** [comment]
One of the ideas is to put 'pull_request_template' on .github,
and describe such as "do not create PR for gh-pages".
Or just to write the URL of the instruction page in the template.

**Comment by bshannon** [comment]
Great!  If you know how to do that, please do it!

**Pull request merged**
