### PR TITLE
move to jakarta.* in default-web.xml

### PR DESCRIPTION
**Pull request by lukasj**

### CODE REVIEW

**Review by bshannon — APPROVED** [review]
Who would've guessed the jar file names are here too!  :-)

Thanks for fixing!

**Comment by lukasj** [comment]
@bshannon I'm only thinking whether ie jakarta.json.jar or jakarta.json.bind-api.jar (maybe few others) shouldn't be added here as well. Question for someone responsible for JSP perhaps? Do you know who to ask? In any case, I think that additions can wait to post RC2...

**Comment by bshannon** [comment]
I have no idea how this list is used so I don't know what should or shouldn't be added to it.
Ask Shing Wai Chan.

**Comment by lukasj** [comment]
Only limited set of jars is supposed to be used here for performance reasons, so updates are OK, additions are not

**Pull request merged**
