### PR TITLE
Update to Jakarta Rest 2.1.6.

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: arjantijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Review by bshannon — APPROVED** [review]

**Comment by bshannon** [comment]
I've tried many times and the continuous integration tests just won't pass.
It looks like there may be a real problem here.

Looking at the failure for the ejb-web-all test, I see this in the server log:

```
MultiException stack 1 of 2
com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [org.glassfish.main.admin.rest-service [170]], State = [NEW]
    at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:193)
    at org.jvnet.hk2.osgiadapter.OsgiPopulatorPostProcessor$1.loadClass(OsgiPopulatorPostProcessor.java:54)
    at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2225)
    at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:436)
    at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:455)
    at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.isWouldBlockRightNow(CurrentTaskFuture.java:1170)
    at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1206)
    at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.osgi.framework.BundleException: Unable to resolve org.glassfish.main.admin.rest-service [170](R 170.0): missing requirement [org.glassfish.main.admin.rest-service [170](R 170.0)] osgi.wiring.package; (&(osgi.wiring.package=javax.ws.rs.client)(version>=2.1.0)(!(version>=3.0.0))) [caused by: Unable to resolve jakarta.ws.rs-api [206](R 206.0): missing requirement [jakarta.ws.rs-api [206](R 206.0)] osgi.wiring.package; (&(osgi.wiring.package=javax.xml.bind.annotation)(version>=2.3.0)(!(version>=3.0.0)))] Unresolved requirements: [[org.glassfish.main.admin.rest-service [170](R 170.0)] osgi.wiring.package; (&(osgi.wiring.package=javax.ws.rs.client)(version>=2.1.0)(!(version>=3.0.0)))]
    at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4149)
    at org.apache.felix.framework.Felix.startBundle(Felix.java:2119)
    at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
    at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:185)
    ... 10 more
MultiException stack 2 of 2
java.lang.IllegalStateException: Could not load descriptor SystemDescriptor(
implementation=org.glassfish.admin.rest.adapter.JerseyContainerCommandService
contracts={org.glassfish.admin.rest.adapter.JerseyContainerCommandService}
    scope=org.glassfish.hk2.runlevel.RunLevel
    qualifiers={}
    descriptorType=CLASS
    descriptorVisibility=NORMAL
metadata=runLevelValue={10},Bundle-SymbolicName={org.glassfish.main.admin.rest-service},Bundle-Version={5.1.0.SNAPSHOT}
    rank=0
loader=OsgiPopulatorPostProcessor.HK2Loader(OSGiModuleImpl:: Bundle = [org.glassfish.main.admin.rest-service [170]], State = [NEW],1209342451)
    proxiable=null
    proxyForSameScope=null
    analysisName=null
    id=686
    locatorId=0
    identityHashCode=1640921935
    reified=false)
    at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2234)
    at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:436)
    at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:455)
    at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.isWouldBlockRightNow(CurrentTaskFuture.java:1170)
    at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1206)
    at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
]] 
```

That suggests some sort of OSGi error related to this change.

**Comment by bshannon** [comment]
@romain-grecourt dug into this deeper and here's what he figured out...

The latest version of the JAX-RS API jar file was built with JDK 12.  JDK 12 doesn't include JAXB
so the build profile includes the separate version of JAXB, which then appears in the OSGi
dependencies with a dependency on that particular version of JAXB.  Since that particular version
of JAXB isn't available in the runtime when these tests run (because they run on JDK 8), the OSGi
dependency analysis fails and the new JAX-RS API jar file can't be loaded.

The fix is to either build with an older version of the JDK so that the explicit dependency on a
particular version of JAXB isn't included, or do something so that the OSGi dependency on JAXB
does not include a version number so that it can be satisfied by the version of JAXB in JDK 8
(which is what the tests use, and what GlassFish supports).  The previous version of the API
jar file was built with JDK 9, which didn't introduce this problem.

@arjantijms can you take care of this?

**Comment by arjantijms** [comment]
>Since that particular version
of JAXB isn't available in the runtime when these tests run (because they run on JDK 8), the OSGi
dependency analysis fails and the new JAX-RS API jar file can't be loaded.

Indeed. The Felix output is a little hard to read (long time TODO item for me to supply a patch for a pretty printer), but it's this one:

> (&(osgi.wiring.package=javax.xml.bind.annotation)(version>=2.3.0)(!(version>=3.0.0

> @arjantijms can you take care of this?

I think this should be doable. I'll try rebuilding and re-staging first then.

**Comment by smillidge** [comment]
Closing as we will need to pull in the Jakarta EE 9 version into master

**Pull request closed without merging**
