### PR TITLE
Remove unused constructors

### PR DESCRIPTION
**Pull request by pzygielo**
Signed-off-by: Piotrek Zygielo <piotr@zygielo.pl>

### CODE REVIEW

**Comment by smillidge** [comment]
Can you detail what testing was carried out against the PR?

**Comment by pzygielo** [comment]
> Can you detail what testing was carried out against the PR?

Apart from checking GF being buildable (ie. no references to removed Ctors in project) I performed following manual steps:

1. I built `appserver/extras/embedded/all/pom.xml`
1. I ran [test project](https://github.com/pzrep/jca-config-property/tree/db70ea932b86dd5ce48b74ab208aea9dcf8b84bd) against local SNAPSHOT built above
which in my eyes proved that both - config-parameters from deployment descriptor and `@`ConfigParameters from code were still recognized.
Change [obviously] does not solve #22747 [yet], so my test was still failing, but RAR was successfully deployed.

**Comment by bshannon** [comment]
I'm not clear on what problem is being solved by removing these constructors.

ConnectorConfigProperty extends EnvironmentProperty, and EnvironmentProperty
has these kinds of constructors.  Why remove them here and not there?  Why were
they added to begin with?

**Comment by pzygielo** [comment]
> ConnectorConfigProperty extends EnvironmentProperty, and EnvironmentProperty
> has these kinds of constructors. 

Constructors are not inherited so having in super-class handful of them does not mean sub-class has to provide similar set nor is excused for doing so.

> Why remove them here and not there?

Good idea. Will check if possible to do so.

> I'm not clear on what problem is being solved by removing these constructors.

It's the code that never gets executed (not even in UTs), but has to be maintained, compiled, kept in jar, etc.. and discussed about like here.

I focused on ConnectorConfigProperty only, as for me it seems there is the place to fix #22747.
Without those 3 Ctors fix is a bit simpler. (Should they be missing already I'd save some time on my investigation).

> Why were they added to begin with?

Looks like they [were always with us](https://github.com/javaee/glassfish/commit/962f22930c9#diff-27e601c417bbd77a361e2a23ba5a220f) (brand new file introduced in Jul 2009).

**Comment by pzygielo** [comment]
>  Why remove them here and not there?

Cannot do, as 

this

https://github.com/eclipse-ee4j/glassfish/blob/eac66d65e6a8eccedaaf40fac0e514d12c71e314/appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/EnvironmentProperty.java#L77

is used (at least) here

https://github.com/eclipse-ee4j/glassfish/blob/eac66d65e6a8eccedaaf40fac0e514d12c71e314/appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/MessageDestinationReferenceDescriptor.java#L61



this

https://github.com/eclipse-ee4j/glassfish/blob/eac66d65e6a8eccedaaf40fac0e514d12c71e314/appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/EnvironmentProperty.java#L95

is used (at least) here

https://github.com/eclipse-ee4j/glassfish/blob/eac66d65e6a8eccedaaf40fac0e514d12c71e314/appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/ResourceReferenceDescriptor.java#L105




this 

https://github.com/eclipse-ee4j/glassfish/blob/eac66d65e6a8eccedaaf40fac0e514d12c71e314/appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/EnvironmentProperty.java#L105

is used (at least) here

https://github.com/eclipse-ee4j/glassfish/blob/eac66d65e6a8eccedaaf40fac0e514d12c71e314/appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/ConnectorConfigProperty.java#L69

**Comment by bshannon** [comment]
Since we no longer have people who understand this code intimately, I'm a bit nervous
about making changes that are not necessary.  And with other subclasses of
EnvironmentProperty also providing similar constructors, I don't really see the
motivation to remove them here.  Maybe I would change my mind if the fix for #22747 were significantly more complicated because of these constructors.

@smillidge what do you think?

**Comment by bshannon** [comment]
Still waiting for comments from @smillidge before approving all your other PRs that
remove all the "unused" constructors.

And I'd like to see the fix for #22747 that justifies these changes.

**Comment by pzygielo** [comment]
> And I'd like to see the fix for #22747 that justifies these changes.

[My fix](https://github.com/pzygielo/glassfish/commit/23615c7572e49ec489c6d8cc6587e0e3da7d40ec) doesn't do that. If taken - 22748 would save only one call.

These removals, IMO, are due to their own bad smell alone.

(It's clear, that it is not pull _demand_ :grin:)

**Comment by smillidge** [comment]
I'm happy to remove dead code

**Comment by bshannon** [comment]
@smillidge if you're sure all of this is dead code, please approve and merge these PRs.  Thanks.

**Comment by bshannon** [comment]
@smillidge poke

**Review by smillidge — APPROVED** [review]

**Comment by smillidge** [comment]
Jenkins is green so I will merge

**Pull request merged**
