### PR TITLE
Integrate Metro and Jersey 3.0.0-M1

### LINKED ISSUE #22897: Incorporate JWS 3.0.0 into GlassFish 6.0

### LINKED ISSUE #22904: Incorporate Jakarta Soap API 2.0.0 into GlassFish 6.0.0
Also requires integration of a jakarta version of Metro

### LINKED ISSUE #22912: Incorporate Jakarta XML Binding 3.0.0 into GlassFish 6.0

### LINKED ISSUE #22916: Incorporate Jakarta XML Web Services 3.0.0 into GlassFish 6.0
Requires integration of a jakarta namespace version of metro

### PR DESCRIPTION
**Pull request by lukasj**
Fixes: #22912, #22897, #22904 and #22916

with this change ~~and my - at this point local only - [changes](https://github.com/eclipse-ee4j/metro-wsit/pull/74) in metro,~~ glassfish builds with Jakarta XML Binding and XML Web services related APIs

few notes:
* there is no "jakarta" xjc maven plugin (and I do not plan to provide one), so what used to be generated by various maven-xjc plugins, is now being generated by xjc ant task (with one exception till [the bug](https://github.com/eclipse-ee4j/jaxb-ri/issues/1436) in the task is fixed)
* metro as such already requires "jakarta.servlet" packages, so to make jsr109-impl module compilable, I had to use both - javax.servlet:javax.servlet-api:4.0.1 as well as jakarta.servlet:jakarta.servlet-api:5.0.0-M1 - for the build
* I made all required jakarta apis not included in this PR, like jakarta.ejb,..., optional in webservices-osgi.jar assuming that as long as a deployment does not contain web service, jsr-109 and webservices-osgi modules will be still able to start and thus not blocking deployment for simple apps (untested)

Questions:
* ~~do you want me to relocate xml-binding and webservices related APIs out from the current 'endorsed' folder?~~ **DONE**
* I may also need to cover #22898 (persistence) as part of this ~~and maybe also #22899 (common annotations)~~ (#22899 is **DONE**) . Or is someone already working on it?

### CODE REVIEW

**Comment by lukasj** [comment]
...and with Jakarta REST 3.0.0-M1 and Jersey 3.0.0-M1 GlassFish 6 runs again.

Note that I had to disable/remove some pieces from the build (see [jersey bug](https://github.com/eclipse-ee4j/jersey/issues/4454) + also jersey.jackson support since that requires javax.xml.bind which is not available any more (well, could be probably taken from JDK 8 if available but I just don't want to mess with that as part of this).

If disabled path is executed, then SEVERE message is printed to server log, so one can get to it later (look for 'log(Level.SEVERE' string in the diff)

**Comment by arjantijms** [comment]
> metro as such already requires "jakarta.servlet" packages, so to make jsr109-impl module compilable, I had to use both - javax.servlet:javax.servlet-api:4.0.1 as well as jakarta.servlet:jakarta.servlet-api:5.0.0-M1 - for the build

Yes, that's fine for now. It's very hard to get everything perfect as there are so many dependencies. We'll fix this where needed after everything has been merged in.

> I may also need to cover #22898 (persistence) as part of this and maybe also #22899 (common annotations) (#22899 is DONE) . Or is someone already working on it?

Shall we just do that in a next PR? Otherwise we just get bigger and bigger PRs that stay open for longer, as everyone is waiting on each other. We had agreed before in the GF project that temporarily tests can break and the only real requirement is that it compiles.

**Review by arjantijms — APPROVED** [review]

**Comment by arjantijms** [comment]
Spot checked the PR and LGTM, but in no way did I check everything.

**Comment by lukasj** [comment]
@arjantijms OK, so this is all I can do right now. While this covers also Jakarta Annotations, this is the piece currently causing  server startup to fail -  a change in osgi.properties helps to get a bit further but it is not perfect.

If you feel blocked, feel free to rebase on top of this or merge this, if you don't mind having dependency on metro-snapshot for few days before I finish M1. M2 of Jersey fixing the problem with Jakarta Annotations should be available later this week too.

**Comment by lukasj** [comment]
to sum up what is pending here:

* removal of snapshot repo definitions
* revert the change in osgi.properties
* jersey 3.0.0-M1 -> 3.0.0-M2
* metro 3.0.0-SNAPSHOT -> 3.0.0-M1

whether this happens as part of this or in another PR later this week/early next week, if this gets merged, is not that important from my point of view

**Comment by arjantijms** [comment]
> If you feel blocked, feel free to rebase on top of this or merge this

Thanks! I'll merge this then so we can keep making progress and reduce the chances of conflicts. Looking forward to your next PR then!

**Pull request merged**
