### PR TITLE
#22874 - Moved master to 6.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by arjantijms**
#22874 Updated version in pom files to 6.0.0-SNAPSHOT and properties for glassfish-version.properties to 6 and 0. Updated copyright to 2020 in files touched.

Signed-off-by: arjantijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Review by bshannon — APPROVED** [review]
I'm not going to review every one of these 488 pom.xml files but in general it looks good to me.
So, assuming that you...
- used an appropriate tool to automate updating the pom.xml files,
- coordinated with Steve about making this version change *now*,
- updated any README and related files, especially on the web site,
it all looks good to me.

This is a significant change; don't forget to announce it on the dev list.

**Comment by smillidge** [comment]
Did you look at why the CI is failing. Is it failing in general or just on this PR?

**Comment by arjantijms** [comment]
> Did you look at why the CI is failing. Is it failing in general or just on this PR?

I'm going to look at it now. A brief glance at https://github.com/eclipse-ee4j/glassfish/pulls shows that many (all?) PRs are failing indeed.

**Comment by arjantijms** [comment]
@smillidge @bshannon 

The initial failure was a missed Jenkins file, but currently the CI seems to be failing randomly in the middle of scripts, e.g.

```
org/glassfish/main/ha/ha-shoal-cache-store/6.0.0-SNAPSHOT/_remote.repositories
org/glassfish/main/ha/ha-shoal-cache-store/6.0.0-SNAPSHOT/ha-shoal-cache-store-6.0.0-SNAPSHOT.pom
org/glassfish/main/ha/ha-shoal-cache-store/6.0.0-SNAPSHOT/maven-metadata-local.xml
org/glassfish/main/ha/ha-shoal-cache-store/maven-metadata-local.xml
org/glassfish/main/web/
script returned exit code 1
```

and

```

org/glassfish/main/distributions/nucleus-common/
org/glassfish/main/distributions/nucleus-common/6.0.0-SNAPSHOT/
org/glassfish/main/distributions/nucleus-common/6.0.0-SNAPSHOT/nucleus-common-6.0.0-SNAPSHOT.zip
org/glassfish/main/distributions/nucleus-common/6.0.0-SNAPSHOT/_remote.repositories
org/glassfish/main/distributions/nucleus-common/6.0.0-SNAPSHOT/nucleus-common-6.0.0-SNAPSHOT.pom
org/glassfish/main/distributions/nucleus-common/6.0.0-SNAPSHOT/maven-metadata-local.xml
org/glassfish/main/distributions/nucleus-common/maven-metadata-local.xml
org/glassfish/main/distributions/atomic/
org/glassfish/main/distributions/atomic/6.0.0-SNAPSHOT/
org/glassfish/main/distributions/atomic/6.0.0-SNAPSHOT/atomic-6.0.0-SNAPSHOT.zip
script returned exit code 2
```

etc.

**Comment by romain-grecourt** [comment]
@arjantijms This particular error seems to be coming from `appserver/tests/gftest.sh`:

```bash
cat ${WORKSPACE}/bundles/_maven-repo* | tar -xvz -f - --overwrite -m -p -C ${HOME}/.m2/repository
```

Note sure what to think of the exit codes.

**Comment by arjantijms** [comment]
@romain-grecourt Yes, it's coming from the `cat` and/or `tar` command. It looks like it hangs for a bit, and then exits with 1 or 2. Could this be a disk issue? Related to https://github.com/eclipse-ee4j/glassfish/pull/22877?

**Comment by romain-grecourt** [comment]
I'd hope it is !

Without access to the k8s cluster this kind of stuff is almost impossible to debug / troubleshoot. Unfortunately we cannot get access to the k8s cluster and the eclipse infra people aren't debugging our builds :(

**Comment by arjantijms** [comment]
@romain-grecourt Okay, let's try it in this PR then.

**Comment by arjantijms** [comment]
@romain-grecourt we're actually a bit further now, but there's still weirdness going on and it therefor fails. One of the things is that the server doesn't stop. See 

https://jenkins.eclipse.org/glassfish/blue/rest/organizations/jenkins/pipelines/glassfish/branches/PR-22876/runs/5/nodes/66/steps/241/log/?start=0

The PR from Jonathan which contained no changes other than the Jenkinsfile update also doesn't run to completion, so something is clearly not right still.

**Comment by hs536** [comment]
I suspect that the `runAsUser` in the Jenkinsfile need to be configured with the appropriate user who can access the persistent volume in the new Eclipse infrastructure.

**Comment by arjantijms** [comment]
@hs536 
> I suspect that the runAsUser in the Jenkinsfile need to be configured with the appropriate user who can access the persistent volume in the new Eclipse infrastructure. Is there any way for us to know that?

I'll try to ping the admins again in the bugzilla issue about this: https://bugs.eclipse.org/bugs/show_bug.cgi?id=551841

**Comment by arjantijms** [comment]
Quoting [the reply from Frederic](https://bugs.eclipse.org/bugs/show_bug.cgi?id=551841#c6) here:

> On our new infra the Maven settings.xml are not longer contained in a configMap but in a secret. Therefore you will need to adapt your volume and volumeMounts sections. See also: https://wiki.eclipse.org/Jenkins#Custom_container_on_Jiro_3
> 
> Please replace your "maven-settings" volume and volumeMount with the "settings-xml" volume and volumeMount and add the "settings-security-xml" volume and volumeMount. You don't need the "toolchains-xml" volume and volumeMount.

**Comment by arjantijms** [comment]
@hs536 @romain-grecourt among the problems were old maven http URLs which just switched to https the other day. I updated these.

Another big problem was setting of the .m2 folder. For debug purposes I set those explicitly in the scripts and I temporarily removed the persistent "caching" volume from the Jenkins file. It now gets a whole lot further.

The biggest problem after that is that the scripts/asadmin command doesn't detect GlassFish stopping. I added "|| false" etc everywhere as a test (to see if this is the only issue) and now it almost fully completes.

I'm not sure why I doesn't detect GlassFish not stopping. Do you have any idea?

**Comment by hs536** [comment]
I don't know if this is related to this, but with Fujitsu's modified GlassFish, there was a problem in the past when deploying an EJB app, where the CORBA non-daemon thread remained and stop-domain timed out. At that time, the ORB created in InitialGroupInfoService could not be destroyed when the service stopped, so the following workaround were made.  
workaround) https://github.com/hs536/orb/commit/bc41875b618c433956b57aae6db848b4af684d3f  
see also) https://docs.oracle.com/javase/7/docs/technotes/guides/rmi-iiop/rmi_iiop_pg.html#connecting  
  
We can determine if this problem is occurring by checking thread dumps during the long time stop-domain such as:
```
"Thread-34" #98 prio=5 os_prio=0 tid=0x00007fcb7cb2a800 nid=0xfda in Object.wait() [0x00007fcb3da79000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at com.sun.corba.ee.impl.javax.rmi.CORBA.KeepAlive.run(Util.java:739)
	- locked <0x00000000e4c76638> (a com.sun.corba.ee.impl.javax.rmi.CORBA.KeepAlive)
```

**Comment by arjantijms** [comment]
@hs536 I was certainly attempting that. Already tried to do it before, but nothing showed up in the output of JPS.

I did enable trace logging, and just compared the console and log output, and the current understanding is that the stop command reaches the server, stopping is indeed taking place:

Starting Server (client side output)
```
16:39:06  + /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish/bin/asadmin start-domain
16:39:06  Picked up JAVA_TOOL_OPTIONS: -Xmx2G
16:39:06  HK2 Service locator will be used for command start-domain
16:39:06  Prepare
16:39:06  Process program options
16:39:06  Parse command options
16:39:06  params: {}
16:39:06  operands: []
16:39:06  Prevalidate command options
16:39:06  Inject command options
16:39:06  Validate command options
16:39:06  Not using local password

16:39:06  asadmin --host localhost --port 4848 --interactive=false --echo=false --terse=false start-domain --verbose=false --upgrade=false --watchdog=false --debug=false --dry-run=false --drop-interrupted-commands=false
16:39:06  Execute command
16:39:06  Respawn args: [--host, localhost, --port, 4848, --secure=false, --terse=false, --echo=false, --interactive=false, start-domain, --verbose=false, --watchdog=false, --debug=false, --domaindir, /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish/domains, domain1]
16:39:06  Time spent in master password extraction: 18 msec

16:39:06  Waiting for domain1 to start Check for pid file: /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish/domains/domain1/config/pid
16:39:06  .Check for pid file: /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish/domains/domain1/config/pid

16:39:15  
16:39:15  Successfully started the domain : domain1
16:39:15  domain  Location: /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish/domains/domain1
16:39:15  Log File: /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish/domains/domain1/logs/server.log
16:39:15  Admin Port: 4848
16:39:15  Command start-domain executed successfully.
```


Stopping Server (client side output)

```
16:39:18  restart.server:
16:39:18       [echo] Restarting server...
16:39:18       [exec] Picked up JAVA_TOOL_OPTIONS: -Xmx2G
16:39:18       [exec] HK2 Service locator will be used for command stop-domain
16:39:18       [exec] Prepare
16:39:18       [exec] Process program options
16:39:18       [exec] Parse command options
16:39:18       [exec] params: {force: [true]
16:39:18       [exec] }
16:39:18       [exec] operands: []
16:39:18       [exec] Prevalidate command options
16:39:18       [exec] Inject command options
16:39:18       [exec] Validate command options
16:39:18       [exec] Setting password to: <non-null>
16:39:18       [exec] Using local password
16:39:18       [exec] asadmin --host localhost --port 4848 --interactive=false --echo=false --terse=false stop-domain --force=true --kill=false
16:39:18       [exec] Execute command
16:39:18       [exec] Stopping local domain on port 4848

16:39:18       [exec] Check if server is at location /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish/domains/domain1
16:39:18       [exec] RemoteCLICommand executes
16:39:18       [exec] Prepare
16:39:18       [exec] Command model for command __locations is not in cache. It must be fatched from server.
16:39:18       [exec] URI: /command/__locations
16:39:18       [exec] URL: http://localhost:4848/command/__locations
16:39:18       [exec] Method: GET
16:39:18       [exec] Password options: null
16:39:18       [exec] Using auth info: User: null, Password: <non-null>
16:39:20       [exec] Response code: 200
16:39:20       [exec] ------- RAW METADATA RESPONSE ---------
16:39:20       [exec] ETag: XTXpOxzc7GTgEiOzQmM7hw==
16:39:20       [exec] {"command":{"@name":"__locations"}}
16:39:20       [exec] ------- RAW METADATA RESPONSE ---------

16:39:20       [exec] Command model for __locations command fetched from remote server. [Duration: 1,290,563,787 nanos]
16:39:20       [exec] doHttpCommand succeeds
16:39:20       [exec] Process program options
16:39:20       [exec] Parse command options
16:39:20       [exec] params: {}
16:39:20       [exec] operands: []
16:39:20       [exec] Prevalidate command options
16:39:20       [exec] Inject command options
16:39:20       [exec] Validate command options
16:39:20       [exec] asadmin --host localhost --port 4848 --interactive=false --echo=false --terse=false __locations
16:39:20       [exec] Execute command
16:39:20       [exec] RemoteCLICommand.executeCommand()
16:39:20       [exec] RemoteRestAdminCommand.executeCommand() - name: __locations
16:39:20       [exec] doUpload set to false

16:39:20       [exec] URI: /command/__locations
16:39:20       [exec] URL: http://localhost:4848/command/__locations
16:39:20       [exec] Method: POST
16:39:20       [exec] Password options: null
16:39:20       [exec] Using auth info: User: null, Password: <non-null>
16:39:20       [exec] Writer to use com.sun.enterprise.admin.remote.writer.ParameterMapFormProprietaryWriter
16:39:20       [exec] Response code: 200
16:39:20       [exec] Result type is application/json;charset=UTF-8
16:39:20       [exec] URL connection is sun.net.www.protocol.http.HttpURLConnection

16:39:20       [exec] ------ ACTION REPORT ------
16:39:20       [exec] ACTION REPORT - 0 [SUCCESS]
16:39:20       [exec]  actionDescription: __locations AdminCommand
16:39:20       [exec]     MESSAGE - 0.M0
16:39:20       [exec]      : /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish/domains/domain1
16:39:20       [exec]      >Config-Dir = /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish/domains/domain1/config
16:39:20       [exec]      >Instance-Root = /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish/domains/domain1
16:39:20       [exec]      >Domain-Root = /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish/domains/domain1
16:39:20       [exec]      >Uptime = 13318
16:39:20       [exec]      >Base-Root = /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish
16:39:20       [exec]      >Restart-Required = false
16:39:20       [exec]      >Pid = 240
16:39:20       [exec] 
16:39:20       [exec] 
16:39:20       [exec] ---- END ACTION REPORT ----

16:39:20       [exec] doHttpCommand succeeds
16:39:20       [exec] Remote server has root directory /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish/domains/domain1
16:39:20       [exec] It's the correct DAS
16:39:20       [exec] RemoteCLICommand executes
16:39:20       [exec] Prepare
16:39:20       [exec] Command model for command stop-domain is not in cache. It must be fatched from server.
16:39:20       [exec] URI: /command/stop-domain
16:39:20       [exec] URL: http://localhost:4848/command/stop-domain
16:39:20       [exec] Method: GET
16:39:20       [exec] Password options: null
16:39:20       [exec] Using auth info: User: null, Password: <non-null>
16:39:20       [exec] Response code: 200

16:39:20       [exec] ------- RAW METADATA RESPONSE ---------
16:39:20       [exec] ETag: K1V2vP4vjIug73dBW4N82Q==
16:39:20       [exec] {"command":{"@name":"stop-domain","option":{"@name":"force","@type":"BOOLEAN","@optional":"true","@default":"true"}}}
16:39:20       [exec] ------- RAW METADATA RESPONSE ---------

16:39:20       [exec] Command model for stop-domain command fetched from remote server. [Duration: 12,824,976 nanos]
16:39:20       [exec] doHttpCommand succeeds
16:39:20       [exec] Process program options
16:39:20       [exec] Parse command options
16:39:20       [exec] params: {force: [true]
16:39:20       [exec] }
16:39:20       [exec] operands: []
16:39:20       [exec] Prevalidate command options
16:39:20       [exec] Inject command options
16:39:20       [exec] Validate command options

16:39:20       [exec] asadmin --host localhost --port 4848 --interactive=false --echo=false --terse=false stop-domain --force=true
16:39:20       [exec] Execute command
16:39:20       [exec] RemoteCLICommand.executeCommand()
16:39:20       [exec] RemoteRestAdminCommand.executeCommand() - name: stop-domain
16:39:20       [exec] doUpload set to false

16:39:20       [exec] URI: /command/stop-domain
16:39:20       [exec] URL: http://localhost:4848/command/stop-domain
16:39:20       [exec] Method: POST
16:39:20       [exec] Password options: null
16:39:20       [exec] Using auth info: User: null, Password: <non-null>
16:39:20       [exec] Writer to use com.sun.enterprise.admin.remote.writer.ParameterMapFormProprietaryWriter
16:39:20       [exec] Response code: 200
16:39:20       [exec] Result type is application/json;charset=UTF-8
16:39:20       [exec] URL connection is sun.net.www.protocol.http.HttpURLConnection

16:39:20       [exec] ------ ACTION REPORT ------
16:39:20       [exec] ACTION REPORT - 0 [SUCCESS]
16:39:20       [exec]  actionDescription: stop-domain AdminCommand
16:39:20       [exec]     MESSAGE - 0.M0
16:39:20       [exec]      : Command stop-domain was successfully initiated asynchronously.
16:39:20       [exec] 
16:39:20       [exec] 
16:39:20       [exec] ---- END ACTION REPORT ----
16:39:20       [exec] doHttpCommand succeeds

16:40:27       [exec] Waiting for the domain to stop ...........................................................
16:40:27       [exec] Command stop-domain failed.
16:40:27       [exec] Timed out (60 seconds) waiting for the domain to stop.
16:40:27       [exec] Result: 1
```

Stopping server (server side output)

```
16:39:20.133   [javax.enterprise.system.core] [tid: _ThreadID=154 _ThreadName=Thread-33] [timeMillis: 1579901960133] [levelValue: 800] [[
  Server shutdown initiated]]

16:39:20.184  [javax.enterprise.bootstrap] [tid: _ThreadID=154 _ThreadName=Thread-33] [timeMillis: 1579901960184] [levelValue: 800] [[
  Unregistered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishImpl@3ba0ae41 from service registry.]]

16:39:20.186  [tid: _ThreadID=154 _ThreadName=Thread-8] [timeMillis: 1579901960186] [levelValue: 800] [[
  FileMonitoring shutdown]]

16:39:20.189  [javax.enterprise.system.jmx] [tid: _ThreadID=154 _ThreadName=Thread-33] [timeMillis: 1579901960189] [levelValue: 800] [[
  JMXStartupService: Stopped JMXConnectorServer: null]]

16:39:20.190  [javax.enterprise.system.jmx] [tid: _ThreadID=154 _ThreadName=Thread-33] [timeMillis: 1579901960190] [levelValue: 800] [[
  JMXStartupService and JMXConnectors have been shut down.]]

16:39:20.301   [tid: _ThreadID=155 _ThreadName=Thread-8] [timeMillis: 1579901960301] [levelValue: 800] [[
  JdbcRuntimeExtension,  getAllSystemRAResourcesAndPools = [GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool]]]
```

**Comment by arjantijms** [comment]
It seems the process gets into the **DEFUNCT** state after stopping:

```
12:29:39       [exec] ACTION REPORT - 0 [SUCCESS]
12:29:39       [exec]  actionDescription: stop-domain AdminCommand
12:29:39       [exec]     MESSAGE - 0.M0
12:29:39       [exec]      : Command stop-domain was successfully initiated asynchronously.
12:29:39       [exec] 
12:29:39       [exec] 
12:29:39       [exec] ---- END ACTION REPORT ----
12:29:39       [exec] doHttpCommand succeeds
12:29:39       [exec] Waiting for the domain to stop Server is local
12:29:39       [exec] Server name:domain1
12:29:39       [exec] Trying to read: /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish/domains/domain1/config/pid.prev
12:29:39       [exec] GlassFish PID read: 274
12:29:39       [exec] isProcessRunningUnix - executing kill -0 274
12:29:39       [exec] kill -0 returned 0
12:29:39       [exec] ps -p returned    PID TTY          TIME CMD
12:29:39       [exec]    274 ?        00:00:27 java
12:29:39       [exec] 
12:29:39       [exec] .Trying to read: /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish/domains/domain1/config/pid.prev
12:29:39       [exec] GlassFish PID read: 274
12:29:39       [exec] isProcessRunningUnix - executing kill -0 274
12:29:39       [exec] kill -0 returned 0
12:29:39       [exec] ps -p returned    PID TTY          TIME CMD
12:29:39       [exec]    274 ?        00:00:27 java
12:29:39       [exec] 
12:29:39       [exec] Trying to read: /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish/domains/domain1/config/pid.prev
12:29:39       [exec] GlassFish PID read: 274
12:29:39       [exec] isProcessRunningUnix - executing kill -0 274
12:29:39       [exec] kill -0 returned 0
12:29:39       [exec] ps -p returned    PID TTY          TIME CMD
12:29:39       [exec]    274 ?        00:00:28 java
12:29:39       [exec] 
12:29:39       [exec] Trying to read: /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish/domains/domain1/config/pid.prev
12:29:39       [exec] GlassFish PID read: 274
12:29:39       [exec] isProcessRunningUnix - executing kill -0 274
12:29:39       [exec] kill -0 returned 0
12:29:39       [exec] ps -p returned    PID TTY          TIME CMD
12:29:39       [exec]    274 ?        00:00:28 java
12:29:39       [exec] 
12:29:40       [exec] Trying to read: /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish/domains/domain1/config/pid.prev
12:29:40       [exec] GlassFish PID read: 274
12:29:40       [exec] isProcessRunningUnix - executing kill -0 274
12:29:40       [exec] kill -0 returned 0
12:29:40       [exec] ps -p returned    PID TTY          TIME CMD
12:29:40       [exec]    274 ?        00:00:28 java
12:29:40       [exec] 
12:29:40       [exec] Trying to read: /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish/domains/domain1/config/pid.prev
12:29:40       [exec] GlassFish PID read: 274
12:29:40       [exec] isProcessRunningUnix - executing kill -0 274
12:29:40       [exec] kill -0 returned 0
12:29:40       [exec] ps -p returned    PID TTY          TIME CMD
12:29:40       [exec]    274 ?        00:00:28 java
12:29:40       [exec] 
12:29:40       [exec] Trying to read: /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish/domains/domain1/config/pid.prev
12:29:40       [exec] GlassFish PID read: 274
12:29:40       [exec] isProcessRunningUnix - executing kill -0 274
12:29:40       [exec] kill -0 returned 0
12:29:40       [exec] ps -p returned    PID TTY          TIME CMD
12:29:40       [exec]    274 ?        00:00:28 java <defunct>
12:29:40       [exec] 
12:29:40       [exec] Trying to read: /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish/domains/domain1/config/pid.prev
12:29:40       [exec] GlassFish PID read: 274
12:29:40       [exec] isProcessRunningUnix - executing kill -0 274
12:29:40       [exec] kill -0 returned 0
12:29:40       [exec] ps -p returned    PID TTY          TIME CMD
12:29:40       [exec]    274 ?        00:00:28 java <defunct>
```

**Comment by arjantijms** [comment]
ps -ef output:

```
UID         PID   PPID  C STIME TTY          TIME CMD

1001880+      1      0  0 19:23 ?        00:00:00 cat

1001880+     17      0  0 19:25 ?        00:00:00 sh -c ({ while [ -d '/home/jenkins/agent/workspace/glassfish_PR-22876@tmp/durable-846abf0d' -a \! -f '/home/jenkins/agent/workspace/glassfish_PR-22876@tmp/durable-846abf0d/jenkins-result.txt' ]; do touch '/home/jenkins/agent/workspace/glassfish_PR-22876@tmp/durable-846abf0d/jenkins-log.txt'; sleep 3; done } & jsc=durable-6bee4b4b5f7883cc12ce7d30ffb8ccdc; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/jenkins/agent/workspace/glassfish_PR-22876@tmp/durable-846abf0d/script.sh' > '/home/jenkins/agent/workspace/glassfish_PR-22876@tmp/durable-846abf0d/jenkins-log.txt' 2>&1; echo $? > '/home/jenkins/agent/workspace/glassfish_PR-22876@tmp/durable-846abf0d/jenkins-result.txt.tmp'; mv '/home/jenkins/agent/workspace/glassfish_PR-22876@tmp/durable-846abf0d/jenkins-result.txt.tmp' '/home/jenkins/agent/workspace/glassfish_PR-22876@tmp/durable-846abf0d/jenkins-result.txt'; wait) >&- 2>&- &

1001880+     18     17  0 19:25 ?        00:00:00 sh -c ({ while [ -d '/home/jenkins/agent/workspace/glassfish_PR-22876@tmp/durable-846abf0d' -a \! -f '/home/jenkins/agent/workspace/glassfish_PR-22876@tmp/durable-846abf0d/jenkins-result.txt' ]; do touch '/home/jenkins/agent/workspace/glassfish_PR-22876@tmp/durable-846abf0d/jenkins-log.txt'; sleep 3; done } & jsc=durable-6bee4b4b5f7883cc12ce7d30ffb8ccdc; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/home/jenkins/agent/workspace/glassfish_PR-22876@tmp/durable-846abf0d/script.sh' > '/home/jenkins/agent/workspace/glassfish_PR-22876@tmp/durable-846abf0d/jenkins-log.txt' 2>&1; echo $? > '/home/jenkins/agent/workspace/glassfish_PR-22876@tmp/durable-846abf0d/jenkins-result.txt.tmp'; mv '/home/jenkins/agent/workspace/glassfish_PR-22876@tmp/durable-846abf0d/jenkins-result.txt.tmp' '/home/jenkins/agent/workspace/glassfish_PR-22876@tmp/durable-846abf0d/jenkins-result.txt'; wait) >&- 2>&- &

1001880+     19     17  0 19:25 ?        00:00:00 sh -xe /home/jenkins/agent/workspace/glassfish_PR-22876@tmp/durable-846abf0d/script.sh

1001880+     22     19  0 19:25 ?        00:00:00 /bin/bash -ex ./appserver/tests/gftest.sh run_test deployment_all

1001880+    116     22  0 19:25 ?        00:00:00 /bin/bash -ex ./appserver/tests/appserv-tests/devtests/deployment/run_test.sh run_test_id deployment_all

1001880+    274      1 99 19:25 ?        00:00:26 [java] <defunct>

1001880+    421    116 51 19:25 ?        00:00:05 /usr/lib/jvm/jdk8/jre/bin/java -classpath /usr/share/ant/lib/ant-launcher.jar -Dant.home=/usr/share/ant -Dant.library.dir=/usr/share/ant/lib org.apache.tools.ant.launch.Launcher -cp  all

1001880+    422    116  0 19:25 ?        00:00:00 tee /home/jenkins/agent/workspace/glassfish_PR-22876/tests-run.log

1001880+    504    421 99 19:26 ?        00:00:02 java -jar /home/jenkins/agent/workspace/glassfish_PR-22876/glassfish6/glassfish/bin/../lib/client/appserver-cli.jar stop-domain --force

1001880+    583     18  0 19:26 ?        00:00:00 sleep 3
1001880+    676    504  0 19:26 ?        00:00:00 ps -ef
```

**Comment by arjantijms** [comment]
@romain-grecourt @m0mus Do you know who created/maintains the docker image that is being used for the build here?

**Comment by m0mus** [comment]
> Do you know who created/maintains the docker image that is being used for the build here?

I don't know, but I am sure that @romain-grecourt knows. :)

**Comment by romain-grecourt** [comment]
@arjantijms send me your docker username in dm, I'll add you to the group.

**Comment by arjantijms** [comment]
@romain-grecourt just send you a dm ;)

**Comment by bshannon** [comment]
Did you announce this on the dev list?  I didn't see it.

This still works with only JDK 8, right?

Do we have a plan for the 5.1.0-runs-with-JDK11 branch?  Will it be merged with master
to allow 6.0.0 to run with JDK 11?  When?

**Pull request merged**
