### PR TITLE
Integrate Shoal 3.0.0-M1

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: Arjan Tijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Review by pzygielo — APPROVED** [review]

**Comment by pzygielo** [comment]
Following is unclear for me:
- How this https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/shoal/shoal-gms-impl/3.0.0-M1/ (+ other shoal-* 300M1) was built and staged? I can't find anything at https://ci.eclipse.org/glassfish/view/all/ - only https://ci.eclipse.org/glassfish/view/all/job/shoal/ which doesn't seem to do that.
- What this was built from? I can't find release branch/tag at https://github.com/eclipse-ee4j/glassfish-shoal.

**Comment by pzygielo** [comment]
>     * How this https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/shoal/shoal-gms-impl/3.0.0-M1/ (+ other shoal-* 300M1) was built and staged? 

OK - found it (again): https://ci.eclipse.org/glassfish/view/All%20Projects/job/all-projects_1_build-and-stage/83/

**Comment by pzygielo** [comment]
>     * What this was built from? I can't find release branch/tag at https://github.com/eclipse-ee4j/glassfish-shoal.

Found it (again again) why: https://ci.eclipse.org/glassfish/view/All%20Projects/job/all-projects_1_build-and-stage/83/parameters/
```
if [[ ${PUSH_TO_GITHUB} = 'true' ]]
```
:disappointed:

**Comment by arjantijms** [comment]
> if [[ ${PUSH_TO_GITHUB} = 'true' ]]

It can probably be removed now. Maybe it was added when GitHub often failed?

**Pull request merged**
