### PR TITLE
Integrate jaxb-impl 4.0.3

### PR DESCRIPTION
**Pull request by arjantijms**
Changes: https://github.com/eclipse-ee4j/jaxb-ri/releases/tag/4.0.3-RI

### CODE REVIEW

**Review by gurunrao — APPROVED** [review]

**Comment by avpinchuk** [comment]
Hmm, something wrong here. Integration tests failed. I tried local build - failed too.

**Comment by hs536** [comment]
It may not be directly related to pipeline failure, but you should create a PR from your forked repository.

**Comment by avpinchuk** [comment]
@hs536, `mvn clean install -Pstaging` failed itself. More specific, `StartStopITest` failed by timeout. With previous jaxb-impl v4.0.2 build succesfull.

**Comment by lukasj** [comment]
I'd expect the build job to archive/publish server logs and/or test results. Where are they?

**Comment by avpinchuk** [comment]
@arjantijms, @lukasj,  osgi bundle manifests for version 4.0.3 contains standard java packages, like `java.awt.*`. I think the problem is there.

**Comment by avpinchuk** [comment]
This is a little bit of the server verbose log

<pre>Launching GlassFish on Felix platform
ERROR: Bundle org.glassfish.main.hk2.config-types [240] Error starting file:/home/avpinchuk/build/glassfish7/glassfish/modules/config-types.jar (org.osgi.framework.BundleException: Unable to resolve org.glassfish.main.hk2.config-types [240](R 240.0): missing requirement [org.glassfish.main.hk2.config-types [240](R 240.0)] osgi.wiring.package; (&amp;(osgi.wiring.package=org.jvnet.hk2.config)(version&gt;=7.0.0)(!(version&gt;=8.0.0))) [caused by: Unable to resolve org.glassfish.main.hk2-config-generator [192](R 192.0): missing requirement [org.glassfish.main.hk2-config-generator [192](R 192.0)] osgi.wiring.package; (&amp;(osgi.wiring.package=com.sun.codemodel)(version&gt;=4.0.0)(!(version&gt;=5.0.0))) [caused by: Unable to resolve com.sun.xml.bind.jaxb-osgi [176](R 176.0): missing requirement [com.sun.xml.bind.jaxb-osgi [176](R 176.0)] osgi.wiring.package; (osgi.wiring.package=java.awt)]] Unresolved requirements: [[org.glassfish.main.hk2.config-types [240](R 240.0)] osgi.wiring.package; (&amp;(osgi.wiring.package=org.jvnet.hk2.config)(version&gt;=7.0.0)(!(version&gt;=8.0.0)))])
org.osgi.framework.BundleException: Unable to resolve org.glassfish.main.hk2.config-types [240](R 240.0): missing requirement [org.glassfish.main.hk2.config-types [240](R 240.0)] osgi.wiring.package; (&amp;(osgi.wiring.package=org.jvnet.hk2.config)(version&gt;=7.0.0)(!(version&gt;=8.0.0))) [caused by: Unable to resolve org.glassfish.main.hk2-config-generator [192](R 192.0): missing requirement [org.glassfish.main.hk2-config-generator [192](R 192.0)] osgi.wiring.package; (&amp;(osgi.wiring.package=com.sun.codemodel)(version&gt;=4.0.0)(!(version&gt;=5.0.0))) [caused by: Unable to resolve com.sun.xml.bind.jaxb-osgi [176](R 176.0): missing requirement [com.sun.xml.bind.jaxb-osgi [176](R 176.0)] osgi.wiring.package; (osgi.wiring.package=java.awt)]] Unresolved requirements: [[org.glassfish.main.hk2.config-types [240](R 240.0)] osgi.wiring.package; (&amp;(osgi.wiring.package=org.jvnet.hk2.config)(version&gt;=7.0.0)(!(version&gt;=8.0.0)))]</pre>

**Comment by avpinchuk** [comment]
I fixed a [similar thing](https://github.com/eclipse-ee4j/glassfish-hk2/pull/809) in the HK2.

Now I tried to build GF with locally fixed JAXB-RI - all works.

**Comment by dmatej** [comment]
> I'd expect the build job to archive/publish server logs and/or test results. Where are they?

Logs are archived, but GF even did not start, so there are no logs. For other builds they available, for example [here](https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/view/change-requests/job/PR-24456/) (if not deleted by tests).

**Comment by arjantijms** [comment]
> Now I tried to build GF with locally fixed JAXB-RI - all works.

We've had that problem with multiple projects. I fixed it a couple of times before.

**Comment by lukasj** [comment]
> We've had that problem with multiple projects. I fixed it a couple of times before.

wouldn't it be better to - after ~5 years - accept the fact there is OSGi R7 out there and adopt it instead of forcing dependencies to not move forward?

**Comment by lukasj** [comment]
> > I'd expect the build job to archive/publish server logs and/or test results. Where are they?
> 
> Logs are archived, but GF even did not start, so there are no logs.

so I did run a build. The test failed. I see server.log in the target folder but here it is said there is no log because server did not start. In my environment, the log is there even though the server did not start. 

From what I can see:
* server logs are not being archived IF the build itself fails
* at least the start/stop test - the one which failed here - should be run with increased verbosity level, so the log makes it easier to pinpoint the cause

**Comment by dmatej** [comment]
> > We've had that problem with multiple projects. I fixed it a couple of times before.
> 
> wouldn't it be better to - after ~5 years - accept the fact there is OSGi R7 out there and adopt it instead of forcing dependencies to not to move forward?

Actually we (OmniFish) force project to move forward - and without these mistakes. GlassFish is blocked by some dependencies, right now I am working on XmlSec (that will affect WSIT after the release).

> so I did run a build. The test failed. I see server.log in the target folder but here it is said there is no log because server did not start. In my environment, the log is there even though the server did not start.

True, seems we should fix the Jenkinsfile, it doesn't archive logs after failure. The step was not executed.

>  increased verbosity level,

Will not help, see #24065 . You can locally set AS_TRACE, but that logs just events before it starts the Felix part. When Felix cannot continue, it simply stops because it cannot print anything to STDOUT/STDERR except when started with `--verbose` which starts in "interatcive mode" so user can read STDOUT and stop the process with CTRL+C . 
In #24458 and #24446 we refactored ProcessManager to year 2023, so I rebased the PR now, but it did not change anything here. I have just aligned the StartStopITest timeout with start-domain timeout, no now it prints this:

```
[ERROR]   StartStopITest.<clinit>:31
Expected: asadmin succeeded
but: was <Waiting for domain1 to start .........................
Waiting finished after 25,000 ms.
Command start-domain failed.
No response from the Domain Administration Server (domain1) after 25 seconds.
The command is either taking too long to complete or the server has failed.
Please see the server log files for command status.
Please start with the --verbose option in order to see early messages.
>
```

->>> And you have to run it locally.

**Comment by arjantijms** [comment]
Proposed fix for JAXB RI: https://github.com/eclipse-ee4j/jaxb-ri/pull/1722 @lukasj

**Review by avpinchuk — APPROVED** [review]

**Comment by lukasj** [comment]
based on my testing the cause of problem is that the definition of the `org.osgi.framework.system.packages` property in the `osgi.properties` file - which is defined by the GlassFish itself - has not been (properly) updated for JDK 9+ to include the list of required/available packages together with uptake of felix 7+ (or whichever version brought OSGi R7 compatibility). Therefore I believe that the fix needs to be done on the GF side and the jaxb patch introduced here and proposed for jaxb-ri is -in its current form - wrong.

**Pull request merged**
