### PR TITLE
TCK Results for Annotations API (uses GlassFish as referenced Compati…

### PR DESCRIPTION
**Pull request by edbratt**
…ble Implementation)

Doc details for Annotations compatibility certification request.

Signed-off-by: Ed Bratt <ed.bratt@oracle.com>

### CODE REVIEW

**Review by Tomas-Kraus — APPROVED** [review]
Looks good.

**Review by m0mus — APPROVED** [review]
LGTM

**Review by smillidge — APPROVED** [review]

**Comment by smillidge** [comment]
Should this be merged now or after ballot?

**Comment by edbratt** [comment]
I will need to be updated because the TCK SHA will change, but I want to verify everything is working. I merged it.

**Pull request merged**
