### PR TITLE
Continue on Fix Admin Console Admin UI Erros

### PR DESCRIPTION
**Pull request by gerdogdu**
Continue to work on fixing the Admin UI related errors. Now, all of the functionality is working except for local file deployment with FileChooser Dialog Box. The FileChooser local file selection dialog box is not working because of dojo upgrade. But, this must be so updated in woodstock 4.0.2.16 version.

Previously there are errors in Application Deployment, Starting Standalone and Cluster instances, Creating Nodes, Log Viewing, JVM reports etc. Now, all of them are working correctly.

Most of the errors were coming from updated dojo to use Dojo AMD.

### CODE REVIEW

**Review by arjantijms — APPROVED** [review]
LGTM

**Comment by arjantijms** [comment]
Oh, the headers do need to be updated to copyright 2020.

**Comment by gerdogdu** [comment]
I did also update the copyright to 2020.

**Comment by arjantijms** [comment]
> I did also update the copyright to 2020.

Thanks! :) Let's see if we can get Suzan to say something about this @MeroRai

**Review by hs536 — APPROVED** [review]

**Pull request merged**
