### PR TITLE
appclient container needs 2.1.1 Jakarta Annotation ManagedBean

### PR DESCRIPTION
**Pull request by scottmarlow**
Signed-off-by: Scott Marlow <smarlow@redhat.com>

Possible change for https://github.com/eclipse-ee4j/glassfish/issues/24014

### CODE REVIEW

**Comment by scottmarlow** [comment]
Note that this doesn't build correctly for me yet due to `Could not find artifact org.jboss.weld.se:weld-se-shaded:jar:5.0.SP2`

**Comment by dmatej** [comment]
Oh, nice, so I can drop my local changes where I "hacked" appclient by adding newer annotation-api to the classpath before weld-se-shaded.

**Comment by arjantijms** [comment]
@scottmarlow If I look here, there's no 5.0.SP2 yet:

https://repo1.maven.org/maven2/org/jboss/weld/se/weld-se-shaded

The last one is

```
5.0.0.SP2         2022-06-08 13:08         -
```

**Comment by starksm64** [comment]
That artifact is there:
https://repo1.maven.org/maven2/org/jboss/weld/se/weld-se-shaded/5.0.0.SP2/
```
[weld-se-shaded-5.0.0.SP2-javadoc.jar](https://repo1.maven.org/maven2/org/jboss/weld/se/weld-se-shaded/5.0.0.SP2/weld-se-shaded-5.0.0.SP2-javadoc.jar)              2022-06-08 13:08   7205180      
[weld-se-shaded-5.0.0.SP2-javadoc.jar.asc](https://repo1.maven.org/maven2/org/jboss/weld/se/weld-se-shaded/5.0.0.SP2/weld-se-shaded-5.0.0.SP2-javadoc.jar.asc)          2022-06-08 13:08       659      
[weld-se-shaded-5.0.0.SP2-javadoc.jar.md5](https://repo1.maven.org/maven2/org/jboss/weld/se/weld-se-shaded/5.0.0.SP2/weld-se-shaded-5.0.0.SP2-javadoc.jar.md5)          2022-06-08 13:08        32      
[weld-se-shaded-5.0.0.SP2-javadoc.jar.sha1](https://repo1.maven.org/maven2/org/jboss/weld/se/weld-se-shaded/5.0.0.SP2/weld-se-shaded-5.0.0.SP2-javadoc.jar.sha1)         2022-06-08 13:08        40      
[weld-se-shaded-5.0.0.SP2-sources.jar](https://repo1.maven.org/maven2/org/jboss/weld/se/weld-se-shaded/5.0.0.SP2/weld-se-shaded-5.0.0.SP2-sources.jar)              2022-06-08 13:08   2913339      
[weld-se-shaded-5.0.0.SP2-sources.jar.asc](https://repo1.maven.org/maven2/org/jboss/weld/se/weld-se-shaded/5.0.0.SP2/weld-se-shaded-5.0.0.SP2-sources.jar.asc)          2022-06-08 13:08       659      
[weld-se-shaded-5.0.0.SP2-sources.jar.md5](https://repo1.maven.org/maven2/org/jboss/weld/se/weld-se-shaded/5.0.0.SP2/weld-se-shaded-5.0.0.SP2-sources.jar.md5)          2022-06-08 13:08        32      
[weld-se-shaded-5.0.0.SP2-sources.jar.sha1](https://repo1.maven.org/maven2/org/jboss/weld/se/weld-se-shaded/5.0.0.SP2/weld-se-shaded-5.0.0.SP2-sources.jar.sha1)         2022-06-08 13:08        40      
[weld-se-shaded-5.0.0.SP2.jar](https://repo1.maven.org/maven2/org/jboss/weld/se/weld-se-shaded/5.0.0.SP2/weld-se-shaded-5.0.0.SP2.jar)                      2022-06-08 13:08   3464828      
[weld-se-shaded-5.0.0.SP2.jar.asc](https://repo1.maven.org/maven2/org/jboss/weld/se/weld-se-shaded/5.0.0.SP2/weld-se-shaded-5.0.0.SP2.jar.asc)                  2022-06-08 13:08       659      
[weld-se-shaded-5.0.0.SP2.jar.md5](https://repo1.maven.org/maven2/org/jboss/weld/se/weld-se-shaded/5.0.0.SP2/weld-se-shaded-5.0.0.SP2.jar.md5)                  2022-06-08 13:08        32      
[weld-se-shaded-5.0.0.SP2.jar.sha1](https://repo1.maven.org/maven2/org/jboss/weld/se/weld-se-shaded/5.0.0.SP2/weld-se-shaded-5.0.0.SP2.jar.sha1)                 2022-06-08 13:08        40      
[weld-se-shaded-5.0.0.SP2.pom](https://repo1.maven.org/maven2/org/jboss/weld/se/weld-se-shaded/5.0.0.SP2/weld-se-shaded-5.0.0.SP2.pom)                      2022-06-08 13:08      7598      
[weld-se-shaded-5.0.0.SP2.pom.asc](https://repo1.maven.org/maven2/org/jboss/weld/se/weld-se-shaded/5.0.0.SP2/weld-se-shaded-5.0.0.SP2.pom.asc)                  2022-06-08 13:08       659      
[weld-se-shaded-5.0.0.SP2.pom.md5](https://repo1.maven.org/maven2/org/jboss/weld/se/weld-se-shaded/5.0.0.SP2/weld-se-shaded-5.0.0.SP2.pom.md5)                  2022-06-08 13:08        32      
[weld-se-shaded-5.0.0.SP2.pom.sha1](https://repo1.maven.org/maven2/org/jboss/weld/se/weld-se-shaded/5.0.0.SP2/weld-se-shaded-5.0.0.SP2.pom.sha1)                 2022-06-08 13:08        40
```

**Comment by starksm64** [comment]
There will have to be a new post 5.0.0.SP2 release to pickup the update of common annotations to 2.1.1.

**Comment by dmatej** [comment]
Seems also there are no other changes in Weld core github repo, including weld-se-shaded project. So we should probably create a PR with updated dependencies for them.
image

**Comment by dmatej** [comment]
Aha, I get it ... we need to update weld-core's dependency on weld-api ...

**Comment by scottmarlow** [comment]
https://github.com/weld/core/pull/2747 + https://issues.redhat.com/browse/WELD-2722 sound like a great change but considering that the pull request is still in draft mode and the work in my opinion, sounds like something that might not be solved quickly, I wonder if it is better to hack in the individual common annotations 2.1.1 jar into the appclient container as @dmatej was likely doing before I created this broken pr! :-)

**Comment by dmatej** [comment]
My "hack" wasn't nice and @manovotn estimates that tomorrow they will release new Weld, so we can probably wait for that :-)

**Comment by scottmarlow** [comment]
I changed the pull request to update to Weld 5.0.0.SP3 (looks like next likely tag in https://github.com/weld/core/tags), if that is not the right version (when released), I will update this pr again.

**Review by dmatej — APPROVED** [review]

**Comment by dmatej** [comment]
> @scottmarlow The version will be [5.0.1.Final](https://issues.redhat.com/projects/WELD/versions/12385166) (using the Weld API 5.0.SP2). The release is running now so if there are no issues with it, I assume it could land in Central within an hour or so.

Just FYI, it reached Maven Central, co I initiated rebuild on Jenkins.

**Comment by dmatej** [comment]
Eh, Maven default rules - it saves failures, so it will recheck after 24 h again. Another option is to purge the Maven repository.

**Review by dmatej — CHANGES_REQUESTED** [review]
Seems OSGi doesn't like this change ...

**Comment by arjantijms** [comment]
After a quick run it seems like the CDI TCK also doesn't like this upgrade:

```
[ERROR] Failures: 
[ERROR]   ProcessBeanAttributesNotFiredForBuiltinBean>Arquillian.run:138->testProcessBeanAttributesNotFired:51 expected [true] but found [false]
[ERROR]   AfterTypeDiscoveryTest>Arquillian.run:138->testFinalAlternatives:128 expected [true] but found [false]
[ERROR]   AfterTypeDiscoveryTest>Arquillian.run:138->testInitialAlternatives:81 expected [3] but found [11]
[ERROR]   AfterTypeDiscoveryMassOperationsTest>Arquillian.run:138->testInitialAlternatives:77 expected [3] but found [11]
```

Maybe a Weld 5.0.1 is just too much for now? What we really need is a 5.0.0.SP3, which only changes the problematic Jakarta Annotation ManagedBean and absolutely nothing else. No comment, no whitespace, nothing. Just ManagedBean.

**Comment by dmatej** [comment]
> After a quick run it seems like the CDI TCK also doesn't like this upgrade:
> 
> ```
> [ERROR] Failures: 
> [ERROR]   ProcessBeanAttributesNotFiredForBuiltinBean>Arquillian.run:138->testProcessBeanAttributesNotFired:51 expected [true] but found [false]
> [ERROR]   AfterTypeDiscoveryTest>Arquillian.run:138->testFinalAlternatives:128 expected [true] but found [false]
> [ERROR]   AfterTypeDiscoveryTest>Arquillian.run:138->testInitialAlternatives:81 expected [3] but found [11]
> [ERROR]   AfterTypeDiscoveryMassOperationsTest>Arquillian.run:138->testInitialAlternatives:77 expected [3] but found [11]
> ```
> 
> Maybe a Weld 5.0.1 is just too much for now? What we really need is a 5.0.0.SP3, which only changes the problematic Jakarta Annotation ManagedBean and absolutely nothing else. No comment, no whitespace, nothing. Just ManagedBean.

Finally we found that these CDI TCK failures were caused by something between Krazo and CDI TCK, it has nothing to do with this PR.

**Review by dmatej — APPROVED** [review]

**Pull request merged**
