### PR TITLE
Add support for MicroProfile JWT

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: Arjan Tijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Review by dmatej — APPROVED** [review]

**Comment by pzygielo** [comment]
Is it possible that these failures
- https://ci.eclipse.org/glassfish/view/GlassFish/job/glassfish_weekly_build/152
- https://ci.eclipse.org/glassfish/view/GlassFish/job/glassfish_weekly_build/153

and this change are related?

**Comment by dmatej** [comment]
> Is it possible that these failures
> 
> * https://ci.eclipse.org/glassfish/view/GlassFish/job/glassfish_weekly_build/152
> * https://ci.eclipse.org/glassfish/view/GlassFish/job/glassfish_weekly_build/153
> 
> and this change are related?

They are, @arjantijms  knows about it. I think it leads the fix is to use Java17 for build.

```
ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.0.0:run (do stuff) on project glassfish: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /home/jenkins/agent/workspace/glassfish_weekly_build/glassfish-build/appserver/distributions/glassfish/target/antrun/build-main.xml:9: The archive microprofile-jwt-auth-api.jar doesn't exist
[ERROR] around Ant part ...<jarupdate basedir="/home/jenkins/agent/workspace/glassfish_weekly_build/glassfish-build/appserver/distributions/glassfish/src/main/patches/microprofile-jwt-auth-api" destfile="/home/jenkins/agent/workspace/glassfish_weekly_build/glassfish-build/appserver/distributions/glassfish/target/stage/glassfish7/glassfish/modules/microprofile-jwt-auth-api.jar" includes="META-INF/MANIFEST.MF" />... @ 17:392 in /home/jenkins/agent/workspace/glassfish_weekly_build/glassfish-build/appserver/distributions/glassfish/target/antrun/build-main.xml

```

**Comment by dmatej** [comment]
Fixed: https://ci.eclipse.org/glassfish/view/GlassFish/job/glassfish_weekly_build/

**Comment by pzygielo** [comment]
Thanks!

**Comment by PatrickHuang888** [comment]
why I got this error when I compile on master or 7.0.1
```
ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.0.0:run (do stuff) on project glassfish: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /opt/glassfish/appserver/distributions/glassfish/target/antrun/build-main.xml:9: The archive microprofile-jwt-auth-api.jar doesn't exist
[ERROR] around Ant part ...<jarupdate basedir="/opt/glassfish/appserver/distributions/glassfish/src/main/patches/microprofile-jwt-auth-api" destfile="/opt/glassfish/appserver/distributions/glassfish/target/stage/glassfish7/glassfish/modules/microprofile-jwt-auth-api.jar" includes="META-INF/MANIFEST.MF" />... @ 17:284 in /opt/glassfish/appserver/distributions/glassfish/target/antrun/build-main.xml
```

**Comment by PatrickHuang888** [comment]
> why I got this error when I compile on master or 7.0.1
> 
> ```
> ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.0.0:run (do stuff) on project glassfish: An Ant BuildException has occured: The following error occurred while executing this line:
> [ERROR] /opt/glassfish/appserver/distributions/glassfish/target/antrun/build-main.xml:9: The archive microprofile-jwt-auth-api.jar doesn't exist
> [ERROR] around Ant part ...<jarupdate basedir="/opt/glassfish/appserver/distributions/glassfish/src/main/patches/microprofile-jwt-auth-api" destfile="/opt/glassfish/appserver/distributions/glassfish/target/stage/glassfish7/glassfish/modules/microprofile-jwt-auth-api.jar" includes="META-INF/MANIFEST.MF" />... @ 17:284 in /opt/glassfish/appserver/distributions/glassfish/target/antrun/build-main.xml
> ```

found out, JDK11 has this problem, and there is no problem on JDK17, I think this should be on docs

**Pull request merged**
