### PR TITLE
Update test tools checkstyle and jacoco

### PR DESCRIPTION
**Pull request by arjantijms**

### CODE REVIEW

**Comment by hs536** [comment]
Humm... Not sure why, but it seems to be failing to get the `htmlunit:pom:2.70.0`.

https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/job/PR-24656/

**Comment by arjantijms** [comment]
> Humm... Not sure why, but it seems to be failing to get the `htmlunit:pom:2.70.0`.
> 
> https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/job/PR-24656/

Very strange, locally it of course builds fine. Occasionally the Eclipse CI has issues with failing to get simple things.

**Comment by arjantijms** [comment]
> > Humm... Not sure why, but it seems to be failing to get the `htmlunit:pom:2.70.0`.
> > https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/job/PR-24656/
> 
> Very strange, locally it of course builds fine. Occasionally the Eclipse CI has issues with failing to get simple things.

Look like a certificate issue;

```
07:41:54  [ERROR] Failed to execute goal on project servlet: Could not resolve dependencies for project org.glassfish.tests.embedded.web:servlet:war:7.0.10-SNAPSHOT: 

Failed to collect dependencies at net.sourceforge.htmlunit:htmlunit:jar:2.70.0: 
Failed to read artifact descriptor for net.sourceforge.htmlunit:htmlunit:jar:2.70.0: 

The following artifacts could not be resolved: net.sourceforge.htmlunit:htmlunit:pom:2.70.0 (absent): 

Could not transfer artifact net.sourceforge.htmlunit:htmlunit:pom:2.70.0 from/to sonatype-nexus-staging (https://jakarta.oss.sonatype.org/content/repositories/staging/): 

PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
```

**Comment by arjantijms** [comment]
Maybe it always tried the staging repo in the chain of repos it tries. 

In this case, the failure aborts the entire operation?

Perhaps the other jobs don't fail as they happen to get their dependencies from the local .m2 first?

**Comment by dmatej** [comment]
Something is wrong with the certificate, I don't see what. All three certificates look valid in my browser.

**Comment by dmatej** [comment]
Tip: didn't htmlunit change also groupid?

**Comment by arjantijms** [comment]
> Tip: didn't htmlunit change also groupid?

I did resolve locally... but let';s try again in a new PR

**Review by avpinchuk — APPROVED** [review]

**Pull request merged**
