### PR TITLE
Reflect current ECA requirements to use `Author` instead of `Signed-Off`

### PR DESCRIPTION
**Pull request by pzygielo**
- https://github.com/eclipse-ee4j/glassfish/pull/24077#issuecomment-1222180772

### CODE REVIEW

**Comment by dmatej** [comment]
Aren't they alternatives now?

**Comment by pzygielo** [comment]
> Aren't they alternatives now?

I don't understand that question.

**Comment by dmatej** [comment]
> > Aren't they alternatives now?
> 
> I don't understand that question.

I mean that now it is possible to use the Author field OR the Signed-Off. But I didn't try it for a while ...

**Comment by pzygielo** [comment]
> > > Aren't they alternatives now?
> > 
> > 
> > I don't understand that question.
> 
> I mean that now it is possible to use the Author field OR the Signed-Off. But I didn't try it for a while ...

I've tried 
- https://github.com/eclipse-ee4j/concurrency-ri/pull/61

(I'm not Committer there) - with Author bearing different address, not known currently to EF, and Signed-Off with ECAed address. ECA check (unavailable now due to PR being closed) failed. So my understanding is - it's Author field only.


The point is - it's [no longer needed](https://www.eclipse.org/lists/eclipse.org-committers/msg01291.html) to sign off commits, with some reasons also given in [558653](https://bugs.eclipse.org/bugs/show_bug.cgi?id=558653).
Apparently almost noone reads [GF: Community Standards](https://github.com/eclipse-ee4j/glassfish/community) :: [Contributing](https://github.com/eclipse-ee4j/glassfish/blob/master/CONTRIBUTING.md) anyway, but for the people that do - let's not bother them with that requirement from the past.

**Comment by dmatej** [comment]
Yeah, that was just a question ;)
When I was resolving ECA, I think I read some Eclipse documentation, but today I found that I enable bookmark sync  both in Chromium and Chrome and all my bookmarks in Chrome are gone and replaced by set from Chromium, eh ... :-/

Ok, I got it, you are absolutely right: https://wiki.eclipse.org/Development_Resources/Contributing_via_Git

**Review by dmatej — APPROVED** [review]

**Pull request merged**
