### PR TITLE
Update several dependencies to latest version.

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: arjantijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Comment by smillidge** [comment]
Not sure I want to merge just a bunch of changes like this when we are getting close to a Full TCK run

**Comment by arjantijms** [comment]
> Not sure I want to merge just a bunch of changes like this when we are getting close to a Full TCK run

If this would cause extra TCK failures it would be a matter of a quick revert, though maybe it's a moot point in this case as the PR is already failing. I'll take a very quick look at the failures tomorrow, and if it's not something extremely obvious I'll close the PR for now.

**Comment by arjantijms** [comment]
p.s. the Weld version definitely would need to be updated from Alpha.3 to Beta.1 I think. I'll do a separate PR for that.

**Review by jGauravGupta — APPROVED** [review]

**Comment by smillidge** [comment]
I'd prefer individual changes. I agree Weld will need an update and a few others. Best to do individual PRs as I got burnt by this a month or so back doing a bunch at the same time. I was also going to pick up a few.

**Comment by arjantijms** [comment]
Ok, no worries. I'll close this in favour of individual PRs.

**Pull request closed without merging**
