### PR TITLE
Website updates for 6.0.0 final

### PR DESCRIPTION
**Pull request by edbratt**
- Updated download page
  - Updated compatibility records

Signed-off-by: Ed Bratt <ed.bratt@oracle.com>

### CODE REVIEW

**Comment by edbratt** [comment]
I've marked this DRAFT until 6.0.0 is actually available.

**Comment by arjantijms** [comment]
@edbratt GF 6 is now available in staging and can be moved to central with the push of a button. Can we merge this?

**Review by arjantijms — APPROVED** [review]

**Comment by arjantijms** [comment]
(we would need to adjust the final date before or right after merging)

**Comment by edbratt** [comment]
I will take care of this first thing in the morning.

**Comment by arjantijms** [comment]
@edbratt 
> I will take care of this first thing in the morning.

Thanks!

**Comment by edbratt** [comment]
Merge site updates for 6.0 final

**Pull request merged**
