### PR TITLE
Sync 6.x to master220213

### PR DESCRIPTION
**Pull request by dmatej**

### CODE REVIEW

**Review by hs536 — APPROVED** [review]

**Review by hs536 — DISMISSED** [review]
devtests seem to fail:
https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/job/PR-23804/1/

**Comment by dmatej** [comment]
> devtests seem to fail: https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/job/PR-23804/1/

There is an issue with Hibernate validator, we are waiting for the fix, I will try it locally.

**Comment by arjantijms** [comment]
@dmatej initial branch to look at: https://github.com/jakartaredhat/hibernate-validator

cc @starksm64

**Comment by dmatej** [comment]
I have created a PR for RedHat: https://github.com/jakartaredhat/hibernate-validator/pull/1
All tests I tried are passing now.

**Comment by dmatej** [comment]
Current status:
* web profile has still issues with hibernate validator
* JBatch fails one test (which wasn't executed on master branch until now)

**Comment by dmatej** [comment]
All issues fixed :-)

**Review by arjantijms — APPROVED** [review]

**Pull request merged**
