### PR TITLE
Configure the Concurrency TCK tests to produce log files in the "target" directory

### PR DESCRIPTION
**Pull request by OndroMih**

### CODE REVIEW

**Review by avpinchuk — APPROVED** [review]

**Comment by dmatej** [comment]
It would be better if they would be ignored under the target directory instead. Can you take a look if there is some option we should set for that?

**Comment by OndroMih** [comment]
> It would be better if they would be ignored under the target directory instead. Can you take a look if there is some option we should set for that?

I agree. I found a solution with `workingDirectory` for the `surefire` and `failsafe` plugins that I already used here: https://github.com/eclipse-ee4j/glassfish/pull/24576.

**Comment by OndroMih** [comment]
I found even a simpler solution, @dmatej I think this is what you meant initially :)

**Comment by OndroMih** [comment]
Please squash the commits when merging

**Review by arjantijms — APPROVED** [review]

**Comment by dmatej** [comment]
> I found even a simpler solution, @dmatej I think this is what you meant initially :)

Yeah, that was exactly that! I deleted those logs so many times but I was always lazy/distracted to resolve this issue, thanks! :-)

**Pull request merged**
