### PR TITLE
New infra - adjusting volumes  attempt 2

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: arjantijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Comment by arjantijms** [comment]
@romain-grecourt @hs536 @m0mus 

This PR with only minimal changes as suggested by ... has the same issue as the bigger PR with the GlassFish 6 changes:

> restart.server:
> 09:39:26       [echo] Restarting server...
> 09:39:26       [exec] Picked up JAVA_TOOL_OPTIONS: -Xmx2G
> 09:40:34       [exec] Waiting for the domain to stop ...........................................................
> 09:40:34       [exec] Command stop-domain failed.
> 09:40:34       [exec] Timed out (60 seconds) waiting for the domain to stop.

On the new infra it's seemingly no longer possible to detect GlassFish stopping, which causes all the tests to fail.

See also: https://bugs.eclipse.org/bugs/show_bug.cgi?id=551841

**Comment by romain-grecourt** [comment]
@arjantijms I'm guessing the catting of the settings.xml file is not meant to be merged right ?

**Comment by arjantijms** [comment]
>  I'm guessing the catting of the settings.xml file is not meant to be merged right ?

Nope, it's a debug output. Maybe it's better to merge in smaller steps, I'll remove it for now so this one is mergeable then.

**Review by bshannon — APPROVED** [review]
I have no idea how this is supposed to work so I'm not really competent to review this,
but I'll approve this anyway on the condition that you write up something for our wiki
that explains how to do this once you've really got it working.

**Pull request merged**
