### PR TITLE
Updated Jersey to 2.27

### PR DESCRIPTION
**Pull request by jansupol**
Signed-off-by: Jan Supol <jan.supol@oracle.com>

### CODE REVIEW

**Comment by smillidge** [comment]
Should these updates be on the EE4J_8 branch as I thought this branch was for JavaEE 8 compatibility? Will the updates affect?

**Comment by jansupol** [comment]
This is the version compatible with Java EE 8, it passes Java EE 8 CTS.

**Comment by jansupol** [comment]
@smillidge This is actually not the the last version that is supposed to be in this branch, AFAIK each EE4J_8 branch should contain a EE4J released project, which is API-wise compatible with latest version released with CDDI license

**Comment by smillidge** [comment]
OK I suppose later it will have the Jakarta dependency

**Review by vinayvishal — APPROVED** [review]
Looks good to me!!

**Pull request merged**
