### PR TITLE
Integrate jstl api 1.2.3

### PR DESCRIPTION
**Pull request by vinayvishal**

### CODE REVIEW

**Comment by vinayvishal** [comment]
@romain-grecourt , I am seeing constant quicklook failure locally (bulk of it failing) since the commit https://github.com/eclipse-ee4j/glassfish/commit/d560b8f21b614209d9c19b9eafbd0ab84d3fada6, with or without my changes. Prior to this commit, quicklook test pass with these changes. 
This is happening because Glassfish is not getting started in Felix mode. Here is the log from my quicklook run. Not sure if the issue is related to my environment. I am using `1.8.0_181`.

From below log, I can see following:
```
 [exec] Dec 05, 2018 12:50:04 PM com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner startBundles
 [exec] WARNING: Can not start bundle file:/home/vinay/glassfish5/glassfish/modules/javax.inject.jar because it is not contained in the list of installed bundles.
 [exec] Exception in thread "main" java.lang.reflect.InvocationTargetException
 [exec]     at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:73)
 [exec]     at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:30)
 [exec] Caused by: A MultiException has 2 exceptions.  They are:
```

```
     [exec] 1. com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [org.glassfish.main.resources.javamail-connector [58]], State = [NEW]
```
```
     [exec] 2. java.lang.IllegalStateException: Could not load descriptor SystemDescriptor(
     [exec]     implementation=org.glassfish.resources.javamail.config.MailResourceInjector
     [exec]     name=mail-resource
     [exec]     contracts=
```

Detailed log: 
```start-server-felix:
     [echo] +-----------------------------+
     [echo] |                             |
     [echo] | S T A R T I N G   GLASSFISH |
     [echo] |       in Felix mode         |
     [echo] |                             |
     [echo] +-----------------------------+

start-server-felix-unix:
     [exec] Waiting for domain1 to start ....
     [exec] Command start-domain failed.
     [exec] Error starting domain domain1.
     [exec] The server exited prematurely with exit code 1.
     [exec] Before it died, it produced the following output:
     [exec]
     [exec] Launching GlassFish on Felix platform
     [exec] Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime@6de70ee9 in service registry.
     [exec] Completed shutdown of GlassFish runtime
     [exec] We are in non-embedded mode, so org.glassfish.main.core.glassfish [134] has nothing to do.
     [exec] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=192m; support was removed in 8.0
     [exec] Dec 05, 2018 12:50:03 PM com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner createBundleProvisioner
     [exec] INFO: Create bundle provisioner class = class com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner.
     [exec] Dec 05, 2018 12:50:03 PM com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner$DefaultCustomizer getLocations
     [exec] WARNING: Skipping entry  because it is not an absolute URI.
     [exec] Dec 05, 2018 12:50:03 PM com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner$DefaultCustomizer getLocations
     [exec] WARNING: Skipping entry  because it is not an absolute URI.
     [exec] Dec 05, 2018 12:50:04 PM com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner startBundles
     [exec] WARNING: Can not start bundle file:/home/vinay/glassfish5/glassfish/modules/javax.inject.jar because it is not contained in the list of installed bundles.
     [exec] Exception in thread "main" java.lang.reflect.InvocationTargetException
     [exec]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:73)
     [exec]     at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:30)
     [exec] Caused by: A MultiException has 2 exceptions.  They are:
     [exec] 1. com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [org.glassfish.main.resources.javamail-connector [58]], State = [NEW]
     [exec] 2. java.lang.IllegalStateException: Could not load descriptor SystemDescriptor(
     [exec]     implementation=org.glassfish.resources.javamail.config.MailResourceInjector
     [exec]     name=mail-resource
     [exec]     contracts={org.glassfish.resources.javamail.config.MailResourceInjector,org.jvnet.hk2.config.ConfigInjector}
     [exec]     scope=javax.inject.Singleton
     [exec]     qualifiers={org.jvnet.hk2.config.InjectionTarget}
     [exec]     descriptorType=CLASS
     [exec]     descriptorVisibility=NORMAL
     [exec]     metadata=@object-type={optional,default\:user,datatype\:java.lang.String,leaf},@store-protocol={optional,default\:imap,datatype\:java.lang.String,leaf},@description={optional,datatype\:java.lang.String,leaf},@deployment-order={optional,default\:100,datatype\:java.lang.Integer,leaf},<property>={collection\:org.jvnet.hk2.config.types.Property,collection\:org.jvnet.hk2.config.types.Property},keyed-as={com.sun.enterprise.config.serverbeans.BindableResource},@transport-protocol={optional,default\:smtp,datatype\:java.lang.String,leaf},target={org.glassfish.resources.javamail.config.MailResource},@jndi-name={optional,datatype\:java.lang.String,leaf},@debug={optional,default\:false,datatype\:java.lang.Boolean,leaf},@user={optional,datatype\:java.lang.String,leaf},@enabled={optional,default\:true,datatype\:java.lang.Boolean,leaf,optional,default\:true,datatype\:java.lang.Boolean,leaf},@store-protocol-class={optional,default\:com.sun.mail.imap.IMAPStore,datatype\:java.lang.String,leaf},@transport-protocol-class={optional,default\:com.sun.mail.smtp.SMTPTransport,datatype\:java.lang.String,leaf},@host={optional,datatype\:java.lang.String,leaf},key={@jndi-name},@from={optional,datatype\:java.lang.String,leaf},Bundle-SymbolicName={org.glassfish.main.resources.javamail-connector},Bundle-Version={5.0.1.SNAPSHOT}

     [exec]     rank=0
     [exec]     loader=OsgiPopulatorPostProcessor.HK2Loader(OSGiModuleImpl:: Bundle = [org.glassfish.main.resources.javamail-connector [58]], State = [NEW],1747025217)
     [exec]     proxiable=null
     [exec]     proxyForSameScope=null
     [exec]     analysisName=null
     [exec]     id=188
     [exec]     locatorId=0
     [exec]     identityHashCode=449074057
     [exec]     reified=false)
     [exec]
     [exec]     at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2233)
     [exec]     at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:436)
     [exec]     at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:455)
     [exec]     at org.jvnet.hk2.config.DomDocument$InjectionTargetFilter.matches(DomDocument.java:160)
     [exec]     at org.jvnet.hk2.internal.ServiceLocatorImpl.getDescriptors(ServiceLocatorImpl.java:345)
     [exec]     at org.jvnet.hk2.internal.ServiceLocatorImpl.getDescriptors(ServiceLocatorImpl.java:387)
     [exec]     at org.jvnet.hk2.internal.ServiceLocatorImpl.getBestDescriptor(ServiceLocatorImpl.java:395)
     [exec]     at org.jvnet.hk2.config.DomDocument.buildModel(DomDocument.java:111)
     [exec]     at org.jvnet.hk2.config.ConfigModel.parseValue(ConfigModel.java:935)
     [exec]     at org.jvnet.hk2.config.ConfigModel.<init>(ConfigModel.java:851)
     [exec]     at org.jvnet.hk2.config.DomDocument.buildModel(DomDocument.java:90)
     [exec]     at org.jvnet.hk2.config.DomDocument.getModelByElementName(DomDocument.java:138)
     [exec]     at org.jvnet.hk2.config.ConfigParser.handleElement(ConfigParser.java:141)
     [exec]     at org.jvnet.hk2.config.ConfigParser.parse(ConfigParser.java:77)
     [exec]     at org.jvnet.hk2.config.ConfigParser.parse(ConfigParser.java:71)
     [exec]     at org.glassfish.config.support.DomainXml.parseDomainXml(DomainXml.java:235)
     [exec]     at org.glassfish.config.support.DomainXml.run(DomainXml.java:93)
     [exec]     at org.jvnet.hk2.config.ConfigurationPopulator.populateConfig(ConfigurationPopulator.java:34)
     [exec]     at org.glassfish.hk2.bootstrap.HK2Populator.populateConfig(HK2Populator.java:83)
     [exec]     at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.populateConfig(AbstractModulesRegistryImpl.java:187)
     [exec]     at com.sun.enterprise.module.bootstrap.Main.createServiceLocator(Main.java:249)
     [exec]     at org.jvnet.hk2.osgiadapter.HK2Main.createServiceLocator(HK2Main.java:95)
     [exec]     at com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime.newGlassFish(EmbeddedOSGiGlassFishRuntime.java:70)
     [exec]     at com.sun.enterprise.glassfish.bootstrap.GlassFishRuntimeDecorator.newGlassFish(GlassFishRuntimeDecorator.java:43)
     [exec]     at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishRuntime.newGlassFish(OSGiGlassFishRuntime.java:66)
     [exec]     at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:89)
     [exec]     ... 6 more
     [exec] Caused by: com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [org.glassfish.main.resources.javamail-connector [58]], State = [NEW]
     [exec]     at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:193)
     [exec]     at org.jvnet.hk2.osgiadapter.OsgiPopulatorPostProcessor$1.loadClass(OsgiPopulatorPostProcessor.java:54)
     [exec]     at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2225)
     [exec]     ... 31 more
     [exec] Caused by: org.osgi.framework.BundleException: Unable to resolve org.glassfish.main.resources.javamail-connector [58](R 58.0): missing requirement [org.glassfish.main.resources.javamail-connector [58](R 58.0)] osgi.wiring.package; (&(osgi.wiring.package=javax.mail)(version>=1.6.0)(!(version>=2.0.0))) [caused by: Unable to resolve com.sun.mail.jakarta.mail [75](R 75.0): missing requirement [com.sun.mail.jakarta.mail [75](R 75.0)] osgi.wiring.package; (&(osgi.wiring.package=javax.activation)(version>=1.2.0)(!(version>=2.0.0)))] Unresolved requirements: [[org.glassfish.main.resources.javamail-connector [58](R 58.0)] osgi.wiring.package; (&(osgi.wiring.package=javax.mail)(version>=1.6.0)(!(version>=2.0.0)))]
     [exec]     at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4149)
     [exec]     at org.apache.felix.framework.Felix.startBundle(Felix.java:2119)
     [exec]     at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
     [exec]     at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:185)
     [exec]     ... 33 more
     [exec]

```
In glassfish/modules directory, we have `jakarta.inject.jar` and not `javax.inject.jar`. I tried replacing the occurrences of `javax.inject.jar` in the codebase, with this, the above warning disappeared but other errors were still there.

Anything obvious??

**Review by romain-grecourt — APPROVED** [review]

**Comment by arjantijms** [comment]
@vinayvishal building the EE4J_8 branch with a totally clean m2/repo did the trick for me. I used the following before the build:

```
export MAVEN_OPTS="-Dmaven.repo.local=/opt/.gfm3"
```

Where `/opt/.gfm3` was an empty directory.

**Comment by romain-grecourt** [comment]
Yup, bad luck ; I'll restart it. Note that you can do that too since you have GF committer access.

**Comment by vinayvishal** [comment]
> @vinayvishal this may be related to an old version of the new javamail that was re-released. Try again with a clean maven repository.
> 
> The warning about javax.inject may be a different issue that needs to be addressed.

Thanks Romain!! It worked.

**Pull request merged**
