### PR TITLE
Upgrade hk2 and asm.

### PR DESCRIPTION
**Pull request by hs536**
ASM used by GlassFish requires version 7.0 or later to work on JDK 11.(https://asm.ow2.io/versions.html#7.0beta)
For osgi to work correctly, hk2 must also be upgraded to 2.6 or later.
The latest hk2 release is 2.6.1 and asm used in this version is 7.1 so upgraded hk2 to 2.6.1 and asm to 7.1.

* Upgrade hk2 to 2.6.1
  - Remove asm-all and asm-repackaged.
  - Rename Module class to HK2Module.
* Upgrade asm to 7.1
  - Replace the reference of ASM6 to AMS7.

I have confirmed that GlassFish was able to start on JDK 11 and that the Servlet app worked.  
(There are other issues that need to be resolved before QuickLook test can be passed such as #22878 .)

Signed-off-by: hs536 <sawamura.hiroki@fujitsu.com>

### CODE REVIEW

**Comment by hs536** [comment]
Most of the renaming to the HK2Module class was done with a script like the following, and the rest was done manually while resolving build errors.
```
SRC_HOME=/work/RS_GlassFish_JDK11/glassfish_pr
SRC_LIST=`find ${SRC_HOME} -type f -name "*.java" \
          |xargs grep "com.sun.enterprise.module." \
          |grep -v "module.Module[a-zA-Z]" \
          |cut -d':' -f 1`

for file in $SRC_LIST; do
  sed -i -e "s/com.sun.enterprise.module.Module;/com.sun.enterprise.module.HK2Module;/g" ${file}
  sed -i -e "s/ Module / HK2Module /g" ${file}
  sed -i -e "s/ Modules / HK2Modules /g" ${file}
  sed -i -e "s/ Module\[/ HK2Module\[/g" ${file}
  sed -i -e "s/<Module>/<HK2Module>/g" ${file}
  sed -i -e "s/,Module>/,HK2Module>/g" ${file}
  sed -i -e "s/<Module,/<HK2Module,/g" ${file}
  sed -i -e "s/(Module /(HK2Module /g" ${file}
  sed -i -e "s/ Module}/ HK2Module}/g" ${file}
  sed -i -e "s/\"Module /\"HK2Module /g" ${file}
done
```

**Review by bshannon — CHANGES_REQUESTED** [review]
I don't believe this should be approved until some significant number of existing tests pass.
quicklook is a bare minimum.  Some dev tests need to run, and for those that don't run there
needs to be a commitment to fix GlassFish to make them run *very* quickly.  We're struggling
to get all the CI tests to work reliably again and we can't afford more backsliding on CI tests.

**Comment by bshannon** [comment]
@russgold just want to make sure you're in the loop on this work.

**Comment by hs536** [comment]
I understand. I'm just making quicklook tests work on JDK11 right now. I'd like to request a merge after this.

**Comment by smillidge** [comment]
to be fair the PR is in to the JDK 11 branch not into master.

**Review by smillidge — APPROVED** [review]

**Comment by hs536** [comment]
@bshannon 
This fix is still unstable, but since it's one of the fixes needed to work quicklook and devtests on JDK 11, would it be possible to merge this fix into the 5.1.0-run-with-JDK11 branch (not into master)? (so is PR#22887)

**Comment by bshannon** [comment]
> @bshannon
> This fix is still unstable, but since it's one of the fixes needed to work quicklook and devtests on JDK 11, would it be possible to merge this fix into the 5.1.0-run-with-JDK11 branch (not into master)? (so is PR#22887)

I don't own that branch, and I forget who does, so you have to talk to them about merging
into that branch.  If you can get this fix working with at least quicklook before merging into
master, that would be a good start.

**Comment by hs536** [comment]
> > @bshannon
> > This fix is still unstable, but since it's one of the fixes needed to work quicklook and devtests on JDK 11, would it be possible to merge this fix into the 5.1.0-run-with-JDK11 branch (not into master)? (so is PR#22887)
> 
> I don't own that branch, and I forget who does, so you have to talk to them about merging
> into that branch. If you can get this fix working with at least quicklook before merging into
> master, that would be a good start.

Thanks. In that sense, I think this branch is under my management because it's a branch I created after consulting with Steve.
( https://www.eclipse.org/lists/glassfish-dev/msg00092.html )

**Comment by hs536** [comment]
Merge this pull request into the 5.1.0-run-with-JDK11 branch based on the following:
  - This is a pull request to the develop branch (5.1.0-run-with-JDK11), not the master branch.
  - 5.1.0-run-with-JDK11 branch is the one created by the member who issued this request.
  - This is a necessary fix to work the tests on JDK 11.
  - Has been approved by at least 1 reviewer.
  - Can be reviewed again when merging into the master branch.

**Pull request merged**
