### PR TITLE
Update uploadFrame.jsf

### PR DESCRIPTION
**Pull request by ayc868**
Can´t deploy applications from Web Console [deploy origPath is NULL

### CODE REVIEW

**Comment by Cousjava** [comment]
@ayc868 You need to sign the ECA (https://www.eclipse.org/legal/ECA.php) and sign-off your commit (git commit -s)

**Comment by DavidGradwell** [comment]
I'm still getting this problem on Glassfish 5.1.0.

**Comment by geekonthepc** [comment]
Can I sign the ECA and pick this up? The change @ayc868 is the required change, it just needs merging.

**Review by geekonthepc — APPROVED** [review]
This change is required to allow the WAR upload from the admin panel to function.

**Review by jGauravGupta — APPROVED** [review]

**Comment by geekonthepc** [comment]
If these build checks are failing because of the original author of the request not being covered, do we need a new pull request? If so, let me know and I'll do it. Really want this fixed before the release of GlassFish 6.

**Comment by arjantijms** [comment]
@geekonthepc If you want, please do a new PR. I'll close this PR then. Thx!

**Pull request closed without merging**
