### PR TITLE
Remove unused Ctor

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Comment by bshannon** [comment]
Did review of this fall through the cracks?
Or was this closed because it's no longer desired?

**Comment by pzygielo** [comment]
Closed as no other comment but by @glassfish-bot recevied for two months. So I assumed such change is not needed.

**Comment by bshannon** [comment]
It's more a case that all the people who are likely to review and merge these changes are super-busy
with work related to the Jakarta EE 8 release.  These minor cleanup changes were lower priority and
so no one has gotten back to them yet.  Sorry.

**Comment by pzygielo** [comment]
Not a problem, and understandable. Thank you Bill.
I keep open the first PR, as there was evidently time spent on by you and Steve.
We can always revisit them later.

**Review by Cousjava — APPROVED** [review]

**Pull request merged**
