### PR TITLE
Upgrade metro to 3.0.0

### PR DESCRIPTION
**Pull request by smillidge**
Signed-off-by: Steve Millidge <steve.millidge@payara.fish>

### CODE REVIEW

**Review by Cousjava — APPROVED** [review]

**Comment by lukasj** [comment]
what happens if I rebuild 3.0.0 now?

**Comment by smillidge** [comment]
Rebuild metro? This is in master so will be incorporated during the next build.

**Comment by lukasj** [comment]
Yes. The reason why I did not create PR for this myself at the time 3.0.0 was built was to do final testing and do last fixes this week (after days off)

**Comment by smillidge** [comment]
OK no problem. There were build failures as the milestone used by GlassFish was deleted from staging so I created this PR.

**Comment by smillidge** [comment]
Jakarta EE release will use GlassFish RC2 so there's no impact if you update the staged artefact.

**Comment by lukasj** [comment]
btw M3 used by GF 6-RC2 is back in staging

**Pull request merged**
