### PR TITLE
#22925: Remove Pruned API Jakarta XML RPC

### LINKED ISSUE #22925: Remove Pruned API Jakarta XML RPC
Gaurav is taking this one

### PR DESCRIPTION
**Pull request by lukasj**
fixes #22925

Signed-off-by: Lukas Jungmann <lukas.jungmann@oracle.com>

### CODE REVIEW

**Review by arjantijms — APPROVED** [review]
I spot checked the code. Even though I have some experience with the XML RPC code in GF, I trust that Lukas is the real expert here and able to do this correctly.

**Comment by arjantijms** [comment]
Builds locally and passes basic tests and ql_gf_web_profile_all. Some other tests are failing, but may well be unrelated to this PR and agreed to fix those later.

**Comment by arjantijms** [comment]
@lukasj one comment, but can be handled at the Metro project. Currently GF can't deploy apps anymore since Metro contains an initialiser `com.sun.xml.ws.transport.http.servlet.WSServletContainerInitializer`, but as soon this class is attempted to be loaded, resolving the bundle that contains it fails, since (of course) RPC isn't there anymore:

```
[org.glassfish.metro.webservices-osgi [29](R 29.0)] 
    osgi.wiring.package; 
   (&(osgi.wiring.package=javax.xml.rpc) (version>=1.1.0) (!(version>=2.0.0)))
```

**Comment by arjantijms** [comment]
@lukasj I staged a -m1 of Metro WSIT 3.0.0 where the JAX-RPC requirement was removed by you, and integrated this into GF. See https://github.com/eclipse-ee4j/glassfish/pull/22968

**Comment by lukasj** [comment]
I'd prefer if you reverted this change instead or did not merge it right away instead of messing around other projects. While metro should be ready around the next weekend doing all the preparations work, such as removing jaxr, jaxrpc, updating ejb-apis to not break the build are not feasible to be done by 1 person in 1 day. Having open PRs for such changes looks to me like the best approach for the time being.

**Comment by arjantijms** [comment]
>  I'd prefer if you reverted this change instead or did not merge it right away

@lukasj If the PR is not ready to be merged yet, that's no problem, but then it's best if you set the status to "draft". With that you clearly indicate the PR should not be merged yet, and it even prevents accidental merges, as the merge button is disabled.


> While metro should be ready around the next weekend doing all the preparations work, such as removing jaxr, jaxrpc, updating ejb-apis to not break the build are not feasible to be done by 1 person in 1 day. 

Yes, we know, and that holds for many other projects as well. Therefor we agreed in the GF project that things don't have to be perfect and can be merged in, and then corrected later. It's not how we'd do that in a perfect world of course, but given the size of the task and the little amount of resources there are few other options.

So don't worry, take your time for the next Metro version and it doesn't have to be perfect in one go.

**Pull request merged**
