### PR TITLE
Integrate jaxb-impl 3.0.1 final

### PR DESCRIPTION
**Pull request by lukasj**
QL passed on my end

### CODE REVIEW

**Review by arjantijms — APPROVED** [review]

**Comment by arjantijms** [comment]
@lukasj 

One question about 3.0.1, jaxb-osgi.jar contains this in `com.sun.istack.tools.Utils` for MR 9 (I stepped through it at runtime using the GlassFish QuickLook test:


```java
    static Authenticator getCurrentAuthenticator() {
        final Field f = getTheAuthenticator();
        if (f == null) {
            return null;
        }

        try {
            AccessController.doPrivileged((PrivilegedAction<Void>) () -> {
                f.setAccessible(true);
                return null;
            });
            return (Authenticator) f.get(null);
        } catch (IllegalAccessException | IllegalArgumentException ex) {
            LOGGER.log(Level.FINEST, "Cannot get Authenticator instance", ex);
            return null;
        } finally {
            AccessController.doPrivileged((PrivilegedAction<Void>) () -> {
                f.setAccessible(false);
                return null;
            });
        }
    }
```

The release 9 should be this:

https://github.com/eclipse-ee4j/jaxb-istack-commons/blob/master/istack-commons/tools/src/main/java-mr/9/com/sun/istack/tools/Utils.java

```java
/**
 *
 * @author lukas
 */
final class Utils {

    private Utils() {}

    static Authenticator getCurrentAuthenticator() {
        return Authenticator.getDefault();
    }
}
```

I tried running with JDK 16 (which forbids the illegal access by default), and got:

```
java.lang.reflect.InaccessibleObjectException: 
    Unable to make field private static volatile java.net.Authenticator java.net.Authenticator.theAuthenticator accessible: 
        module java.base does not "opens java.net" to unnamed module @56928e17
```

Test is essentially:

``` java
WsimportTool compTool = new WsimportTool(out);
compTool.run(arguments);
```

With arguments being:

```
-d, 
/glassfish/appserver/tests/quicklook/classes/test, 
-keep, 
-g, 
-verbose, 
/glassfish/appserver/tests/quicklook/wsit/JaxwsFromWsdl/etc/AddNumbers.wsdl, 
-b, 
/glassfish/appserver/tests/quicklook/wsit/JaxwsFromWsdl/etc/custom-server.xml
```

Any idea?

**Comment by lukasj** [comment]
@arjantijms 

`META-INF/MANIFEST.MF` contains `Multi-Release: true` and `javap` told me:

`ljungman-mac:jxb lukas$ javap -v jar:file:///Users/lukas/tmp/jxb/jaxb-osgi-3.0.1.jar\!/META-INF/versions/9/com/sun/istack/tools/Utils.class`:
```
Classfile jar:file:///Users/lukas/tmp/jxb/jaxb-osgi-3.0.1.jar!/META-INF/versions/9/com/sun/istack/tools/Utils.class
  Last modified Apr 6, 2021; size 430 bytes
  MD5 checksum 5c69c356e72b01afb22d364a618f2de9
  Compiled from "Utils.java"
final class com.sun.istack.tools.Utils
  minor version: 0
  major version: 53
  flags: (0x0030) ACC_FINAL, ACC_SUPER
  this_class: #3                          // com/sun/istack/tools/Utils
  super_class: #4                         // java/lang/Object
  interfaces: 0, fields: 0, methods: 2, attributes: 1
Constant pool:
...
{
  static java.net.Authenticator getCurrentAuthenticator();
    descriptor: ()Ljava/net/Authenticator;
    flags: (0x0008) ACC_STATIC
    Code:
      stack=1, locals=0, args_size=0
         0: invokestatic  #2                  // Method java/net/Authenticator.getDefault:()Ljava/net/Authenticator;
         3: areturn
      LineNumberTable:
        line 24: 0
}
SourceFile: "Utils.java"
```

`javap -v jar:file:///Users/lukas/tmp/jxb/jaxb-osgi-3.0.1.jar\!/com/sun/istack/tools/Utils.class`:
```
Classfile jar:file:///Users/lukas/tmp/jxb/jaxb-osgi-3.0.1.jar!/com/sun/istack/tools/Utils.class
  Last modified Apr 6, 2021; size 2826 bytes
  MD5 checksum 10bb15e9818227765b7b91e488e0bf26
  Compiled from "Utils.java"
final class com.sun.istack.tools.Utils
  minor version: 0
  major version: 52
  flags: (0x0030) ACC_FINAL, ACC_SUPER
  this_class: #23                         // com/sun/istack/tools/Utils
  super_class: #24                        // java/lang/Object
  interfaces: 0, fields: 1, methods: 6, attributes: 3
Constant pool:
...
{
  static java.net.Authenticator getCurrentAuthenticator();
    descriptor: ()Ljava/net/Authenticator;
    flags: (0x0008) ACC_STATIC
    Code:
      stack=4, locals=4, args_size=0
         0: invokestatic  #2                  // Method getTheAuthenticator:()Ljava/lang/reflect/Field;
         3: astore_0
         4: aload_0
         5: ifnonnull     10
         8: aconst_null
         9: areturn
        10: aload_0
        11: invokedynamic #3,  0              // InvokeDynamic #0:run:(Ljava/lang/reflect/Field;)Ljava/security/PrivilegedAction;
        16: invokestatic  #4                  // Method java/security/AccessController.doPrivileged:(Ljava/security/PrivilegedAction;)Ljava/lang/Object;
        19: pop
        20: aload_0
        21: aconst_null
        22: invokevirtual #5                  // Method java/lang/reflect/Field.get:(Ljava/lang/Object;)Ljava/lang/Object;
        25: checkcast     #6                  // class java/net/Authenticator
        28: astore_1
        29: aload_0
        30: invokedynamic #7,  0              // InvokeDynamic #1:run:(Ljava/lang/reflect/Field;)Ljava/security/PrivilegedAction;
        35: invokestatic  #4                  // Method java/security/AccessController.doPrivileged:(Ljava/security/PrivilegedAction;)Ljava/lang/Object;
        38: pop
        39: aload_1
        40: areturn
        41: astore_1
        42: getstatic     #10                 // Field LOGGER:Ljava/util/logging/Logger;
        45: getstatic     #11                 // Field java/util/logging/Level.FINEST:Ljava/util/logging/Level;
        48: ldc           #12                 // String Cannot get Authenticator instance
        50: aload_1
        51: invokevirtual #13                 // Method java/util/logging/Logger.log:(Ljava/util/logging/Level;Ljava/lang/String;Ljava/lang/Throwable;)V
        54: aconst_null
        55: astore_2
        56: aload_0
        57: invokedynamic #7,  0              // InvokeDynamic #1:run:(Ljava/lang/reflect/Field;)Ljava/security/PrivilegedAction;
        62: invokestatic  #4                  // Method java/security/AccessController.doPrivileged:(Ljava/security/PrivilegedAction;)Ljava/lang/Object;
        65: pop
        66: aload_2
        67: areturn
        68: astore_3
        69: aload_0
        70: invokedynamic #7,  0              // InvokeDynamic #1:run:(Ljava/lang/reflect/Field;)Ljava/security/PrivilegedAction;
        75: invokestatic  #4                  // Method java/security/AccessController.doPrivileged:(Ljava/security/PrivilegedAction;)Ljava/lang/Object;
        78: pop
        79: aload_3
        80: athrow
      Exception table:
         from    to  target type
            10    29    41   Class java/lang/IllegalAccessException
            10    29    41   Class java/lang/IllegalArgumentException
            10    29    68   any
            41    56    68   any
      LineNumberTable:
        line 31: 0
        line 32: 4
        line 33: 8
        line 37: 10
        line 41: 20
        line 46: 29
        line 41: 39
        line 42: 41
        line 43: 42
        line 44: 54
        line 46: 56
        line 44: 66
        line 46: 68
        line 50: 79
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
           42      26     1    ex   Ljava/lang/Exception;
            4      77     0     f   Ljava/lang/reflect/Field;
      StackMapTable: number_of_entries = 3
        frame_type = 252 /* append */
          offset_delta = 10
          locals = [ class java/lang/reflect/Field ]
        frame_type = 94 /* same_locals_1_stack_item */
          stack = [ class java/lang/Exception ]
        frame_type = 90 /* same_locals_1_stack_item */
          stack = [ class java/lang/Throwable ]

  static {};
    descriptor: ()V
    flags: (0x0008) ACC_STATIC
    Code:
      stack=1, locals=0, args_size=0
         0: ldc           #20                 // class com/sun/istack/tools/DefaultAuthenticator
         2: invokevirtual #21                 // Method java/lang/Class.getName:()Ljava/lang/String;
         5: invokestatic  #22                 // Method java/util/logging/Logger.getLogger:(Ljava/lang/String;)Ljava/util/logging/Logger;
         8: putstatic     #10                 // Field LOGGER:Ljava/util/logging/Logger;
        11: return
      LineNumberTable:
        line 26: 0
}
SourceFile: "Utils.java"
InnerClasses:
  public static final #122= #121 of #125; // Lookup=class java/lang/invoke/MethodHandles$Lookup of class java/lang/invoke/MethodHandles
BootstrapMethods:
  0: #55 REF_invokeStatic java/lang/invoke/LambdaMetafactory.metafactory:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
    Method arguments:
      #56 ()Ljava/lang/Object;
      #57 REF_invokeStatic com/sun/istack/tools/Utils.lambda$getCurrentAuthenticator$0:(Ljava/lang/reflect/Field;)Ljava/lang/Void;
      #58 ()Ljava/lang/Void;
  1: #55 REF_invokeStatic java/lang/invoke/LambdaMetafactory.metafactory:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
    Method arguments:
      #56 ()Ljava/lang/Object;
      #64 REF_invokeStatic com/sun/istack/tools/Utils.lambda$getCurrentAuthenticator$1:(Ljava/lang/reflect/Field;)Ljava/lang/Void;
      #58 ()Ljava/lang/Void;
```


that implies following:
* the jar itself is proper multi release jar
* the tool you used for debugging does not support multi-release jars properly
* ant and/or some maven plugin is/are too old (ant must be 1.10.7+)
* custom class/resourceloading which does not consider MR jars is used
* try `-Djdk.util.jar.enableMultiRelease=force` JVM option

**Comment by arjantijms** [comment]
> ant and/or some maven plugin is/are too old (ant must be 1.10.7+)

As per the issue in jaxb, this appeared to be the case. It's fixed now. Thanks again for all your help.

**Comment by lukasj** [comment]
@arjantijms if you are playing with JDK 16+, you may notice that jsr109 based deployment probably does not work properly - once you face this, file a bug in metro-jax-ws project with some simple test case (pointer to failing test), please.

In short - there is no API in JDK allowing one dynamically creating classes in not yet existing package as is currently mandated by the spec ([3.6.2.1](https://jakarta.ee/specifications/xml-web-services/3.0/jakarta-xml-ws-spec-3.0.html#j2wsdldocwrapped) and [3.7](https://jakarta.ee/specifications/xml-web-services/3.0/jakarta-xml-ws-spec-3.0.html#j2w11except)) at runtime, which former jsr109 needs to do. I'm not sure if and/or how it works on classpath mode which I believe GF is using but on JPMS, it's (known) problem on JDKs 16+

**Pull request merged**
