### PR TITLE
Upgrade to Jakarta Servlet API 4.0.2

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Signed-off-by: Stuart Douglas <sdouglas@redhat.com>

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
I am not sure why this is saying IP validation failed, I definitely have a contributor agreement signed for sdouglas@redhat.com.

**Comment by stuartwdouglas** [comment]
@vinayvishal what do I need to do to get a TCK run on this and get it merged?

**Comment by romain-grecourt** [comment]
@stuartwdouglas we are actively working on the PR automation. Details on how to run the CTS/TCKs will be provided soon. cc @m0mus @anajosep

**Comment by stuartwdouglas** [comment]
So is there anything I can do the get a release of the Serlet API sooner? Or am I blocked one GF PR automation?

**Review by romain-grecourt — APPROVED** [review]
approved, can be merged when pipeline passes.

**Comment by romain-grecourt** [comment]
@stuartwdouglas looks like the ip-validation failed because your sign-off does not match your commit author.

> The identity in the Signed-off-By must match the Author or the Committer.
stuartwdouglas

**Comment by stuartwdouglas** [comment]
The CI run failed but I am not really sure why? Its looks like some admin console related tests failed but they should not be related to the Servlet API as far as I can tell.

**Comment by romain-grecourt** [comment]
Looking at the test output [here](https://jenkins.eclipse.org/glassfish/blue/rest/organizations/jenkins/pipelines/glassfish/branches/PR-22615/runs/7/nodes/77/steps/410/log/?start=0) it failed because the admin console is not coming up after 60 seconds. Looking at the server.log from the test artifact [here](https://jenkins.eclipse.org/glassfish/job/glassfish/job/PR-22615/7/artifact/ql_gf_web_profile_all-results.tar.gz) I see that there is an error related to the deployment of the admin console:

```
[2018-11-29T04:26:20.070+0000] [glassfish 5.0] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=219 _ThreadName=Thread-71] [timeMillis: 1543465580070] [levelValue: 1000] [[
  Exception while deploying the app [__admingui]]]

[2018-11-29T04:26:20.071+0000] [glassfish 5.0] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=219 _ThreadName=Thread-71] [timeMillis: 1543465580071] [levelValue: 1000] [[
  Exception during lifecycle processing
com.sun.enterprise.module.ResolveError: Not able to locate a unique module by name jakarta.servlet-api
	at com.sun.enterprise.v3.server.ClassLoaderHierarchyImpl.createApplicationParentCL(ClassLoaderHierarchyImpl.java:148)
	at org.glassfish.deployment.common.DeploymentContextImpl.createClassLoader(DeploymentContextImpl.java:222)
	at org.glassfish.deployment.common.DeploymentContextImpl.createDeploymentClassLoader(DeploymentContextImpl.java:205)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:341)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:382)
	at com.sun.enterprise.v3.admin.adapter.InstallerThread.load(InstallerThread.java:187)
	at com.sun.enterprise.v3.admin.adapter.InstallerThread.run(InstallerThread.java:76)
]]

[2018-11-29T04:26:20.076+0000] [glassfish 5.0] [SEVERE] [NCLS-CORE-00041] [javax.enterprise.system.core] [tid: _ThreadID=219 _ThreadName=Thread-71] [timeMillis: 1543465580076] [levelValue: 1000] [[
  Application deployment failed: Exception while deploying the app [__admingui]]]
```

I think you should be able to reproduce this by running the quicklook tests locally. There is a pointer to the instructions for running the tests in the README.md at the top of the workspace.

**Comment by smillidge** [comment]
Comment I would suspect this change https://github.com/eclipse-ee4j/glassfish/pull/22615/files#diff-d9e3fd44282df051ffc711a3d0200a7bR81

**Comment by stuartwdouglas** [comment]
This build is looking better. It looks like this just runs the GF tests and not the TCK?

**Comment by stuartwdouglas** [comment]
This failure does not look related, it passed last build and EJB3 does not really have anything to do with Servlet.

**Comment by stuartwdouglas** [comment]
Does this mean that it has had a TCK run on it so I can perform the Servlet release?

**Comment by romain-grecourt** [comment]
No, this means that it passed the first set of tests in GF. In any case this is a final version so if there is something wrong you'd have to re-release it. We are still getting ready for CTS automation, @anajosep are you guys running it manually off the EE4J_8 branch ?

**Pull request merged**
