### PR TITLE
Integrate OpenMQ 6.5.0

### PR DESCRIPTION
**Pull request by arjantijms**
Changes: https://github.com/eclipse-ee4j/openmq/releases/tag/6.5.0-RELEASE

### CODE REVIEW

**Comment by OndroMih** [comment]
This one uses JDK21 in build, but still releases Java 11 compatible binaries, right? In master, for 6.6.0, the binaries are going to require Java 21 to run with this: https://github.com/eclipse-ee4j/openmq/pull/2024

**Comment by arjantijms** [comment]
Yes, so 6.6.0 is for GF 8 only.

**Review by dmatej — APPROVED** [review]

**Comment by pzygielo** [comment]
> This one uses JDK21 in build, but still releases Java 11 compatible binaries, right? 

Correct.

> Yes, so 6.6.0 is for GF 8 only.

I'd think that GF8 is for Jakarta EE 11, which seems to be Java 17+. Thus I think 6.5 will do for GF8 as well.

**Comment by OndroMih** [comment]
> I'd think that GF8 is for Jakarta EE 11, which seems to be Java 17+. Thus I think 6.5 will do for GF8 as well.

The final version of GF8 aims Jakarta EE 11 with Java 21+. We have 2 branches for GF 8 now - the main one, 8.0, has Java 21 as he baseline. 

The other branch, 8.0-JDK17, is a port of 8.0 to support Java 17, and aims to be used only to ratify and release Jakarta EE on Java 17. The aim is to use the 8.0 branch for GF 8 final and discard the 8.0-JDK17 branch after Jakarta EE 11 is released.

@pzygielo, do you think GF8 final should support also Java 17?

**Comment by pzygielo** [comment]
I meant the minimum Java version as listed here:
image
which introduces some limits.

**Comment by OndroMih** [comment]
Yes, but that doesn’t mean that Jakarta EE 11 implementations have to support Java 17. Jakarta EE will allow implementations to require Java 21.

**Pull request merged**
