### PR TITLE
Fixes classloader leak when a resource is retrieved

### PR DESCRIPTION
**Pull request by ctabin**
Fixes a potential leak when en resource is loaded from a class loaded in a EAR/JAR that is invoked from a dynamically loaded class by a custom ClassLoader.

When the resources stream are correctly loaded, the reference to the `throwable` is removed and hence there won't be any hard reference to classes that have no more reference, because otherwise this will prevent the ClassLoader to be GCed.

Those modifications are taken from https://github.com/payara/Payara/pull/6206.

### CODE REVIEW

**Review by dmatej — APPROVED** [review]

**Comment by ctabin** [comment]
@dmatej The build error doesn't seem related to my modifications. Maybe you can help ? Thanks !

```
23:24:22  Caused by: java.net.ConnectException: Connection refused
23:24:22  	at java.base/sun.nio.ch.Net.connect0(Native Method)
23:24:22  	at java.base/sun.nio.ch.Net.connect(Net.java:579)
23:24:22  	at java.base/sun.nio.ch.Net.connect(Net.java:568)
23:24:22  	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
23:24:22  	at java.base/java.net.Socket.connect(Socket.java:633)
23:24:22  	at java.base/java.net.Socket.connect(Socket.java:583)
23:24:22  	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
23:24:22  	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
23:24:22  	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
23:24:22  	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:279)
23:24:22  	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:384)
23:24:22  	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:406)
23:24:22  	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
23:24:22  	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
23:24:22  	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
23:24:22  	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
23:24:22  	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
23:24:22  	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
23:24:22  	at org.glassfish.main.admin.test.ClusterITest.getURL(ClusterITest.java:146)
```

**Comment by dmatej** [comment]
Not sure, I am trying to rerun tests, if they would fail again, I will try locally again in the morning (now we have midnight here ;-) )

**Comment by dmatej** [comment]
Locally it passed, but there was yet another build which failed at night, it seems that Jenkins had some networking issues.

**Review by dmatej — APPROVED** [review]

**Comment by dmatej** [comment]
> @dmatej Thanks for the merge, this is great. Do you have any possibility to approve/merge the one in [Payara](https://github.com/payara/Payara/pull/6206) ?

I am not in Payara for nearly two years any more, so I have no rights there. But I believe they will merge it too after it gets into some internal plan.

**Comment by ctabin** [comment]
@dmatej It seems that the `SentinelInputStream` is here to ensure that the provided `InputStream` by the ClassLoader are released with warning. After looking the source of the `URLClassLoader`, indeed all the resources are released, so this is redundant and the only difference would be the log of some warnings that don't seem to be so useful.

So, since less code means less bug, IMHO we could remove the `SentinelInputStream` altogether. I can provide a PR if you don't mind.

**Pull request merged**
