### PR TITLE
Update nucleus distribution release documentation

### PR DESCRIPTION
**Pull request by avpinchuk**
Try to make more accurate the nucleus distribution release documentation.

Signed-off-by: Alexander Pinčuk <alexander.v.pinchuk@gmail.com>

### CODE REVIEW

**Comment by avpinchuk** [comment]
I need help.

I don't now where this group https://javaee.groups.io/g/glassfish/ resides now.
And I don't now what to do with links to OTN.

**Review by dmatej — APPROVED** [review]

**Comment by dmatej** [comment]
@smillidge and @hs536 , perhaps @arjantijms or @edbratt, @ivargrimstad would know? Or should it be the Slack channel? Mailing lists?

**Comment by avpinchuk** [comment]
I find this:
https://www.eclipse.org/forums/index.php/f/419/

At first glance there is only one mailing list, https://accounts.eclipse.org/mailing-list/glassfish-dev. I doubt it is intended to public community support.

**Comment by dmatej** [comment]
Maybe the best would be to link just to the GlassFish homepage and maintain all links there. Keeping it in documentation seems quite limited .... we could even add a filter to StackOverflow, reddit, etc.
Btw maybe we should visit this forum more often: https://www.eclipse.org/forums/index.php/f/419/ I completely forgot it even exists :-)

**Comment by avpinchuk** [comment]
Good idea!

In this case at least 2 files look redundant: `features.html` and `quickstart.html`. They are duplicates of *Release Notes* and *Quick Start Guide*.

**Review by arjantijms — APPROVED** [review]

**Pull request merged**
