### PR TITLE
Tests to reproduce #24059

### PR DESCRIPTION
**Pull request by OndroMih**
Also creates a  new Jakarta EE test suite, which now contains only this test for Concurrency.

The test is failing now as expected, need to fix the issue.

### CODE REVIEW

**Comment by dmatej** [comment]
Just a note for myself - Jenkins `#1` failed due to missing dependency.
` Failed to execute goal on project jakarta.enterprise.concurrent-tck-ext: Could not resolve dependencies for project org.glassfish.main.tests.jakartaee:jakarta.enterprise.concurrent-tck-ext:jar:7.0.0-SNAPSHOT: Could not find artifact jakarta.enterprise.concurrent:jakarta.enterprise.concurrent-tck:jar:3.0.2 in eclipse.maven.central.mirror (https://repo.eclipse.org/content/repositories/maven_central/) -> [Help 1]`

**Comment by OndroMih** [comment]
> Just a note for myself
Yes, the Concurrency TCK 3.0.2 isn't released yet. The Concurrency team is about to release it soon, they just need to sort out Jenkins jobs to do it. I tested against the snapshot version built locally.

**Comment by OndroMih** [comment]
And even then this new test will fail until https://github.com/omnifaces/omniconcurrent/pull/1is fixed, released and integrated to GlassFish.

**Comment by dmatej** [comment]
> And even then this new test will fail until https://github.com/omnifaces/omniconcurrent/pull/1is fixed, released and integrated to GlassFish.

Yep, I understood that from the description ;-)

**Comment by dmatej** [comment]
Oh, I see what Jenkins doesn't like. I will finish it tomorrow, thanks!

**Comment by OndroMih** [comment]
Concurrency TCK 3.0.2 was finally deployed to Maven Central: https://mvnrepository.com/artifact/jakarta.enterprise.concurrent/jakarta.enterprise.concurrent-tck

What remains now is to release a new version of OmniConcurrent to Maven Central too.

**Review by dmatej — APPROVED** [review]

**Pull request merged**
