### PR TITLE
Code clean up (Remove commented code/remove unused imports) of Asadmi…

### PR DESCRIPTION
**Pull request by h-hub**
Code clean up of AsadminMain

Signed-off-by: h-hub <harsha.kj89@gmail.com>

### CODE REVIEW

**Review by bshannon — CHANGES_REQUESTED** [review]
First, the simple comment...

This change introduces a bunch of gratuitous white space changes that use the wrong indentation.

But the bigger issue...

It appears that the Metrix class is an almost-no-longer-used performance measurement class.
The one other remaining use is in admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLIContainer.java.

If the class is still useful, the commented out code should remain, so that it can be
easily enabled in the future.

If the Metrix class is no longer useful, an issue should filed, and the class itself should be
removed, along with the references in AsadminMain and CLIContainer.

I would like to get feedback from others on the utility of the Metrix class.

**Comment by h-hub** [comment]
Hi @bshannon,

When it comes to indentations, I believe I have followed these guidelines.
https://wiki.eclipse.org/Coding_Conventions.

To remove the gratuitous white space, should I remove line 28 and 33?

Sorry for the noob questions. I'm new to opensource contribution.

**Comment by bshannon** [comment]
> When it comes to indentations, I believe I have followed these guidelines.
> https://wiki.eclipse.org/Coding_Conventions.

I doesn't say it explicitly, but I believe that document applies to the Eclipse IDE, not to all projects at eclipse.org.

In any event, rule #0 for coding conventions is to follow the style of the code you're modifying.
In the case of GlassFish, most code uses spaces for indentation, not tab characters, with
"tab stops" for indentation every 4 characters.

And since you're not changing some of those lines of code, there's no reason to change the
indentation for those lines of code.  Since your goal was to remove some lines of code, the
"diff" output should show only those changes and no changes to other lines of code.

Also, I hope you understood my other comments about whether this code should be removed
or not.

**Comment by h-hub** [comment]
Hi @bshannon,

I understand and Thanks for the information.

**Comment by arjantijms** [comment]
Is this PR still relevant? If not, let's close it.

**Comment by h-hub** [comment]
It is not relevant. Closing now.

**Pull request closed without merging**
