### PR TITLE
Incorporate IP review comments

### PR DESCRIPTION
**Pull request by vinayvishal**

### CODE REVIEW

**Comment by vinayvishal** [comment]
Quicklook tests were successful: (Are few tests disabled, seeing a total count of 104 instead of 110 without any failures)
```
     [echo]    [testng] ===============================================
     [echo]    [testng] QuickLookTests
     [echo]    [testng] Total tests run: 104, Failures: 0, Skips: 0
     [echo]    [testng] ===============================================
```

**Comment by vinayvishal** [comment]
Seeing following error with the build:
```
org.glassfish.jersey.media:jersey-media-json-processing:jar:2.27 -> org.glassfish:jsonp-jaxrs:jar:1.1.3:  
Failed to read artifact descriptor for org.glassfish:jsonp-jaxrs:jar:1.1.3: Could not transfer artifact 
org.glassfish:jsonp-jaxrs:pom:1.1.3 from/to sonatype-nexus-staging 
(https://oss.sonatype.org/content/repositories/staging): java.lang.RuntimeException: Unexpected error: 
java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty -> [Help 1]

```
`JSON-P 1.1.3` is there in Maven Central [[1](https://repo1.maven.org/maven2/org/glassfish/jsonp-jaxrs/1.1.3/)], not sure why it is looking for it in staging repository.

**Review by bshannon — APPROVED** [review]
Generally looks fine, although some of the html files would benefit from line breaks
so I don't have to scroll horizontally to review them.

**Comment by romain-grecourt** [comment]
@vinayvishal the issue is related to SSL access to oss.sonatype.org. It fails because it checks for the artifact in oss-staging first and for whatever reason maven gives up at this point. I have a fix pending in a PR. You'll need to refresh this branch for the pipeline to pass.

**Comment by romain-grecourt** [comment]
Actually, refreshing the branch may not be required. I've retried the pipeline will see what happens.

**Pull request merged**
