### PR TITLE
Mega Jakarta Namespace PR READY FOR REVIEW

### PR DESCRIPTION
**Pull request by smillidge**
This now compiles on Jenkins and is ready for review. Once merged we can go back to working off master.

### CODE REVIEW

**Comment by jGauravGupta** [comment]
PR includes namespace transition for following specs:

- `jakarta.faces`
- `jakarta.ejb`
- `jakarta.servlet`
- `jakarta.enterprises`
- `jakarta.persistence`
- `jakarta.transaction`
- `jakarta.resource`
- `jakarta.interceptor`

- [ ] Needs a RC or Milestone release of `jsftemplating` currently references a SNAPSHOT

**Comment by smillidge** [comment]
Any blockers at the moment other than snapshots?

**Comment by jGauravGupta** [comment]
No blockers other than listed snapshots to build the project successfully. Although having an OSGi issue in starting the domain due to missing release of Jakartafied Hk2.

**Comment by smillidge** [comment]
OK I will check and push to get some of the snapshots released to maven central.

**Comment by smillidge** [comment]
HK2 3.0.0-M1 is now on staging

**Comment by arjantijms** [comment]
PR for -M1 JSTL and -M1 JSFTemplate done here:

https://github.com/smillidge/glassfish/pull/1

**Comment by arjantijms** [comment]
PR for -M1 Woodstock done here: 

https://github.com/smillidge/glassfish/pull/2

**Review by arjantijms — APPROVED** [review]

**Comment by arjantijms** [comment]
Confirmed that I compiles here locally.

**Pull request merged**
